import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Game} from './server.mjs';
import {HERD,validateHerd} from './herd.mjs';
import {HERD_PROMPTS} from './pack-content.mjs';
import {cloudRequest} from './cloud-game.mjs';
// Party (pot rules). herd:true makes this round the second Same Brain of the night.
const party=(n,{herd=true,chips={}}={})=>{const g=new Game(),{code}=g.create('Host'),r=g.rooms.get(code);for(let i=1;i<n;i++)g.join(code,'Player '+i);r.banEnabled=false;r.enabledGames=['brain'];r.brainRounds=herd?1:0;for(const [i,c] of Object.entries(chips))r.players[i].chips=c;g.fresh(r);let guard=0;while(!['herdWrite','play'].includes(r.phase)){assert.ok(guard++<10,r.phase);g.advance(r);}return {g,r,p:r.players};};
const minigame=n=>{const g=new Game(),{code}=g.create('Host','minigames'),r=g.rooms.get(code);for(let i=1;i<n;i++)g.join(code,'Player '+i);g.action(r,r.players[0],{type:'selectGame',game:'brain'});g.action(r,r.players[0],{type:'start'});g.begin(r);return {g,r,p:r.players};};
const by=(r,id)=>r.players.find(p=>p.id===id);
const ask=(g,r,q={question:'Beach or mountains?',a:'Beach',b:'Mountains'})=>g.action(r,by(r,r.herd.asker),{type:'herdAsk',...q});
// sides: one entry per voter in seat order ('a', 'b' or null for no tap). Time runs out if anyone skips.
const vote=(g,r,sides)=>{r.herd.voters.forEach((id,i)=>{if(sides[i]&&r.phase==='herdVote')g.action(r,by(r,id),{type:'herdVote',side:sides[i]});});if(r.phase==='herdVote')g.advance(r);};
const finish=(g,r)=>{let guard=0;while(r.phase!=='result'){assert.ok(guard++<10,r.phase);g.advance(r);}};
const wealth=r=>r.players.reduce((s,p)=>s+p.chips,0)+(r.potSettled?0:Object.values(r.stakes||{}).reduce((a,b)=>a+b,0))+(r.carry||0);

test('2 and 3 players: Same Brain stays standard every round',()=>{for(const n of [2,3]){const {g,r}=minigame(n);for(let i=0;i<4;i++){assert.equal(r.phase,'play');assert.equal(r.herd,null);finish(g,r);g.action(r,r.players[0],{type:'replay'});g.begin(r);}}
 const {r}=party(3);assert.equal(r.phase,'play');assert.equal(r.herd,null);});
test('4+ players: standard first, then Herd every other Same Brain round',()=>{const {g,r}=minigame(4),seen=[];for(let i=0;i<6;i++){seen.push(!!r.herd);assert.equal(r.phase,r.herd?'herdWrite':'play');finish(g,r);g.action(r,r.players[0],{type:'replay'});g.begin(r);}assert.deepEqual(seen,[false,true,false,true,false,true]);});
test('writer rotates through players in seat order, then loops',()=>{const {g,r,p}=minigame(4),askers=[];for(let i=0;i<10;i++){if(r.herd)askers.push(r.herd.asker);finish(g,r);g.action(r,p[0],{type:'replay'});g.begin(r);}assert.deepEqual(askers,[p[0].id,p[1].id,p[2].id,p[3].id,p[0].id]);});
test('writer sits out: not active, not a voter, pays no entry',()=>{const {r,p}=party(4);const asker=r.herd.asker;assert.equal(asker,p[0].id);assert.ok(!r.active.includes(asker)&&!r.contestants.includes(asker)&&!r.herd.voters.includes(asker));assert.equal(r.stakes[asker]||0,0);assert.equal(p[0].chips,100);assert.equal(r.herd.voters.length,3);});
test('validation: lengths, trimming, different options, writer only, vote rules',()=>{const {g,r,p}=party(5);const writer=by(r,r.herd.asker),voter=by(r,r.herd.voters[0]);
 for(const [q,re] of [[{question:'  ',a:'A',b:'B'},/question first/],[{question:'x'.repeat(91),a:'A',b:'B'},/90/],[{question:'Q?',a:'',b:'B'},/both options/],[{question:'Q?',a:'x'.repeat(31),b:'B'},/30/],[{question:'Q?',a:'Beach',b:' beach '},/different/]])assert.throws(()=>g.action(r,writer,{type:'herdAsk',...q}),re);
 assert.throws(()=>g.action(r,voter,{type:'herdAsk',question:'Q?',a:'A',b:'B'}),/Only the writer/);assert.throws(()=>g.action(r,voter,{type:'herdVote',side:'a'}),/Wait for the question/);
 assert.deepEqual(validateHerd({question:'  Beach \t  or mountains? ',a:' Big  wave ',b:'Hike'}),{question:'Beach or mountains?',a:'Big wave',b:'Hike'});
 g.action(r,writer,{type:'herdAsk',question:'  Beach   or mountains? ',a:' Beach ',b:'Mountains'});assert.equal(r.phase,'herdVote');assert.equal(r.herd.question,'Beach or mountains?');assert.equal(r.herd.stock,false);
 assert.throws(()=>g.action(r,writer,{type:'herdVote',side:'a'}),/You wrote this one/);assert.throws(()=>g.action(r,voter,{type:'herdVote',side:'c'}),/A or B/);
 g.action(r,voter,{type:'herdVote',side:'a'});assert.throws(()=>g.action(r,voter,{type:'herdVote',side:'b'}),/locked/);assert.equal(r.herd.votes[voter.id],'a');
 assert.equal(validateHerd({question:'x'.repeat(90),a:'y'.repeat(30),b:'z'}).question.length,90);});
test('stock prompts: about 40, all valid, no em dashes; timeout and a leaving writer fall back to one',()=>{assert.ok(HERD_PROMPTS.length>=40);for(const [q,a,b] of HERD_PROMPTS){validateHerd({question:q,a,b});assert.ok(!/[\u2013\u2014]/.test(q+a+b));}
 let {g,r}=party(4);g.advance(r);assert.equal(r.phase,'herdVote');assert.equal(r.herd.stock,true);assert.ok(HERD_PROMPTS.some(x=>x[0]===r.herd.question));assert.equal(r.prompt,r.herd.question);assert.ok(r.deadline-Date.now()<=HERD.voteSeconds*1000);
 ({g,r}=minigame(4));finish(g,r);g.action(r,r.players[0],{type:'replay'});g.begin(r);assert.equal(r.phase,'herdWrite');g.action(r,by(r,r.herd.asker),{type:'leave',round:r.round});assert.equal(r.phase,'herdVote');assert.equal(r.herd.stock,true);vote(g,r,['a','a','b']);assert.equal(r.phase,'result');});
test('majority is the Herd: bigger side splits the pot evenly, leftover chips carry, smaller side loses its entry',()=>{const {g,r}=party(6);ask(g,r);vote(g,r,['a','b','a','b','a']);const o=r.herd.outcome,v=r.herd.voters;
 assert.deepEqual(r.result.winners,[v[0],v[2],v[4]]);assert.equal(r.result.tie,false);assert.equal(o.sheep,null);assert.equal(o.easy,false);assert.equal(r.result.changes[v[1]],-5);assert.equal(r.result.changes[v[3]],-5);assert.deepEqual([v[0],v[2],v[4]].map(id=>r.result.changes[id]),[3,3,3]);assert.equal(r.carry,1);assert.equal(r.result.carry,1);assert.equal(by(r,r.herd.asker).chips,100);assert.equal(wealth(r),600);assert.match(r.result.detail,/Beach wins/);});
test('lone Black Sheep pays a multiple of the winner count (10 with 3 winners pays 9); capped, never below 0; winnings stay even',()=>{let {g,r,p}=party(5);ask(g,r);vote(g,r,['a','a','b','a']);let v=r.herd.voters;assert.equal(r.herd.outcome.sheep,v[2]);assert.equal(r.herd.outcome.penalty,9);assert.equal(r.result.changes[v[2]],-14);assert.equal(by(r,v[2]).chips,86);assert.deepEqual([v[0],v[1],v[3]].map(id=>r.result.changes[id]),[4,4,4]);assert.equal(r.carry,2);assert.equal(wealth(r),500);assert.match(r.result.detail,/Black Sheep: Player 3/);
 ({g,r,p}=party(5,{chips:{3:8}}));ask(g,r);v=r.herd.voters;assert.equal(v[2],p[3].id);vote(g,r,['a','a','b','a']);assert.equal(r.herd.outcome.penalty,3);assert.equal(p[3].chips,0);assert.equal(r.result.changes[p[3].id],-8);assert.deepEqual([v[0],v[1],v[3]].map(id=>r.result.changes[id]),[2,2,2]);assert.equal(wealth(r),408);
 ({g,r,p}=party(6));ask(g,r);vote(g,r,['a','a','b','a','a']);assert.equal(r.herd.outcome.penalty,8,'4 winners: 10 rounds down to 8');assert.equal(r.carry,1);assert.deepEqual(r.herd.voters.filter((id,i)=>i!==2).map(id=>r.result.changes[id]),[3,3,3,3]);assert.equal(wealth(r),600);});
test('unanimous: every voter wins their entry back plus an even share of the writer’s penalty; the writer pays for the no-brainer',()=>{let {g,r,p}=party(4);ask(g,r);vote(g,r,['b','b','b']);const o=r.herd.outcome,v=r.herd.voters;assert.equal(o.easy,true);assert.equal(o.payer,p[0].id);assert.equal(o.penalty,9);assert.deepEqual(r.result.winners,v);assert.equal(r.result.tie,false);assert.equal(p[0].chips,91);assert.equal(r.result.changes[p[0].id],-9);assert.deepEqual(v.map(id=>r.result.changes[id]),[3,3,3]);assert.equal(r.carry,0);assert.equal(wealth(r),400);assert.match(r.result.detail,/Too easy: Host pays/);
 ({g,r,p}=party(4,{chips:{0:6}}));ask(g,r);vote(g,r,['a','a','a']);assert.equal(p[0].chips,0);assert.equal(r.herd.outcome.penalty,6);assert.equal(wealth(r),306);});
test('carry joins the next pot that has winners, split evenly; leftovers at the end go to the chip leader',()=>{const {g,r,p}=party(5);ask(g,r);vote(g,r,['a','a','b','a']);assert.equal(r.carry,2);
 g.action(r,p[0],{type:'next'});let guard=0;while(r.phase!=='play'){assert.ok(guard++<10,r.phase);g.advance(r);}assert.equal(r.herd,null);const [x,y,...rest]=r.active;
 for(const id of r.active)g.action(r,by(r,id),{type:'submit',value:[x,y].includes(id)?'pizza':'answer '+id});assert.equal(r.phase,'result');assert.deepEqual(r.result.winners.sort(),[x,y].sort());assert.equal(r.result.bonus,1);assert.equal(r.carry,0);assert.equal(r.result.carry,0);assert.equal(wealth(r),500);
 r.carry=3;const lead=p.reduce((a,b)=>b.chips>a.chips?b:a),before=lead.chips;g.phase(r,'finished');assert.equal(lead.chips,before+3);assert.equal(r.carry,0);assert.deepEqual(r.carryAwarded,{player:lead.id,amount:3});});
test('tie: nobody wins, everyone gets their entry back, no penalty',()=>{const {g,r,p}=party(5);ask(g,r);vote(g,r,['a','b','b','a']);assert.equal(r.result.tie,true);assert.deepEqual(r.result.winners,[]);assert.equal(r.herd.outcome.payer,null);assert.ok(p.every(q=>q.chips===100));assert.match(r.result.detail,/Tie/);
 const x=party(4);ask(x.g,x.r);x.g.advance(x.r);assert.equal(x.r.result.tie,true);assert.ok(x.p.every(q=>q.chips===100),'nobody picked');});
test('no tap counts as the losing side; it never makes a Black Sheep or a no-brainer; the split is even',()=>{const {g,r}=party(5);ask(g,r);vote(g,r,['a','a',null,'a']);const v=r.herd.voters,o=r.herd.outcome;assert.deepEqual(o.missed,[v[2]]);assert.equal(o.easy,false);assert.equal(o.sheep,null);assert.equal(r.result.changes[v[2]],-5);assert.ok(!r.result.winners.includes(v[2]));assert.deepEqual([v[0],v[1],v[3]].map(id=>r.result.changes[id]),[1,1,1]);assert.equal(r.carry,2);assert.equal(by(r,r.herd.asker).chips,100);assert.equal(wealth(r),500);});
test('vote closes early once every voter locks in; a voter leaving does not stall it',()=>{const {g,r}=party(5);ask(g,r);const v=r.herd.voters;g.action(r,by(r,v[0]),{type:'herdVote',side:'a'});g.action(r,by(r,v[1]),{type:'herdVote',side:'a'});g.action(r,by(r,v[2]),{type:'herdVote',side:'b'});assert.equal(r.phase,'herdVote');g.action(r,by(r,v[3]),{type:'leave',round:r.round});assert.equal(r.phase,'result');assert.equal(wealth(r),500);});
test('Minigames: callouts only, no chips move',()=>{const {g,r,p}=minigame(4);finish(g,r);g.action(r,p[0],{type:'replay'});g.begin(r);ask(g,r);vote(g,r,['a','a','b']);assert.equal(r.herd.outcome.sheep,r.herd.voters[2]);assert.equal(r.herd.outcome.penalty,0);assert.ok(p.every(q=>q.chips===100));assert.equal(r.result.winners.length,2);});
test('privacy: no one sees another player’s pick before the reveal; herd prompts are never rated',()=>{const {g,r,p}=party(5);let rated=0;g.onRate=()=>rated++;
 assert.equal(g.view(r,p[1]).herd.question,'');ask(g,r,{question:'SECRET Q',a:'Left',b:'Right'});const v=r.herd.voters;g.action(r,by(r,v[0]),{type:'herdVote',side:'b'});
 for(const q of p){const h=g.view(r,q).herd;assert.equal(h.question,'SECRET Q');assert.equal(h.locked,1);assert.equal('votes' in h,false);assert.equal(h.reveal,undefined);assert.equal(h.mine,q.id===v[0]?'b':null);}
 const pub=g.publicView(r);assert.equal(pub.herd.mine,null);assert.equal('votes' in pub.herd,false);assert.deepEqual(pub.answers,{});
 vote(g,r,[null,'a','a','a']);assert.equal(r.phase,'result');const rv=g.view(r,p[1]);assert.deepEqual(rv.herd.reveal.B,[v[0]]);assert.equal(rv.rating,null);assert.throws(()=>g.action(r,p[1],{type:'rate',vote:'fire'}));assert.equal(rated,0);});
test('cloud path: Herd round round-trips through serialized state',async()=>{
 class Store{data=new Map();async get(k){return this.data.get(k)||null;}async compareAndSwap(k,b,a){await new Promise(resolve=>setImmediate(resolve));if((this.data.get(k)||null)!==b)return false;this.data.set(k,a);return true;}}
 const s=new Store(),host=await cloudRequest(s,{type:'create',name:'Host',mode:'minigames'});const guests=[];for(let i=0;i<4;i++)guests.push(await cloudRequest(s,{type:'join',code:host.code,name:'Guest '+i}));
 await cloudRequest(s,{...host,type:'selectGame',game:'brain'});const room=JSON.parse(await s.get(host.code));room.brainRounds=1;s.data.set(host.code,JSON.stringify(room));
 await cloudRequest(s,{...host,type:'start'});await cloudRequest(s,{...host,type:'beginGame'});let st=await cloudRequest(s,guests[0],{state:true});assert.equal(st.phase,'herdWrite');assert.equal(st.herd.youAsk,false);
 await assert.rejects(cloudRequest(s,{...guests[0],type:'herdAsk',question:'Q?',a:'A',b:'B'}));await cloudRequest(s,{...host,type:'herdAsk',question:'Tea or coffee?',a:'Tea',b:'Coffee'});
 await Promise.all(guests.map((a,i)=>cloudRequest(s,{...a,type:'herdVote',side:i<3?'a':'b'})));st=await cloudRequest(s,host,{state:true});
 assert.equal(st.phase,'result');assert.equal(st.herd.reveal.A.length,3);assert.equal(st.herd.reveal.sheep,st.herd.reveal.B[0]);assert.equal(JSON.stringify(st).includes(host.token),false);
 // Timers work from stored deadlines too: an overdue write phase falls back to a stock prompt on the next read.
 await cloudRequest(s,{...host,type:'replay'});await cloudRequest(s,{...host,type:'beginGame'});st=await cloudRequest(s,host,{state:true});assert.equal(st.phase,'play');
 const x=JSON.parse(await s.get(host.code));x.brainRounds=1;x.phase='result';s.data.set(host.code,JSON.stringify(x));await cloudRequest(s,{...host,type:'replay'});await cloudRequest(s,{...host,type:'beginGame'});
 const y=JSON.parse(await s.get(host.code));assert.equal(y.phase,'herdWrite');y.deadline=Date.now()-1;s.data.set(host.code,JSON.stringify(y));st=await cloudRequest(s,host,{state:true});assert.equal(st.phase,'herdVote');assert.equal(st.herd.stock,true);});
test('TV and phone screens: writing, live lock count, reveal with sheep and callout; no em dashes',async()=>{const {render}=await import('./public/display.js');const {herdScreen}=await import('./public/herd-ui.js');
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const phone=(g,r,q)=>{const s=g.view(r,q),name=id=>esc(s.players.find(x=>x.id===id)?.name),btn=(t,a)=>`<button data-action="${a}">${t}</button>`,heading=(l,t)=>`<h2>${l}</h2><h1>${t}</h1>`;return herdScreen(s,{esc,name,btn,heading,host:q.id===s.host});};
 const {g,r,p}=party(5);let tv=render(g.publicView(r)).html;assert.match(tv,/Host is writing…/);assert.match(phone(g,r,p[1]),/Host is writing…/);assert.match(phone(g,r,p[0]),/id="herdForm"/);
 ask(g,r,{question:'<b>Pick</b>',a:'Cats & dogs',b:'Fish'});g.action(r,p[1],{type:'herdVote',side:'b'});tv=render(g.publicView(r)).html;assert.match(tv,/1 of 4 picked/);assert.ok(tv.includes('&lt;b&gt;Pick&lt;/b&gt;'));assert.ok(!tv.includes('<b>Pick'));
 assert.match(phone(g,r,p[1]),/Locked: Fish/);assert.match(phone(g,r,p[2]),/data-action="herdVote:a"[^]*data-action="herdVote:b"/);assert.match(phone(g,r,p[0]),/Your question/);
 vote(g,r,[null,'a','a','a']);tv=render(g.publicView(r)).html;assert.match(tv,/🐑 Black Sheep<\/span> Player 1/);assert.match(tv,/Cats &amp; dogs wins/);assert.ok(!/[\u2014]/.test(tv));
 const res=phone(g,r,p[1]);assert.match(res,/🐑 Black Sheep: Player 1/);assert.match(phone(g,r,p[0]),/Next round/);assert.ok(!/[\u2014]/.test(res));
 const u=party(4);ask(u.g,u.r);vote(u.g,u.r,['a','a','a']);assert.match(render(u.g.publicView(u.r)).html,/Too easy<\/span> Host · pays 9 chips/);assert.match(phone(u.g,u.r,u.p[1]),/Too easy: Host pays/);});
test('Party sessions with Herd rounds conserve chips and finish',()=>{for(const n of [4,6]){const g=new Game(),{code}=g.create('Host'),r=g.rooms.get(code);for(let i=1;i<n;i++)g.join(code,'P'+i);r.banEnabled=false;r.enabledGames=['brain'];r.totalRounds=9;g.fresh(r);let steps=0,herds=0;
 while(r.phase!=='finished'){assert.ok(steps++<300,r.phase);if(r.phase==='herdWrite'){herds++;ask(g,r);}else if(r.phase==='herdVote'){vote(g,r,r.herd.voters.map((id,i)=>herds%2&&!i?'b':'a'));}else if(r.phase==='play'){for(const id of [...r.active])if(r.phase==='play')g.action(r,by(r,id),{type:'submit',value:'pizza'});}else if(r.phase==='result')g.action(r,r.players[0],{type:'next'});else g.advance(r);if(r.potSettled||r.phase==='finished')assert.equal(r.players.reduce((t,q)=>t+q.chips,0)+(r.carry||0)-(r.issuedChips||0),n*100,`${r.phase} ${r.round}`);}
 assert.ok(herds>=2,`${n}: ${herds} herd rounds`);}});
test('screens: long questions get the smaller heading, tidy intro title, carry is shown',async()=>{const {render}=await import('./public/display.js');const {herdScreen}=await import('./public/herd-ui.js');
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const phone=(g,r,q)=>{const s=g.view(r,q),name=id=>esc(s.players.find(x=>x.id===id)?.name),btn=(t,a)=>`<button data-action="${a}">${t}</button>`,heading=(l,t)=>`<h2>${l}</h2><h1>${t}</h1>`;return herdScreen(s,{esc,name,btn,heading,host:q.id===s.host});};
 const {g,r,p}=party(5);r.phase='reveal';assert.match(phone(g,r,p[1]),/<span class="herd-title">🐑 Herd round<\/span>/);r.phase='herdWrite';
 ask(g,r,{question:'Would you rather live at the beach or in the mountains for a year?',a:'Beach',b:'Mountains'});assert.match(phone(g,r,p[1]),/class="herd-q long"/);assert.match(render(g.publicView(r)).html,/class="prompt herd-long"/);
 const x=party(5);ask(x.g,x.r,{question:'Cats or dogs?',a:'Cats',b:'Dogs'});assert.match(phone(x.g,x.r,x.p[1]),/class="herd-q"/);assert.doesNotMatch(render(x.g.publicView(x.r)).html,/herd-long/);
 vote(g,r,['a','a','b','a']);assert.match(phone(g,r,p[1]),/2 left over → next pot/);assert.match(render(g.publicView(r)).html,/2 left over → next pot/);assert.match(phone(g,r,p[1]),/pays 9/);});
