// Content packs for Oops, All In. Content only: no game logic here.
// Filled by the content pass; the engine reads it through packs.mjs.
// Every array is optional. Empty arrays are ignored.

// Replaces the old Ballpark list when non-empty: [question, answer, source]
// Every answer was checked against the linked source on 2026-09-24.
export const BALLPARK_CORE = [
  ["How many hot dogs did Joey Chestnut eat to win Nathan's Hot Dog Eating Contest in 2021?",76,"https://www.cbssports.com/general/news/nathans-hot-dog-eating-contest-2021-results-joey-chestnut-sets-new-world-record-wins-14th-title"],
  ["How many bones are in an adult human body?",206,"https://www.britannica.com/science/human-skeletal-system"],
  ["How many teeth does an adult dog have?",42,"https://www.britannica.com/animal/dog/Teeth"],
  ["How many keys are on a standard piano?",88,"https://en.wikipedia.org/wiki/Piano"],
  ["How many elements are on the periodic table?",118,"https://en.wikipedia.org/wiki/Periodic_table"],
  ["How tall is Mount Everest in feet, per the 2020 survey?",29032,"https://www.washingtonpost.com/world/asia_pacific/mount-everest-height-nepal-china/2020/12/08/a7b3ad1e-389a-11eb-aad9-8959227280c4_story.html"],
  ["How tall is the Burj Khalifa, the world's tallest building, in meters?",828,"https://www.britannica.com/topic/Burj-Khalifa"],
  ["How many rooms are in Buckingham Palace?",775,"https://www.royal.uk/royal-residences-buckingham-palace"],
  ["How many rooms are in the White House?",132,"https://www.whitehouse.gov/about-the-white-house/the-white-house/"],
  ["How old was the oldest person ever verified when she died in 1997?",122,"https://www.guinnessworldrecords.com/world-records/oldest-person-ever"],
  ["How tall was Robert Wadlow, the tallest man ever, in inches?",107,"https://www.guinnessworldrecords.com/world-records/tallest-man-ever"],
  ["Charles Osborne had the hiccups for the longest time on record. How many years?",68,"https://en.wikipedia.org/wiki/Charles_Osborne_(hiccups)"],
  ["The 2021 world record for holding your breath lasted how many full minutes?",24,"https://www.guinnessworldrecords.com/news/2021/5/freediver-holds-breath-for-almost-25-minutes-breaking-record-660285"],
  ["How many pounds did the record-breaking giant pumpkin weigh in 2023?",2749,"https://www.smithsonianmag.com/smart-news/minnesota-mans-latest-giant-pumpkin-shatters-world-record-with-2749-pound-gourd-180983045/"],
  ["How many lifeboats did the Titanic carry?",20,"https://titanicfacts.net/titanic-lifeboats/"],
  ["How many years did Queen Elizabeth II reign?",70,"https://www.britannica.com/biography/Elizabeth-II"],
  ["How many stairs do runners climb in the Empire State Building race to the 86th floor?",1576,"https://www.esbnyc.com/news/climb-1576-stairs-years-empire-state-building-run-race"],
  ["By March 2025, how many Big Macs had Don Gorske eaten since 1972?",35000,"https://www.guinnessworldrecords.com/news/2025/3/man-who-enjoys-daily-burgers-has-35000th-big-mac-since-1972-where-did-the-time-go"],
  ["A scallop can have up to how many eyes?",200,"https://en.wikipedia.org/wiki/Scallop"],
  ["What is the record for the most T-shirts worn at once, set in 2019?",260,"https://www.guinnessworldrecords.com/world-records/most-t-shirts-worn-at-once"],
  ["In 1964, Randy Gardner set a record for staying awake. How many days?",11,"https://en.wikipedia.org/wiki/Randy_Gardner_sleep_deprivation_experiment"],
  ["How tall is each face on Mount Rushmore, in feet?",60,"https://www.britannica.com/topic/Mount-Rushmore-National-Memorial"],
  ["How many times does the International Space Station circle Earth in one day?",16,"https://www.nasa.gov/international-space-station/space-station-facts-and-figures/"],
  ["How tall is Seattle's Space Needle, in feet?",605,"https://www.spaceneedle.com/facts-1"],
  ["How tall is the Statue of Liberty from heel to top of head, in feet?",111,"https://www.nps.gov/stli/learn/statue-of-liberty-facts.htm"]
];

// Extra items for the default pack, added to the existing prompts.
export const CORE_EXTRA = {
  brain: [
    "A pizza topping people love or hate",
    "The first animal a kid learns to draw",
    "Best superhero with no powers",
    "The most famous ghost",
    "A breakfast food you eat with syrup",
    "The loudest animal on a farm",
    "The most famous wizard",
    "A vegetable kids hate",
    "The most famous cartoon mouse",
    "Something you bring to the beach",
    "A game everyone played at recess",
    "The most famous green cartoon character",
    "Best sauce for fries",
    "A candy you hope to get on Halloween",
    "The most famous cartoon cat",
    "Something that is always cold",
    "The best flavor of chips",
    "A word you scream on a roller coaster",
    "Something you stick in a birthday cake",
    "The most popular name for a dog",
    "The first thing you check in the morning",
    "A sport with a net",
    "The most famous princess",
    "The snack you get at the movies",
    "A song everyone knows the words to",
    "Something with wheels that is not a car",
    "A shape for a cookie cutter",
    "A number people pick when you say pick a number",
    "The best day of the week",
    "A card game everyone knows"
  ],
  quips: [
    "The worst thing to find in your burrito.",
    "What your dog would say if it could talk for five seconds.",
    "The least scary Halloween costume.",
    "A rule your grandma has that makes no sense.",
    "The real reason the chicken crossed the road.",
    "Something you should never yell on a roller coaster.",
    "The worst new flavor of chips.",
    "What the cat is thinking while staring at the wall.",
    "The worst thing to shout at a bowling alley.",
    "A bad thing to say when meeting someone's parents.",
    "A new holiday nobody wants.",
    "Your Wi-Fi's secret nickname for you.",
    "The worst thing to bring on your first camping trip.",
    "What the tooth fairy really does with all those teeth.",
    "The worst thing a lifeguard could shout.",
    "Something you'd hear at a very bad magic show.",
    "The worst snack to open on a crowded bus.",
    "How you can tell your pizza has given up.",
    "A strange thing to find in a car's cup holder.",
    "What the gum under the table has seen.",
    "The saddest ice cream flavor.",
    "The worst ringtone to go off in a quiet movie theater.",
    "A karaoke song choice that clears the room.",
    "What sharks talk about at dinner.",
    "Something a snowman worries about at night.",
    "A thing you should never whisper to a horse.",
    "Something you should never paint on the side of a boat.",
    "An unfortunate thing to get tattooed on your hand.",
    "The weirdest thing to order at a coffee shop.",
    "A dance move that got someone banned from the roller rink.",
    "The one text you never want from your landlord.",
    "A new emoji nobody needed.",
    "What babies are secretly laughing at.",
    "The worst thing to say after a high five.",
    "A dessert that sounds great until the last word.",
    "The worst sound your car can make.",
    "What your shadow does when you're not looking.",
    "The real reason the pool is closed today.",
    "A villain's very small evil plan.",
    "What a squirrel is saving up for."
  ],
  draw: [
    "A cat riding a skateboard",
    "A snowman at the beach",
    "A shark eating spaghetti",
    "A frog wearing a crown",
    "A cow on a trampoline",
    "A pizza wearing sunglasses",
    "A dog driving a bus",
    "A banana lifting weights",
    "A ghost brushing its teeth",
    "A penguin on a surfboard",
    "A robot walking a dog",
    "A burger running away on tiny legs",
    "A snail winning a race",
    "An octopus playing drums",
    "A hot dog in a sleeping bag",
    "A bear eating ice cream",
    "A cactus giving a hug",
    "A duck with a mustache",
    "A giraffe stuck in a tiny car",
    "An alien waiting at a bus stop",
    "A turtle wearing a backpack",
    "A sad cloud raining on a house",
    "A pig in a hot air balloon",
    "A monkey taking a selfie",
    "A taco on vacation",
    "A tree wearing a scarf",
    "A fish riding a bike",
    "A dragon blowing out birthday candles",
    "A spider knitting a sweater",
    "A lion getting a haircut"
  ],
  faker: [
    ["Food","Tacos"],
    ["Food","Sushi"],
    ["Food","Pancakes"],
    ["Food","Ice cream"],
    ["Animals","Penguin"],
    ["Animals","Giraffe"],
    ["Animals","Shark"],
    ["Animals","Kangaroo"],
    ["Places","Beach"],
    ["Places","Hospital"],
    ["Places","Zoo"],
    ["Places","Movie theater"],
    ["Jobs","Teacher"],
    ["Jobs","Pilot"],
    ["Jobs","Chef"],
    ["Jobs","Barber"],
    ["Sports","Basketball"],
    ["Sports","Soccer"],
    ["Sports","Tennis"],
    ["Sports","Golf"],
    ["Holidays","Halloween"],
    ["Holidays","Thanksgiving"],
    ["Around the house","Toothbrush"],
    ["Around the house","Microwave"]
  ],
  rhythm: [
    "Things in a kitchen",
    "Fruits",
    "Vegetables",
    "Colors",
    "Countries",
    "Dog breeds",
    "Car brands",
    "Candy",
    "Breakfast foods",
    "Sea animals",
    "Board games",
    "Things at the beach",
    "Body parts",
    "Clothes",
    "Musical instruments",
    "Jobs",
    "Things in a bathroom",
    "Drinks",
    "Cities",
    "Sports",
    "Things with wheels",
    "Birds",
    "Pasta shapes",
    "Things in a classroom"
  ],
  food: [
    "Build the best meal after a long day at the beach.",
    "Build the best meal after a long hike.",
    "Build a late-night meal after karaoke.",
    "Build the best lazy Sunday breakfast.",
    "Build a meal to cheer up a friend after a breakup.",
    "Build the ultimate movie-night meal.",
    "Build a birthday dinner for someone who can't decide.",
    "Build the best meal for a rainy day inside."
  ]
};

// Themed packs the host can switch on in the lobby.
// faker items are [category, word]; number items are [question, answer, source].
export const PACKS = {
  local: {
    name: "Hawaii and local",
    description: "Hawaii food, places, and everyday island life. Local style, but anyone can play.",
    brain: [
      "The best side on a plate lunch",
      "A shave ice flavor everyone orders",
      "The first thing you eat when you land back home",
      "The island most visitors go to first",
      "The best beach on Oahu",
      "The first Hawaiian word every visitor learns",
      "What you wear to a fancy party in Hawaii",
      "A snack in every grandma's pantry",
      "The best topping for saimin",
      "A local fast-food chain",
      "What you take off before going inside the house",
      "A fish you always see on a poke menu"
    ],
    quips: [
      "The worst thing to find in your plate lunch.",
      "What the chickens on Kauai are planning.",
      "Something you should never say to your aunty at a party.",
      "A new Spam flavor that should not exist.",
      "The real reason there is always traffic on the H-1.",
      "What your slippers say after a long day at the beach.",
      "A bad souvenir to bring back from Hawaii.",
      "A secret rule at every family party in Hawaii.",
      "What the gecko on your wall is thinking.",
      "The first thing your mom says when you visit home.",
      "A strange new shave ice topping.",
      "Something visitors pack for Hawaii and never use."
    ],
    draw: [
      "A gecko surfing a big wave",
      "A Spam musubi on vacation",
      "A chicken at the beach in sunglasses",
      "A sea turtle taking a nap",
      "A shave ice melting in the sun",
      "A mongoose driving a car",
      "A rainbow over a plate lunch",
      "A pineapple wearing slippers",
      "A volcano blowing bubbles",
      "A coconut playing ukulele"
    ],
    faker: [
      ["Food","Poke"],
      ["Food","Spam musubi"],
      ["Food","Malasada"],
      ["Food","Loco moco"],
      ["Desserts","Shave ice"],
      ["Places","Waikiki"],
      ["Places","Diamond Head"],
      ["Activities","Snorkeling"],
      ["Animals","Sea turtle"],
      ["Beach gear","Boogie board"]
    ],
    rhythm: [
      "Plate lunch items",
      "Shave ice flavors",
      "Local snacks",
      "Places on Oahu",
      "Beaches in Hawaii",
      "Hawaiian words",
      "Fruits that grow in Hawaii",
      "Things at a family party",
      "Fish you can eat",
      "Things at a beach park"
    ],
    number: [
      ["How many letters are in the Hawaiian alphabet, counting the okina?",13,"https://en.wikipedia.org/wiki/Hawaiian_alphabet"],
      ["How tall is Mauna Kea above sea level, in feet?",13803,"https://en.wikipedia.org/wiki/Mauna_Kea"],
      ["About how many cans of Spam does Hawaii eat in a year, according to Hormel?",7000000,"https://www.hormelfoods.com/newsroom/news/the-power-of-spam-how-a-canned-meat-went-from-wartime-necessity-to-hawaii-delicacy/"],
      ["How many Olympic medals did Duke Kahanamoku win?",5,"https://en.wikipedia.org/wiki/Duke_Kahanamoku"],
      ["How many steps are on the Haiku Stairs, the Stairway to Heaven?",3922,"https://en.wikipedia.org/wiki/Ha%CA%BBik%C5%AB_Stairs"],
      ["In what year was Iolani Palace finished?",1882,"https://www.iolanipalace.org/history/"],
      ["How tall is Aloha Tower in Honolulu, in feet?",184,"https://en.wikipedia.org/wiki/Aloha_Tower"],
      ["About how many air miles is it from Honolulu to Seattle?",2677,"https://www.airmilescalculator.com/distance/hnl-to-sea/"]
    ],
    food: [
      "Build the best plate lunch after surfing all morning.",
      "Build a meal for the drive around the island.",
      "Build the ultimate beach day cooler.",
      "Build a late-night meal after a family party."
    ]
  },
  sports: {
    name: "Sports",
    description: "Teams, legends, and game day, for the fans and the ones who came for snacks.",
    brain: [
      "The greatest basketball player ever",
      "A sport where you use a racket",
      "The most famous jersey number",
      "The best food at a baseball game",
      "The first sport you ever played",
      "What you yell when your team scores",
      "A sport played on ice",
      "The most famous boxer ever",
      "The best snack for watching football",
      "The most famous soccer player"
    ],
    quips: [
      "The worst walk-up song for a baseball player.",
      "What the ref really says in the huddle.",
      "A new rule that would make golf more fun.",
      "What the mascot does after the game.",
      "The worst thing to shout on a quiet golf course.",
      "A halftime show idea that got everyone fired.",
      "Why the guy on the bench is smiling.",
      "A sport that should be in the Olympics but isn't.",
      "The real reason the goalie missed.",
      "What a coach says when nobody's listening.",
      "The worst touchdown celebration.",
      "A strange thing to find in a gym bag."
    ],
    draw: [
      "A basketball player dunking on a giraffe",
      "A soccer ball running away from a foot",
      "A dog playing tennis",
      "A goalie made of jelly",
      "A snail running a marathon",
      "A scared bowling pin",
      "A hockey player riding a penguin",
      "A baseball flying through a window"
    ],
    faker: [
      ["Sports","Volleyball"],
      ["Sports","Boxing"],
      ["Sports","Baseball"],
      ["Sports","Swimming"],
      ["Gear","Helmet"],
      ["Gear","Whistle"],
      ["Places","Stadium"],
      ["Jobs","Referee"],
      ["Events","Super Bowl"],
      ["Events","Olympics"]
    ],
    rhythm: [
      "NBA teams",
      "NFL teams",
      "MLB teams",
      "Soccer clubs",
      "Olympic sports",
      "Famous athletes",
      "Things at a stadium",
      "Things in a gym",
      "Ball sports",
      "Stadium snacks"
    ],
    number: [
      ["How many points did Wilt Chamberlain score in one game in 1962?",100,"https://en.wikipedia.org/wiki/Wilt_Chamberlain%27s_100-point_game"],
      ["How many home runs did Barry Bonds hit in 2001?",73,"https://sabr.org/gamesproj/game/october-5-2001-barry-bonds-hits-71st-home-run-to-set-new-single-season-record/"],
      ["How many Olympic gold medals has Michael Phelps won?",23,"https://www.olympics.com/en/news/michael-phelps-olympic-medals-record-how-many-gold-swimmer-world-record"],
      ["How many regular-season NHL goals did Wayne Gretzky score in his career?",894,"https://records.nhl.com/records/individual-scoring-records/goals"],
      ["How many hits did Ichiro get in 2004, the MLB single-season record?",262,"https://sabr.org/gamesproj/game/october-1-2004-ichiro-suzuki-breaks-george-sislers-single-season-record-with-258th-hit/"],
      ["How many games did the 2001 Seattle Mariners win?",116,"https://en.wikipedia.org/wiki/2001_Seattle_Mariners_season"],
      ["How many points did Kobe Bryant score against Toronto in January 2006?",81,"https://en.wikipedia.org/wiki/Kobe_Bryant%27s_81-point_game"],
      ["How many hot dogs did Miki Sudo eat to win the 2024 Nathan's women's contest?",51,"https://www.on3.com/pro/news/miki-sudo-wins-womens-nathans-hot-dog-eating-contest-2024-coney-island-results/"]
    ],
    food: [
      "Build the best tailgate meal before kickoff.",
      "Build the ultimate meal in the stadium bleachers."
    ]
  },
  pop: {
    name: "Pop culture",
    description: "Music, movies, shows, games, and the internet.",
    brain: [
      "The best Harry Potter house",
      "The most famous rapper",
      "A Marvel hero everyone knows",
      "The most famous video game character",
      "A Pixar movie that made you cry",
      "The biggest pop star in the world right now",
      "An app everyone deletes and then downloads again",
      "The best Star Wars character",
      "A song everyone knows the dance to",
      "The best Pokemon",
      "The scariest horror movie villain",
      "A TV show everyone has rewatched"
    ],
    quips: [
      "A rejected title for the next Fast and Furious movie.",
      "The worst song to wake up to on a Monday.",
      "A new Pokemon that would be totally useless.",
      "What Mario does on his day off.",
      "A video game side quest nobody wants.",
      "The worst thing to accidentally post on your story.",
      "A movie sequel nobody asked for.",
      "A reality show that gets canceled after one week.",
      "What your algorithm thinks you are into.",
      "A new dance trend that ends badly.",
      "The worst comment to leave on your crush's post.",
      "What Batman does when he's bored."
    ],
    draw: [
      "Mario eating spaghetti",
      "Spider-Man doing laundry",
      "A zombie at a concert",
      "Shrek at the beach",
      "A robot DJ",
      "A dinosaur watching a scary movie",
      "A cat wearing headphones",
      "A vampire taking a selfie",
      "A minion eating a banana",
      "Baby Yoda on a skateboard"
    ],
    faker: [
      ["Movies","Frozen"],
      ["Movies","Titanic"],
      ["Video games","Minecraft"],
      ["Video games","Fortnite"],
      ["Superheroes","Batman"],
      ["Apps","TikTok"],
      ["Apps","Instagram"],
      ["Singers","Taylor Swift"],
      ["Cartoons","SpongeBob"],
      ["TV shows","The Simpsons"]
    ],
    rhythm: [
      "Disney movies",
      "Marvel heroes",
      "Video games",
      "Pokemon",
      "Pop singers",
      "Rappers",
      "Apps on your phone",
      "Harry Potter characters",
      "TV shows",
      "Famous bands"
    ],
    number: [
      ["How many Pokemon were in the original Pokemon Red and Blue?",151,"https://pokemondb.net/pokedex/game/red-blue-yellow"],
      ["How many episodes of Friends were made?",236,"https://www.looper.com/1366545/friends-how-many-episodes-total/"],
      ["How many shows did Taylor Swift play on the Eras Tour?",149,"https://time.com/7199590/taylor-swift-eras-tour-final-numbers/"],
      ["How many Oscars did Titanic win in 1998?",11,"https://parade.com/entertainment/titanic-1997-classic-widely-considered-greatest-film-ever-made-won-11-academy-awards"],
      ["How many players started the games in season 1 of Squid Game?",456,"https://en.wikipedia.org/wiki/Squid_Game_season_1"],
      ["How many songs did the Beatles take to No. 1 on the Billboard Hot 100?",20,"https://www.billboard.com/lists/artists-most-number-one-hits-all-time-hot-100/"]
    ],
    food: []
  },
  family: {
    name: "Family friendly",
    description: "Kid-safe and grandma-approved. Silly, never sketchy.",
    brain: [
      "The best ice cream flavor",
      "The best animal at the zoo",
      "A cartoon dog everyone knows",
      "The best thing to put on toast",
      "A game you play at a birthday party",
      "The most popular crayon color",
      "A food that's fun to eat with your hands",
      "A fairy tale with a wolf in it",
      "The best dinosaur",
      "The best season of the year",
      "Something you find in a backpack",
      "A bug everyone likes"
    ],
    quips: [
      "What the goldfish thinks about all day.",
      "The worst thing to pack in a school lunch.",
      "A new crayon color nobody would use.",
      "What dinosaurs would complain about today.",
      "The silliest rule in a treehouse club.",
      "What your teddy bear does while you're at school.",
      "Why the dog is wearing a tiny hat.",
      "A bedtime excuse that almost worked.",
      "What a snowman eats for breakfast.",
      "A superhero who only helps with chores.",
      "The strangest thing to find under the couch.",
      "A new bubblegum flavor nobody should chew."
    ],
    draw: [
      "A bunny on a pogo stick",
      "A dinosaur eating a cupcake",
      "A whale in a tiny boat",
      "An owl reading a book",
      "A kitten in a teacup",
      "A caterpillar wearing shoes",
      "A sun wearing sunglasses",
      "A castle made of pancakes",
      "A dog flying a kite",
      "An elephant on roller skates"
    ],
    faker: [
      ["Animals","Elephant"],
      ["Animals","Monkey"],
      ["Food","Spaghetti"],
      ["Food","Cupcake"],
      ["Places","Playground"],
      ["Places","Farm"],
      ["Toys","Teddy bear"],
      ["Toys","Yo-yo"],
      ["Jobs","Doctor"],
      ["Weather","Rainbow"]
    ],
    rhythm: [
      "Cartoon characters",
      "Zoo animals",
      "Farm animals",
      "Things in a backpack",
      "Toys",
      "Fairy tale characters",
      "Things that are round",
      "Dinosaurs",
      "Things in the sky",
      "Desserts"
    ],
    number: [],
    food: [
      "Build the best lunch after a long day at the zoo.",
      "Build the ultimate kids' birthday party lunch.",
      "Build a treat for a great report card.",
      "Build a picnic for a family day at the park."
    ]
  },
  spicy: {
    name: "Spicy (adults)",
    description: "Adults only. Flirty, awkward, dating and nightlife. Embarrassing, never explicit.",
    brain: [
      "The worst place for a first date",
      "The most popular dating app",
      "First thing you notice on a date",
      "The most awkward place to run into your ex",
      "A song that is always playing at the club at 1 AM",
      "A red flag on a dating profile",
      "The messiest food to eat on a first date",
      "What you check in the mirror before a date",
      "The most romantic movie ever",
      "The best place to meet someone in real life"
    ],
    quips: [
      "The worst thing to say right after a first kiss.",
      "A dating profile bio that screams run.",
      "The real reason they didn't text back.",
      "An awful thing to find in your date's car.",
      "The worst song to slow dance to.",
      "The worst question to ask on a first date.",
      "A pickup line that got someone kicked out of the bar.",
      "The most awkward thing your mom could say to your date.",
      "The worst place to get dumped.",
      "A text you should never send after midnight.",
      "The worst thing to accidentally like on your ex's page.",
      "A terrible reason to swipe right.",
      "The worst excuse to leave a date early.",
      "What your date whispers that ruins the moment.",
      "The worst couples costume.",
      "A dealbreaker that is actually kind of fair.",
      "The worst thing to order to impress a date.",
      "Something that only seems like a good idea at 2 AM.",
      "The worst nickname a partner could give you.",
      "A believable excuse for wearing yesterday's outfit."
    ],
    draw: [
      "Two snails on a date",
      "A heart with a cracked phone",
      "Cupid missing his shot",
      "A frog blowing a kiss",
      "A dance floor with only one person",
      "A love letter on fire",
      "A candlelit dinner for two cats",
      "A bouncer turning away a penguin"
    ],
    faker: [
      ["Date spots","Mini golf"],
      ["Date spots","Picnic"],
      ["Date spots","Rooftop bar"],
      ["Apps","Tinder"],
      ["Nightlife","Dance floor"],
      ["Nightlife","Bouncer"],
      ["Romance","Valentine's Day"],
      ["Romance","First kiss"]
    ],
    rhythm: [
      "Cocktails",
      "Love songs",
      "Romantic movies",
      "Pet names for a partner",
      "Valentine's gifts",
      "Things at a bar",
      "First-date spots",
      "Party songs"
    ],
    number: [],
    food: []
  }
};
