import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Game} from './server.mjs';
import {distribute} from './pot.mjs';
const setup=(n=4,game='number',round=3)=>{const g=new Game(),{code}=g.create('Host'),r=g.rooms.get(code);for(let i=1;i<n;i++)g.join(code,'Player '+i);r.banEnabled=false;r.enabledGames=[game];r.round=round-1;g.fresh(r);return {g,r,p:r.players};};
const move=(g,r,move,total)=>g.action(r,r.players.find(p=>p.id===r.pot.turn),{type:'potBet',move,total,confirmed:move==='allin'||move==='match',round:r.round,revision:r.pot.revision});
const matchAll=(g,r)=>{let n=0;while(r.phase==='wager'){assert.ok(n++<20);move(g,r,'match');}};
const wealth=r=>r.players.reduce((s,p)=>s+p.chips,0)+(r.potSettled?0:Object.values(r.stakes||{}).reduce((a,b)=>a+b,0));
test('20/100/100 gives short winner 60 and next ranked player side pot 160',()=>{assert.deepEqual(distribute({a:20,b:100,c:100},{a:3,b:2,c:1},['a','b','c']).payouts,{a:60,b:160,c:0});});
test('unmatched chips return; folded players lose matched contribution; odd chips rotate',()=>{assert.deepEqual(distribute({a:100,b:20},{a:1},['a','b']).payouts,{a:120,b:0});assert.deepEqual(distribute({a:5,b:5,c:5},{a:1,b:1},['b','a','c']).payouts,{a:7,b:8,c:0});});
test('random settlement conserves integer chips across ranks, ties, folds and refunds',()=>{let seed=87;const rand=n=>(seed=(seed*1664525+1013904223)>>>0)%n;for(let i=0;i<1500;i++){const stakes={},scores={},order=[];for(let j=0;j<2+rand(7);j++){const id='p'+j;order.push(id);stakes[id]=rand(500);if(rand(4))scores[id]=rand(5);}const {payouts}=distribute(stakes,scores,order,{refund:rand(20)===0});assert.equal(Object.values(payouts).reduce((a,b)=>a+b,0),Object.values(stakes).reduce((a,b)=>a+b,0));assert.ok(Object.values(payouts).every(n=>Number.isSafeInteger(n)&&n>=0));}});
test('game first, no secret or prompt leaks during betting; stale and wrong turn rejected',()=>{const {g,r,p}=setup();assert.equal(r.phase,'spin');assert.equal(wealth(r),400);assert.equal(g.publicView(r).prompt,'');g.advance(r);assert.equal(r.phase,'wager');const current=p.find(p=>p.id===r.pot.turn),revision=r.pot.revision;assert.throws(()=>g.action(r,p.find(p=>p!==current),{type:'potBet',move:'raise',total:20,round:r.round,revision}));move(g,r,'raise',20);assert.throws(()=>g.action(r,current,{type:'potBet',move:'raise',total:50,round:r.round,revision}));assert.equal(g.publicView(r).prompt,'');assert.equal(wealth(r),400);});
test('first two rounds limit raises to 20; all in unlocks round three',()=>{for(const round of [1,2]){const {g,r}=setup(2,'number',round);g.advance(r);assert.throws(()=>move(g,r,'allin'),/FUN_POLICE/);assert.throws(()=>move(g,r,'raise',50),/FUN_POLICE/);move(g,r,'raise',20);matchAll(g,r);assert.equal(r.phase,'reveal');assert.equal(wealth(r),200);}const {g,r}=setup(2);g.advance(r);move(g,r,'allin');matchAll(g,r);assert.equal(r.phase,'reveal');assert.equal(wealth(r),200);});
test('creative judges assigned before chips; folded contestant never judges',()=>{const {g,r,p}=setup(6,'quips');g.advance(r);const folded=r.pot.turn;move(g,r,'fold');assert.equal(r.phase,'result');assert.ok(!g.voters(r).some(p=>p.id===folded));assert.equal(wealth(r),600);});
test('raise pass closes; final response cannot reopen it and timeout never auto-calls',()=>{const {g,r}=setup(2);g.advance(r);move(g,r,'match');move(g,r,'raise',50);assert.equal(r.pot.stage,'response');assert.throws(()=>move(g,r,'raise',60),/Raising is closed/);g.advance(r);assert.equal(r.phase,'result');assert.equal(wealth(r),200);});
test('missing creative submission forfeits instead of causing refund',()=>{const {g,r,p}=setup(4,'quips');g.advance(r);matchAll(g,r);g.advance(r);const winner=r.active[0];g.action(r,p.find(p=>p.id===winner),{type:'submit',value:'A funny answer'});g.advance(r);for(const judge of g.voters(r))if(r.phase==='vote')g.action(r,judge,{type:'vote',player:winner});assert.equal(r.result.tie,false);assert.equal(r.result.changes[winner],5);assert.equal(wealth(r),400);});
test('fixed matching round refunds everyone matching; faker has no role leak before reveal',()=>{let {g,r,p}=setup(4,'brain',1);g.advance(r);assert.equal(r.phase,'reveal');g.advance(r);for(const q of p)g.action(r,q,{type:'submit',value:'Banana'});assert.equal(r.result.tie,true);assert.equal(wealth(r),400);({g,r,p}=setup(4,'imposter',1));assert.equal(g.view(r,p[0]).secret,null);assert.equal(g.publicView(r).category,null);g.advance(r);assert.equal(r.pot.fixed,true);assert.equal(g.publicView(r).secret,null);});
test('smaller all in, custom all in confirmation and repeated settlement do not mint chips',()=>{const {g,r,p}=setup(3,'number',4);p[0].chips=20;g.advance(r);let guard=0;while(r.phase==='wager'){assert.ok(guard++<10);move(g,r,'allin');}g.advance(r);for(const id of [...r.active])g.action(r,p.find(p=>p.id===id),{type:'submit',value:p[0].id===id?r.answer:r.answer+10});const before=p.map(p=>p.chips);g.settle(r);assert.deepEqual(p.map(p=>p.chips),before);assert.equal(wealth(r),220);});
test('leave keeps committed stake in the pot; no refund sabotage',()=>{const {g,r,p}=setup(2);g.advance(r);matchAll(g,r);g.advance(r);const loser=p[0];g.action(r,loser,{type:'leave',round:r.round});assert.equal(r.phase,'result');assert.equal(loser.chips,95);assert.equal(p[1].chips,105);assert.equal(wealth(r),200);});
test('entire sessions at 2, 3, 4, 8 seats conserve chips and terminate',()=>{for(const n of [2,3,4,8]){const {g,r,p}=setup(n,'number',1);r.totalRounds=9;let steps=0;while(r.phase!=='finished'){assert.ok(steps++<250);if(r.phase==='wager')move(g,r,'match');else if(r.phase==='play'){for(const id of [...r.active])if(r.phase==='play')g.action(r,p.find(p=>p.id===id),{type:'submit',value:r.answer+Math.floor(p.findIndex(p=>p.id===id)/2)});}else if(r.phase==='result')g.action(r,p[0],{type:'next'});else if(r.phase==='comeback')g.advance(r);else g.advance(r);assert.equal(wealth(r),n*100);}assert.equal(r.round,9);}});

test('stateful challenge departure cannot recover an entry; rematch clears pot',()=>{const {g,r,p}=setup(4,'rhythm',1);g.advance(r);matchAll(g,r);g.advance(r);const leaving=p.find(p=>r.active.includes(p.id));g.action(r,leaving,{type:'leave',round:r.round});assert.equal(r.phase,'result');assert.equal(leaving.chips,95);assert.equal(wealth(r),400);r.phase='finished';g.action(r,p.find(p=>p.id===r.host),{type:'rematch'});assert.equal(g.view(r,p[1]).pot,null);});
test('matching a whole stack requires explicit confirmation after round two',()=>{const {g,r,p}=setup(2);g.advance(r);move(g,r,'allin');const q=p.find(p=>p.id===r.pot.turn);assert.throws(()=>g.action(r,q,{type:'potBet',move:'match',round:r.round,revision:r.pot.revision}),/Confirm All In/);move(g,r,'match');assert.equal(r.phase,'reveal');});
test('all nine games complete a paid round with conserved chips',()=>{
 for(const game of ['brain','imposter','number','draft','auction','draw','quips','shadow','rhythm']){
  const {g,r,p}=setup(4,game,['brain','imposter','rhythm'].includes(game)?1:3);let guard=0;
  while(r.phase!=='result'){
   assert.ok(guard++<250,game+' stalled at '+r.phase);
   if(r.phase==='wager')move(g,r,'match');
   else if(r.phase==='play'){for(const id of [...r.active])if(r.phase==='play')g.action(r,p.find(q=>q.id===id),{type:'submit',value:game==='number'?r.answer:game==='draw'?'data:image/png;base64,abc':'Pizza'});}
   else if(r.phase==='clue')g.action(r,p.find(q=>q.id===r.clueOrder[r.clueIndex]),{type:'clue',value:'hmm',clueIndex:r.clueIndex});
   else if(r.phase==='auction'){const a=r.auction;if(a.pending.length)g.action(r,p.find(q=>q.id===a.pending[0].player),{type:'auctionItem',value:'My food',revision:a.revision});else g.action(r,p.find(q=>q.id===a.turn),{type:'auctionPass',revision:a.revision});}
   else if(r.phase==='pitch'){r.deadline=1;g.tick();}
   else if(r.phase==='physicalSetup'){if(game==='rhythm')g.action(r,p[0],{type:'physicalCategory',value:'States',revision:r.physical.revision});g.action(r,p[0],{type:'physicalStart',revision:r.physical.revision});}
   else if(r.phase==='physical')g.action(r,p[0],{type:'physicalFinish',revision:r.physical.revision});
   else if(r.phase==='vote'){for(const q of g.voters(r))if(r.phase==='vote')g.action(r,q,{type:'vote',player:r.active.find(id=>id!==q.id)});}
   else g.advance(r);
  }
  assert.equal(wealth(r),400,game);assert.ok(r.result.pots.length,game);
 }
});
