// Original ratings for the Scout grade; our own judgments, not league
// or video-game data.
export const RATINGS = {
  hoops: {
    "Stephen Curry": [98, 55, "Redefined shooting range forever"],
    "Magic Johnson": [95, 70, "Showtime era, elite all-around"],
    "Gary Payton": [75, 96, "The Glove, lockdown defender"],
    "Sue Bird": [80, 68, "WNBA floor general, four titles"],
    "Chris Paul": [86, 80, "Elite point guard, career assists"],
    "Steve Nash": [90, 55, "Back-to-back MVP, offensive maestro"],
    "Isiah Thomas": [88, 72, "Bad Boys Pistons leader"],
    "John Stockton": [82, 75, "All-time assists and steals king"],
    "Allen Iverson": [92, 60, "Fearless scorer, undersized dominance"],
    "Russell Westbrook": [88, 65, "Triple-double machine, relentless energy"],
    "Luka Doncic": [97, 58, "Scoring champ and playmaker"],
    "Jason Kidd": [78, 82, "Pass-first floor general, gritty defense"],
    "Caitlin Clark": [90, 55, "Logo threes, instant WNBA impact"],
    "Damian Lillard": [90, 58, "Deep-range killer, clutch shooter"],
    "Shai Gilgeous-Alexander": [96, 76, "MVP scorer, elite efficiency"],
    "Courtney Vandersloot": [78, 70, "Elite assist artist, WNBA steady"],
    "Jalen Brunson": [88, 56, "Champion Knicks closer"],
    "Tyrese Haliburton": [83, 60, "Pass-first playmaker, sneaky scorer"],
    "Paige Bueckers": [82, 58, "Rising college star, smooth scorer"],
    "Yuki Kawamura": [55, 60, "Tiny sparkplug, feisty on-ball defense"],
    "Jeremy Lin": [70, 52, "Linsanity spark, brief but electric"],
    "Nate Robinson": [72, 45, "Three-time dunk champ, undersized guard"],
    "Matthew Dellavedova": [50, 68, "Gritty role player, hard-nosed defense"],
    "Muggsy Bogues": [58, 70, "Shortest NBA player, pesky defender"],
    "Spud Webb": [60, 50, "Dunk contest legend, tiny guard"],
    "Yuta Tabuse": [45, 45, "First Japanese-born NBA player"],
    "Anthony Carter": [48, 62, "Steady backup, defensive-minded guard"],
    "T.J. McConnell": [55, 72, "Pesky on-ball defender, hustle guard"],
    "Patrick Beverley": [52, 80, "Irritant defender, undersized pest"],
    "Mario Chalmers": [58, 55, "Clutch Heat role player"],
    "Derek Fisher": [55, 58, "Clutch shot-maker, five rings"],
    "Scoot Henderson": [70, 55, "Explosive young athlete, still developing"],
    "Bronny James": [45, 50, "Rookie role player, still developing"],
    "Natasha Cloud": [58, 68, "Vocal leader, tough WNBA defender"],
    "Reed Sheppard": [62, 55, "Sharpshooting young guard"],

    "Michael Jordan": [99, 90, "Greatest ever, dominant both ends"],
    "Kobe Bryant": [96, 88, "Mamba mentality, five championships"],
    "Dwyane Wade": [90, 78, "Explosive finisher, Finals MVP"],
    "Ray Allen": [85, 55, "Purest shooter, clutch Game 6"],
    "Diana Taurasi": [93, 60, "WNBA all-time scoring leader"],
    "Klay Thompson": [85, 58, "Splash Brother, historic shooting nights"],
    "James Harden": [93, 50, "Stepback specialist, scoring titles"],
    "Reggie Miller": [85, 55, "Legendary clutch shooter, Knicks rival"],
    "Jewell Loyd": [82, 55, "Elite WNBA scorer, gold medalist"],
    "Anthony Edwards": [91, 70, "Explosive star scorer"],
    "Devin Booker": [88, 55, "Silky scorer, 70-point game"],
    "Arike Ogunbowale": [80, 52, "Clutch college hero, WNBA scorer"],
    "Kelsey Plum": [78, 50, "Sharpshooting WNBA All-Star"],
    "Jerry West": [90, 75, "The Logo, clutch legend"],
    "Manu Ginobili": [80, 70, "Euro-step pioneer, sixth man great"],
    "Vince Carter": [86, 50, "High-flying dunker, longevity king"],
    "Donovan Mitchell": [88, 56, "Explosive scoring guard"],
    "Jaylen Brown": [88, 74, "Finals MVP, two-way wing"],
    "Sabrina Ionescu": [85, 52, "Three-point contest record holder"],
    "Jalen Williams": [82, 74, "All-NBA two-way wing"],
    "J.R. Smith": [62, 45, "Streaky shooter, iconic mistake"],
    "Alex Caruso": [50, 85, "Elite perimeter defender, hustle guard"],
    "Jordan Clarkson": [68, 45, "Sixth Man award, instant offense"],
    "Nick Young": [65, 40, "Swaggy P, gunner reputation"],
    "Lou Williams": [75, 40, "Three-time Sixth Man scorer"],
    "Jamal Crawford": [72, 42, "Crossover king, three-time Sixth Man"],
    "Kyle Korver": [70, 45, "Elite volume three-point shooter"],
    "Steve Kerr": [65, 45, "Championship shooter turned championship coach"],
    "Jason Terry": [68, 48, "Jet, sixth man scorer"],
    "Austin Reaves": [80, 56, "Undrafted to 23 a night"],
    "Svi Mykhailiuk": [50, 45, "Journeyman shooting specialist"],
    "Dalton Knecht": [55, 42, "Bench shooter"],
    "Brandin Podziemski": [58, 55, "Feisty rookie, heady playmaker"],
    "Sophie Cunningham": [50, 55, "Physical WNBA role player"],
    "Dyson Daniels": [58, 86, "Steals leader, defensive pest"],
    "Jarrett Culver": [45, 50, "Former lottery pick, limited role"],

    "LeBron James": [98, 80, "Generational all-around dominance, longevity"],
    "Larry Bird": [95, 72, "Trash-talking legend, clutch shooter"],
    "Kevin Durant": [97, 60, "Unstoppable scoring at any size"],
    "Kawhi Leonard": [88, 92, "Two-way Finals MVP, lockdown wing"],
    "Scottie Pippen": [80, 90, "Jordan's wingman, elite defender"],
    "Maya Moore": [90, 65, "Four WNBA titles, complete scorer"],
    "Julius Erving": [88, 60, "Dr. J, aerial artistry pioneer"],
    "Jayson Tatum": [91, 74, "Champion two-way forward"],
    "Paul George": [85, 75, "Three-and-D star, All-Star scorer"],
    "Carmelo Anthony": [90, 45, "Elite scorer, volume shot creator"],
    "Elgin Baylor": [88, 55, "Pre-instant-replay high flyer"],
    "Tamika Catchings": [82, 88, "WNBA defensive stalwart and scorer"],
    "Detlef Schrempf": [75, 55, "Two-time Sixth Man, German pioneer"],
    "Jimmy Butler": [82, 80, "Playoff Jimmy, tough two-way wing"],
    "Candace Parker": [85, 72, "Two-way WNBA MVP, champion"],
    "Rashard Lewis": [72, 40, "Stretch four pioneer, All-Star"],
    "Cooper Flagg": [80, 72, "Rookie of the Year all-rounder"],
    "Rui Hachimura": [65, 45, "Efficient scoring forward, Japan pioneer"],
    "Franz Wagner": [75, 60, "Smooth two-way scoring forward"],
    "Mikal Bridges": [68, 78, "Elite wing defender, iron man"],
    "Brian Scalabrine": [40, 40, "White Mamba, beloved bench legend"],
    "Yuta Watanabe": [45, 55, "Hard-nosed Japanese role player"],
    "Jaime Jaquez Jr.": [60, 55, "Crafty rookie, footwork savant"],
    "Bruce Bowen": [40, 88, "Elite point-of-attack defender, corner three"],
    "Shane Battier": [50, 82, "No-stats all-star, smart defender"],
    "Metta World Peace": [68, 85, "Defensive Player of Year, champion"],
    "Andrei Kirilenko": [65, 80, "AK-47, versatile shot blocker"],
    "Matt Barnes": [55, 68, "Physical role player, tough defender"],
    "Stephen Jackson": [65, 62, "Champion, feisty scoring wing"],
    "Hedo Turkoglu": [68, 45, "Most Improved Player, crafty scorer"],
    "P.J. Tucker": [40, 75, "Undersized enforcer, corner specialist"],
    "Rick Fox": [55, 55, "Three-time champion role player"],
    "Tony Allen": [45, 88, "Grindfather, elite perimeter stopper"],
    "Josh Hart": [58, 68, "Rebounding guard-forward, hustle glue guy"],
    "Kyle Anderson": [55, 65, "Slow Mo, crafty playmaking forward"],
    "Joe Ingles": [58, 55, "Sharpshooting Aussie, sneaky passer"],

    "Tim Duncan": [88, 95, "Fundamental big man, five titles"],
    "Shawn Kemp": [85, 65, "Reign Man, high-flying power dunker"],
    "Breanna Stewart": [92, 70, "Dominant WNBA MVP scorer"],
    "Dirk Nowitzki": [93, 55, "Unstoppable fadeaway, champion"],
    "Giannis Antetokounmpo": [95, 88, "Greek Freak, two-way MVP force"],
    "Karl Malone": [90, 70, "The Mailman, all-time scorer"],
    "Kevin Garnett": [85, 92, "Defensive Player of Year, intensity"],
    "Charles Barkley": [88, 65, "Undersized rebounding force, Round Mound"],
    "Dennis Rodman": [45, 95, "Rebounding savant, elite defender"],
    "A'ja Wilson": [92, 85, "Dominant two-way WNBA MVP"],
    "Blake Griffin": [82, 55, "High-flying dunker, All-Star forward"],
    "Pau Gasol": [80, 72, "Skilled European big, champion"],
    "Napheesa Collier": [85, 70, "Two-way WNBA scoring force"],
    "Chris Webber": [82, 60, "Fab Five star, skilled scorer"],
    "Anthony Davis": [88, 90, "Elite rim protector, two-way anchor"],
    "Draymond Green": [55, 92, "Defensive Player of Year, glue guy"],
    "Paolo Banchero": [82, 55, "Franchise scorer, physical forward"],
    "Zion Williamson": [88, 55, "Explosive interior force, injury-prone"],
    "Angel Reese": [70, 72, "Rebounding machine, WNBA rookie force"],
    "Evan Mobley": [76, 90, "DPOY rim protector"],
    "Robert Horry": [55, 60, "Big Shot Rob, seven rings"],
    "Kelly Olynyk": [55, 45, "Stretch big, floppy-haired role player"],
    "Yi Jianlian": [50, 45, "Chinese import, limited NBA impact"],
    "Udonis Haslem": [40, 55, "Heat lifer, locker-room glue guy"],
    "Brian Cardinal": [40, 45, "Custodian, hustle bench big"],
    "Luis Scola": [68, 50, "Skilled Argentine scoring forward"],
    "Mehmet Okur": [65, 45, "Stretch big, Turkish sharpshooter"],
    "Channing Frye": [58, 40, "Stretch-five three-point specialist"],
    "Charles Oakley": [50, 80, "Enforcer, physical rebounding presence"],
    "Kurt Rambis": [40, 55, "Goggled hustle player, Showtime role"],
    "Chuck Hayes": [40, 70, "Undersized defensive rebounding specialist"],
    "Drew Gooden": [58, 40, "Journeyman scoring big man"],
    "Taj Gibson": [45, 68, "Reliable defensive rotation big"],
    "Nick Collison": [40, 60, "Blue-collar screen-setting role player"],
    "Mark Madsen": [40, 40, "Energy bench big, cult favorite"],
    "Glen Davis": [58, 50, "Big Baby, physical bench scorer"],

    "Shaquille O'Neal": [95, 80, "Unstoppable force, four championships"],
    "Kareem Abdul-Jabbar": [92, 85, "Skyhook legend, all-time scoring leader"],
    "Hakeem Olajuwon": [88, 96, "Dream Shake, elite shot blocker"],
    "Bill Russell": [55, 98, "Eleven rings, defensive anchor legend"],
    "Wilt Chamberlain": [96, 80, "100-point game, statistical monster"],
    "Nikola Jokic": [97, 66, "MVP passing big, triple-doubles"],
    "Victor Wembanyama": [88, 97, "DPOY unicorn, MVP finalist"],
    "Lisa Leslie": [88, 75, "WNBA pioneer, dominant scorer"],
    "Brittney Griner": [82, 88, "Elite shot-blocking WNBA center"],
    "Yao Ming": [80, 68, "Chinese pioneer, skilled seven-footer"],
    "Patrick Ewing": [85, 80, "Knicks legend, rim-protecting scorer"],
    "David Robinson": [85, 88, "Admiral, two-way dominant center"],
    "Joel Embiid": [92, 78, "MVP scorer, dominant when healthy"],
    "Lauren Jackson": [85, 72, "Australian great, three-time MVP"],
    "Sylvia Fowles": [75, 85, "Rebounding and defense anchor"],
    "Jack Sikma": [70, 60, "Sonics legend, skilled shooting center"],
    "Alperen Sengun": [82, 62, "All-Star passing big"],
    "Chet Holmgren": [74, 90, "Shot-blocking stretch big"],
    "Bam Adebayo": [72, 85, "Versatile defensive anchor, playmaking big"],
    "Kamilla Cardoso": [55, 60, "Physical rookie WNBA presence"],
    "Boban Marjanovic": [50, 45, "Beloved giant, limited-minutes bruiser"],
    "Tacko Fall": [40, 50, "Tallest NBA player, cult favorite"],
    "Bol Bol": [45, 40, "Skilled but inconsistent stretch big"],
    "Luka Garza": [55, 40, "College legend, limited NBA role"],
    "Walker Kessler": [45, 78, "Elite young shot blocker"],
    "Zach Edey": [62, 70, "Huge rebounding center"],
    "Mark Williams": [55, 68, "Athletic rim-running shot blocker"],
    "Manute Bol": [40, 60, "Tallest player ever, shot blocker"],
    "Gheorghe Muresan": [40, 50, "Towering seven-foot-seven center"],
    "Shawn Bradley": [40, 45, "Prolific but mocked shot blocker"],
    "Steven Adams": [45, 75, "Bruising screen-setter, offensive rebounder"],
    "Zaza Pachulia": [40, 45, "Physical veteran screen-setter"],
    "Joakim Noah": [40, 82, "Defensive Player of Year energy big"],
    "Wang Zhizhi": [45, 40, "First Chinese-born NBA player"],
    "Mark Eaton": [40, 85, "Shot-blocking record holder, defensive specialist"],
    "Anderson Varejao": [45, 55, "Hustle rebounder, flopping reputation"]
  },
  nfl: {
    "Walter Jones": [55, 96, "Shutdown left tackle"],
    "Jason Kelce": [52, 92, "Smart, nimble center"],
    "Patrick Mahomes": [97, 85, "Generational arm talent, three rings"],
    "Josh Allen": [93, 80, "Dual-threat cannon arm, MVP"],
    "Lamar Jackson": [92, 75, "Electric runner, two-time MVP"],
    "Joe Burrow": [90, 70, "Ice-cold pocket passer, Bengal revival"],
    "Jalen Hurts": [85, 82, "Tush Push, Super Bowl champion"],
    "Sam Darnold": [65, 55, "Journeyman resurgence, streaky passer"],
    "Jayden Daniels": [82, 60, "Explosive rookie of the year"],
    "Drake Maye": [70, 55, "Promising young rebuilding quarterback"],
    "C.J. Stroud": [80, 58, "Poised rookie standout, strong arm"],
    "Tom Brady": [95, 95, "Seven rings, ultimate clutch legend"],
    "Peyton Manning": [96, 80, "Record-setting passer, five MVPs"],
    "Joe Montana": [92, 90, "Mr. Cool, four Super Bowl rings"],
    "Dan Marino": [93, 60, "Record-setting arm, no ring"],
    "John Elway": [88, 85, "The Drive, comeback specialist"],
    "Aaron Rodgers": [93, 55, "Elite improviser, MVP accuracy"],
    "Russell Wilson": [82, 70, "Seahawks Super Bowl winner, mobile"],
    "Matt Hasselbeck": [72, 68, "Seahawks franchise leader, playoff run"],
    "Warren Moon": [80, 72, "Hall of Fame gunslinger, Oilers"],
    "Marcus Mariota": [60, 55, "Heisman winner, unfulfilled ceiling"],
    "Tua Tagovailoa": [75, 45, "Accurate arm, injury-plagued career"],
    "Tim Tebow": [50, 60, "Tebowing phenomenon, unorthodox winner"],
    "Ryan Fitzpatrick": [60, 55, "FitzMagic journeyman, seven teams"],
    "Brian Hoyer": [45, 55, "Reliable career backup quarterback"],
    "Chase Daniel": [40, 50, "Long-tenured clipboard-holding backup"],
    "Kyle Orton": [50, 50, "Steady game-manager journeyman starter"],
    "Jon Kitna": [55, 58, "Durable game-manager, iron man"],
    "Rex Grossman": [45, 40, "Erratic Bears Super Bowl starter"],
    "Jake Delhomme": [58, 55, "Panthers Super Bowl run leader"],
    "Mark Sanchez": [50, 45, "Butt-fumble, Jets playoff starter"],
    "Case Keenum": [55, 55, "Minneapolis Miracle journeyman starter"],
    "Matt Flynn": [40, 40, "One big game, mostly backup"],
    "Charlie Whitehurst": [40, 40, "Clipboard Jesus, career backup"],
    "Nick Foles": [65, 72, "Philly Special, Super Bowl MVP"],
    "Gardner Minshew": [55, 60, "Mustache folk hero backup"],
    "Taysom Hill": [45, 55, "Swiss Army knife utility player"],
    "Doug Flutie": [65, 65, "Hail Mary legend, undersized magic"],
    "Josh McCown": [45, 55, "Well-traveled reliable veteran backup"],
    "Tommy DeVito": [40, 45, "Jersey folk hero backup run"],
    "Timmy Chang": [40, 40, "Hawaii gunslinger, NCAA record passer"],
    "Colt McCoy": [45, 58, "Steady long-career backup quarterback"],

    "Marshawn Lynch": [90, 80, "Beast Mode, bone-crushing runs"],
    "Shaun Alexander": [82, 55, "Single-season TD record holder"],
    "Kenneth Walker III": [75, 60, "Explosive Seahawks feature back"],
    "Christian McCaffrey": [93, 60, "All-purpose dual-threat superstar"],
    "Saquon Barkley": [90, 65, "Explosive record-breaking rushing season"],
    "Derrick Henry": [92, 80, "King Henry, bruising workhorse"],
    "Bijan Robinson": [82, 58, "Smooth explosive young workhorse"],
    "Jahmyr Gibbs": [80, 55, "Big-play home run hitter"],
    "Jonathan Taylor": [85, 60, "League-leading rushing champion"],
    "Ashton Jeanty": [72, 50, "Heisman-level college workload rookie"],
    "De'Von Achane": [78, 45, "Blazing speed home-run threat"],
    "Josh Jacobs": [78, 62, "Physical downhill workhorse back"],
    "Barry Sanders": [95, 55, "Ankle-breaking, gone-too-soon legend"],
    "Walter Payton": [90, 88, "Sweetness, iron-man workhorse"],
    "Emmitt Smith": [88, 85, "All-time rushing leader, durable"],
    "Jim Brown": [93, 85, "Dominant power, never missed games"],
    "LaDainian Tomlinson": [90, 68, "Record touchdown season, dual threat"],
    "Adrian Peterson": [90, 60, "All Day, explosive power runner"],
    "Bo Jackson": [88, 45, "Two-sport legend, cut short"],
    "Eric Dickerson": [88, 58, "Single-season rushing record holder"],
    "Danny Woodhead": [55, 50, "Undersized change-of-pace scatback"],
    "Mike Alstott": [60, 72, "A-Train, bruising fullback scorer"],
    "Peyton Hillis": [55, 55, "One breakout Madden cover year"],
    "BenJarvus Green-Ellis": [55, 68, "Law Firm, never fumbled"],
    "Jerome Bettis": [78, 80, "The Bus, powerful workhorse"],
    "Christine Michael": [40, 40, "Talented but inconsistent journeyman"],
    "Mack Strong": [40, 60, "Seahawks lead-blocking fullback stalwart"],
    "Leon Washington": [50, 45, "Explosive kick returner, change of pace"],
    "Kyle Juszczyk": [40, 65, "Elite modern fullback, versatile blocker"],
    "Patrick Ricard": [40, 68, "Pro Bowl fullback and lineman"],
    "Darren Sproles": [65, 50, "Electric all-purpose scatback returner"],
    "Dexter McCluster": [45, 42, "Versatile slot back and returner"],
    "Lorenzo Neal": [40, 70, "Premier lead-blocking fullback"],
    "Chris Carson": [65, 58, "Physical Seahawks feature back"],
    "Rashaad Penny": [50, 45, "Injury-limited flashes of explosion"],
    "Robert Turbin": [40, 45, "Rotational power back depth"],
    "Jerick McKinnon": [45, 42, "Versatile receiving change-of-pace back"],
    "Rex Burkhead": [40, 55, "Reliable third-down role back"],
    "James White": [55, 60, "Super Bowl overtime hero back"],
    "Mike Tolbert": [45, 60, "Stocky short-yardage power back"],

    "Jerry Rice": [98, 80, "Greatest receiver ever, tireless worker"],
    "Randy Moss": [95, 55, "Unmatched deep-ball vertical threat"],
    "Steve Largent": [82, 65, "Seahawks Hall of Famer, reliable hands"],
    "Doug Baldwin": [75, 68, "Slot technician, Super Bowl champion"],
    "Tyler Lockett": [80, 60, "Elite route runner, deep speed"],
    "DK Metcalf": [82, 58, "Explosive size-speed deep threat"],
    "Jaxon Smith-Njigba": [78, 50, "Rising slot route technician"],
    "Justin Jefferson": [95, 55, "Record-pace elite route runner"],
    "Ja'Marr Chase": [93, 55, "Explosive contested-catch superstar"],
    "CeeDee Lamb": [88, 52, "Cowboys volume target, sure hands"],
    "Tyreek Hill": [93, 50, "Cheetah speed, game-breaking threat"],
    "Puka Nacua": [82, 55, "Record-breaking rookie production"],
    "Amon-Ra St. Brown": [85, 58, "Reliable slot volume machine"],
    "Malik Nabers": [80, 52, "Explosive rookie target share"],
    "A.J. Brown": [88, 58, "Physical downfield mismatch weapon"],
    "Davante Adams": [90, 55, "Route-running savant, red-zone threat"],
    "Calvin Johnson": [92, 55, "Megatron, unstoppable jump-ball weapon"],
    "Larry Fitzgerald": [88, 70, "Sure-handed, longevity and clutch"],
    "Terrell Owens": [90, 45, "Dominant physical touchdown scorer"],
    "Julio Jones": [88, 52, "Freak athlete, yardage machine"],
    "Julian Edelman": [72, 68, "Super Bowl MVP, tough slot receiver"],
    "Wes Welker": [78, 55, "Prolific slot possession receiver"],
    "Jermaine Kearse": [55, 58, "Clutch Seahawks playoff catches"],
    "Golden Tate": [68, 50, "Elite yards-after-catch playmaker"],
    "Chad Johnson": [82, 42, "Ochocinco, flashy touchdown scorer"],
    "Danny Amendola": [55, 58, "Gritty slot possession receiver"],
    "Victor Cruz": [65, 45, "Salsa celebration, breakout Giant"],
    "Cole Beasley": [55, 50, "Undersized reliable slot chains-mover"],
    "Adam Thielen": [72, 55, "Undrafted breakout possession receiver"],
    "Hunter Renfrow": [58, 48, "Crafty undersized slot technician"],
    "David Tyree": [40, 45, "Helmet catch, one iconic moment"],
    "Josh Cribbs": [55, 42, "Elite return specialist, part-time receiver"],
    "Devin Hester": [50, 40, "Greatest return man ever"],
    "Jake Bobo": [45, 50, "Undrafted possession receiver depth"],
    "Kendrick Bourne": [55, 50, "Energetic complementary deep threat"],
    "Deion Branch": [58, 55, "Super Bowl MVP, reliable target"],
    "Wayne Chrebet": [55, 60, "Undersized Jets fan-favorite grinder"],
    "Ricky Proehl": [50, 55, "Long-career clutch postseason target"],
    "Chris Hogan": [48, 50, "Lacrosse convert, Patriots deep threat"],
    "Cordarrelle Patterson": [55, 42, "Elite kick returner, versatile weapon"],

    "Travis Kelce": [92, 65, "Most prolific modern tight end"],
    "George Kittle": [85, 78, "Elite blocker and receiver combo"],
    "Rob Gronkowski": [92, 60, "Unstoppable red-zone touchdown machine"],
    "Tony Gonzalez": [90, 55, "Record-setting reception tight end"],
    "Shannon Sharpe": [82, 50, "Trash-talking Hall of Fame pass-catcher"],
    "Antonio Gates": [85, 45, "Basketball convert, red-zone terror"],
    "Jason Witten": [78, 72, "Reliable durable Cowboys mainstay"],
    "Mark Andrews": [82, 50, "Lamar's favorite red-zone target"],
    "Trey McBride": [80, 55, "Breakout dual-threat modern tight end"],
    "Brock Bowers": [82, 52, "Explosive rookie receiving phenom"],
    "Sam LaPorta": [75, 52, "Efficient rookie-record pass catcher"],
    "Tyler Warren": [65, 50, "Versatile rising rookie weapon"],
    "Mike Ditka": [78, 75, "Da Coach, bruising player first"],
    "Kellen Winslow": [82, 55, "Pioneer of pass-catching tight ends"],
    "Jimmy Graham": [78, 45, "Athletic dunking red-zone weapon"],
    "Zach Ertz": [78, 60, "Reliable Super Bowl-clinching target"],
    "Greg Olsen": [75, 58, "Steady three-time Pro Bowl target"],
    "Dallas Goedert": [72, 58, "Efficient complementary Eagles weapon"],
    "Dallas Clark": [70, 50, "Colts slot-tight end weapon"],
    "AJ Barner": [45, 55, "Developing blocking-focused young tight end"],
    "Luke Willson": [40, 50, "Reliable Seahawks depth tight end"],
    "Will Dissly": [45, 65, "Blocking-first Seahawks red-zone target"],
    "Martellus Bennett": [60, 55, "Athletic journeyman, colorful personality"],
    "Vernon Davis": [72, 50, "Explosive athletic vertical threat"],
    "Jared Cook": [65, 45, "Athletic journeyman receiving tight end"],
    "Kyle Rudolph": [62, 58, "Reliable red-zone possession target"],
    "Heath Miller": [60, 68, "Durable Steelers blocking mainstay"],
    "Marcedes Lewis": [40, 72, "Elite veteran run-blocking specialist"],
    "Delanie Walker": [68, 55, "Underrated tough all-around tight end"],
    "Owen Daniels": [58, 50, "Steady Texans possession target"],
    "Jermichael Finley": [60, 42, "Talented but injury-cut-short career"],
    "Ben Watson": [45, 65, "Long-career reliable blocking veteran"],
    "Dan Campbell": [50, 60, "Tough journeyman, now head coach"],
    "Frank Wycheck": [55, 52, "Music City Miracle lateral thrower"],
    "Mark Bavaro": [55, 70, "Punishing blocker, Giants Super Bowl"],
    "Chris Cooley": [58, 50, "Quirky reliable Redskins pass-catcher"],
    "Julius Thomas": [62, 40, "Athletic red-zone touchdown scorer"],
    "Tyler Eifert": [58, 40, "Talented but injury-derailed tight end"],
    "Logan Thomas": [50, 55, "QB convert turned solid tight end"],

    "Richard Sherman": [78, 92, "Legion of Boom shutdown corner"],
    "Earl Thomas": [75, 94, "Elite range, ball-hawking safety"],
    "Kam Chancellor": [70, 90, "Bone-crushing enforcer safety"],
    "Bobby Wagner": [75, 92, "Sideline-to-sideline tackling machine"],
    "Cortez Kennedy": [72, 85, "Dominant interior pass-rush force"],
    "Devon Witherspoon": [65, 80, "Physical rookie shutdown corner"],
    "Manti Te'o": [45, 55, "Notre Dame star, modest NFL career"],
    "DeForest Buckner": [68, 80, "Disruptive interior pass rusher"],
    "Lawrence Taylor": [92, 85, "Redefined the pass-rush position"],
    "Reggie White": [90, 88, "Minister of Defense, sack legend"],
    "Ray Lewis": [80, 92, "Intense leader, tackling legend"],
    "Deion Sanders": [82, 90, "Prime Time, lockdown shutdown corner"],
    "Troy Polamalu": [78, 88, "Wild-haired ball-hawking safety"],
    "J.J. Watt": [90, 85, "Three-time Defensive Player of Year"],
    "Aaron Donald": [95, 90, "Most disruptive interior lineman ever"],
    "T.J. Watt": [88, 82, "Elite sack artist, Pittsburgh terror"],
    "Myles Garrett": [88, 80, "Explosive edge-rushing force"],
    "Micah Parsons": [90, 80, "Versatile edge-rushing phenom"],
    "Sauce Gardner": [70, 88, "Shutdown rookie of the year corner"],
    "Aidan Hutchinson": [78, 72, "Rising elite edge rusher"],
    "Michael Bennett": [72, 68, "Versatile disruptive line presence"],
    "Brandon Mebane": [55, 72, "Run-stuffing nose tackle anchor"],
    "Red Bryant": [50, 75, "Massive run-defense specialist"],
    "K.J. Wright": [60, 75, "Steady versatile Legion linebacker"],
    "Malcolm Smith": [50, 55, "Super Bowl MVP linebacker"],
    "Byron Maxwell": [50, 55, "Solid complementary Seahawks corner"],
    "Cliff Avril": [65, 58, "Speed-rush complement, championship pieces"],
    "James Harrison": [78, 75, "Super Bowl pick-six sack legend"],
    "Vince Wilfork": [50, 85, "Massive immovable nose tackle"],
    "William Perry": [40, 60, "The Fridge, goal-line cult hero"],
    "Brett Keisel": [50, 65, "Bearded Steelers run-stopping mainstay"],
    "Jared Allen": [82, 65, "Sack artist, lasso celebration"],
    "Tyson Alualu": [45, 60, "Steady run-stopping defensive tackle"],
    "Jevon Kearse": [75, 55, "Freak of Nature, explosive rookie sacks"],
    "Clay Matthews": [75, 60, "Flowing-hair sack-producing linebacker"],
    "London Fletcher": [55, 80, "Undersized durable tackling machine"],
    "Tedy Bruschi": [55, 78, "Heady leader, Patriots dynasty piece"],
    "Mike Vrabel": [58, 70, "Versatile linebacker, now head coach"],
    "Chris Long": [55, 60, "Reliable veteran edge presence"],
    "Kyle Williams": [55, 72, "Underrated interior line stalwart"]
  },
  mlb: {
    "Yoshinobu Yamamoto": [88, 70, "Ace import, pinpoint command"],
    "Roki Sasaki": [85, 55, "Triple-digit heat, electric young arm"],
    "Yu Darvish": [85, 68, "Deep pitch mix, durable ace"],
    "Hideo Nomo": [78, 65, "Tornado delivery, MLB trailblazer"],
    "Paul Skenes": [92, 58, "Overpowering rookie phenom ace"],
    "Tarik Skubal": [90, 72, "Cy Young dominant control artist"],
    "Logan Gilbert": [78, 72, "Steady Mariners rotation anchor"],
    "George Kirby": [75, 80, "Elite command, minimal walks"],
    "Bryan Woo": [70, 68, "Emerging efficient Mariners starter"],
    "Felix Hernandez": [88, 78, "King Felix, perfect game ace"],
    "Randy Johnson": [93, 75, "Big Unit, dominant left-handed heat"],
    "Sid Fernandez": [65, 55, "Deceptive Mets rotation strikeout arm"],
    "Sandy Koufax": [92, 60, "Dominant peak, arm cut it short"],
    "Nolan Ryan": [95, 90, "Strikeout king, seven no-hitters"],
    "Pedro Martinez": [95, 65, "Peak dominance, unhittable stuff"],
    "Clayton Kershaw": [92, 75, "Modern era's most dominant lefty"],
    "Greg Maddux": [85, 92, "Command artist, four Cy Youngs"],
    "Mariano Rivera": [85, 90, "Greatest closer ever, cutter legend"],
    "Justin Verlander": [90, 80, "Power arm, longevity and no-hitters"],
    "Jacob deGrom": [95, 45, "Electric stuff, injury-shortened peak"],
    "Bartolo Colon": [55, 88, "Big Sexy, beloved journeyman longevity"],
    "Rich Hill": [55, 70, "Late-career journeyman revival arm"],
    "Pat Venditte": [40, 55, "Switch-pitching novelty reliever"],
    "Jamie Moyer": [50, 90, "Junk-balling ageless wonder"],
    "Fernando Rodney": [58, 45, "Arrow-shooting eccentric closer"],
    "Brian Wilson": [65, 50, "Bearded intimidating closer"],
    "Kenley Jansen": [78, 75, "Cutter-heavy elite closer"],
    "Tim Lincecum": [80, 40, "The Freak, dominant then faded"],
    "R.A. Dickey": [55, 70, "Knuckleball Cy Young surprise"],
    "Hideki Okajima": [55, 55, "Funky delivery, championship setup man"],
    "Koji Uehara": [65, 55, "Splitter specialist, playoff closer"],
    "Kazuhiro Sasaki": [65, 55, "Rookie of the Year closer"],
    "Shintaro Fujinami": [45, 40, "Erratic import, control struggles"],
    "Brandon League": [50, 50, "Journeyman setup and closer"],
    "Joba Chamberlain": [60, 40, "Explosive setup man, faded fast"],
    "Jonathan Papelbon": [72, 68, "Dominant closer, fist-pump intensity"],
    "Jesse Chavez": [50, 72, "Reliable swingman journeyman arm"],
    "Brent Suter": [45, 68, "Crafty soft-tossing lefty reliever"],
    "Mark Buehrle": [60, 92, "Quick-working durable innings eater"],
    "Kent Tekulve": [50, 80, "Submarine-throwing durable reliever"],

    "Cal Raleigh": [88, 75, "Big Dumper, record-setting power catcher"],
    "Kurt Suzuki": [60, 68, "Durable reliable veteran backstop"],
    "Dan Wilson": [55, 72, "Steady Mariners fan-favorite catcher"],
    "Kenji Johjima": [60, 65, "Japanese import, solid two-way catcher"],
    "Johnny Bench": [90, 95, "Greatest catcher ever, cannon arm"],
    "Yogi Berra": [85, 80, "Ten rings, unlikely quotable legend"],
    "Mike Piazza": [92, 45, "Greatest hitting catcher ever"],
    "Ivan Rodriguez": [80, 95, "Pudge, elite throwing arm legend"],
    "Buster Posey": [82, 80, "Franchise cornerstone, three championships"],
    "Yadier Molina": [65, 95, "Defensive maestro, pitcher whisperer"],
    "Salvador Perez": [80, 72, "Durable power-hitting Royals leader"],
    "Will Smith": [75, 68, "Dodgers modern power catcher"],
    "Adley Rutschman": [78, 75, "Switch-hitting franchise cornerstone"],
    "William Contreras": [78, 60, "Emerging power-hitting catcher"],
    "J.T. Realmuto": [78, 80, "Elite all-around modern catcher"],
    "Joe Mauer": [82, 72, "Batting champion, hometown hero"],
    "Carlton Fisk": [78, 80, "Iconic home run wave legend"],
    "Roy Campanella": [82, 82, "Three-time MVP, career cut short"],
    "Gary Carter": [75, 80, "Kid, championship defensive leader"],
    "Jorge Posada": [75, 58, "Core Four dynasty switch-hitter"],
    "David Ross": [45, 65, "Grandpa Rossy, veteran pitcher whisperer"],
    "A.J. Pierzynski": [65, 55, "Scrappy, well-traveled durable catcher"],
    "Jose Molina": [40, 85, "Pitch-framing pioneer, glove-first"],
    "Bengie Molina": [58, 65, "Steady power-hitting Molina brother"],
    "Mike Zunino": [55, 60, "Power-or-nothing strikeout-prone catcher"],
    "Jesus Sucre": [40, 55, "Journeyman backup defensive catcher"],
    "Jeff Mathis": [40, 72, "Glove-only, historically weak bat"],
    "Drew Butera": [40, 58, "Defense-first journeyman backup"],
    "Austin Hedges": [40, 80, "Elite defender, minimal offense"],
    "Erik Kratz": [40, 55, "Well-traveled journeyman backup catcher"],
    "Stephen Vogt": [55, 58, "All-Star journeyman, now manager"],
    "Tom Murphy": [55, 55, "Solid power bat, injury-prone"],
    "Luis Torrens": [45, 55, "Steady backup, Rule 5 pick"],
    "Brent Mayne": [40, 58, "Journeyman, pitched a game once"],
    "Russell Martin": [60, 72, "Durable All-Star two-way catcher"],
    "Jason Varitek": [58, 72, "Captain, no-hitter catching record"],
    "Bob Uecker": [40, 40, "Mr. Baseball, funnier than his stats"],
    "Chris Gimenez": [40, 50, "Journeyman utility emergency catcher"],
    "Dioner Navarro": [50, 55, "Switch-hitting journeyman starter"],
    "Carlos Ruiz": [58, 70, "Chooch, championship battery mate"],

    "Kolten Wong": [62, 80, "Gold Glove defensive second baseman"],
    "J.P. Crawford": [62, 72, "Steady Mariners defensive shortstop"],
    "Kyle Seager": [72, 72, "Reliable Mariners power third baseman"],
    "Adrian Beltre": [85, 90, "Hall of Fame glove and bat"],
    "Derek Jeter": [82, 68, "Captain, clutch postseason leader"],
    "Cal Ripken Jr.": [82, 85, "Iron Man, consecutive games streak"],
    "Jackie Robinson": [82, 75, "Broke barrier, dynamic star infielder"],
    "Lou Gehrig": [92, 70, "Iron Horse, dominant power hitter"],
    "Ozzie Smith": [55, 98, "Wizard, greatest defensive shortstop ever"],
    "Mike Schmidt": [90, 80, "Greatest power-hitting third baseman"],
    "Ryne Sandberg": [78, 82, "Smooth power-hitting second baseman"],
    "Albert Pujols": [95, 60, "Machine, all-time great slugger"],
    "Freddie Freeman": [88, 72, "Smooth-swinging consistent All-Star"],
    "Francisco Lindor": [85, 80, "Mr. Smile, two-way shortstop star"],
    "Bobby Witt Jr.": [88, 75, "Dynamic five-tool young star"],
    "Mookie Betts": [90, 82, "Elite two-way superstar, MVP"],
    "Jose Altuve": [85, 65, "Undersized batting champion, sparkplug"],
    "Gunnar Henderson": [85, 68, "Rising Orioles power shortstop"],
    "Elly De La Cruz": [82, 55, "Electric speed-power tool shortstop"],
    "Vladimir Guerrero Jr.": [90, 50, "Powerful bat, first-base slugger"],
    "David Eckstein": [55, 68, "Gritty undersized World Series MVP"],
    "Pablo Sandoval": [70, 50, "Kung Fu Panda, clutch postseason bat"],
    "Willie Bloomquist": [45, 60, "Versatile utility journeyman infielder"],
    "Ben Zobrist": [70, 72, "Ultimate versatile utility All-Star"],
    "Brock Holt": [55, 60, "Versatile cycle-hitting utility man"],
    "Enrique Hernandez": [55, 65, "Kike, clutch postseason utility man"],
    "Nick Punto": [40, 62, "Scrappy defensive-minded utility infielder"],
    "Mario Mendoza": [40, 55, "Namesake of the batting-line minimum"],
    "Dylan Moore": [50, 58, "Versatile Mariners utility contributor"],
    "Lenn Sakata": [40, 50, "Journeyman utility infielder curiosity"],
    "Munenori Kawasaki": [40, 55, "Beloved eccentric utility infielder"],
    "Kevin Youkilis": [72, 60, "Greek God of Walks, gritty hitter"],
    "Jose Iglesias": [55, 80, "Slick-fielding defensive shortstop"],
    "Sean Casey": [65, 50, "The Mayor, likable contact hitter"],
    "John Kruk": [65, 45, "Scrappy contact-hitting fan favorite"],
    "Luis Arraez": [80, 45, "Batting title contact-hitting machine"],
    "Willians Astudillo": [45, 40, "La Tortuga, cult-favorite contact hitter"],
    "Ty France": [65, 55, "Steady Mariners contact hitter"],
    "Josh Harrison": [58, 58, "Versatile journeyman All-Star infielder"],
    "Tony Kemp": [50, 55, "Undersized versatile utility contributor"],

    "Ichiro Suzuki": [82, 88, "Hit machine, elite outfield arm"],
    "Ken Griffey Jr.": [93, 88, "The Kid, sweetest swing ever"],
    "Julio Rodriguez": [85, 72, "J-Rod, five-tool Mariners star"],
    "Jay Buhner": [78, 72, "Bone-crushing power, Mariners icon"],
    "Randy Arozarena": [78, 58, "Postseason legend, electric playmaker"],
    "Shane Victorino": [72, 80, "Flyin Hawaiian, championship glove"],
    "Benny Agbayani": [55, 50, "Hawaii-born Mets fan favorite"],
    "Hideki Matsui": [80, 55, "Godzilla, World Series MVP power"],
    "Seiya Suzuki": [72, 60, "Steady import power hitter"],
    "Babe Ruth": [99, 55, "The Bambino, home run revolution"],
    "Willie Mays": [96, 95, "Say Hey Kid, complete superstar"],
    "Hank Aaron": [95, 72, "Hammerin Hank, all-time home runs"],
    "Mickey Mantle": [93, 72, "Switch-hitting power and speed legend"],
    "Rickey Henderson": [88, 80, "Greatest leadoff man, stolen base king"],
    "Tony Gwynn": [88, 68, "Mr. Padre, contact-hitting artist"],
    "Aaron Judge": [96, 65, "Modern home run record chaser"],
    "Juan Soto": [93, 55, "Elite eye, generational hitter"],
    "Mike Trout": [95, 75, "Best all-around player of his era"],
    "Ronald Acuna Jr.": [90, 68, "40-70 club, electric five-tool star"],
    "Kyle Tucker": [85, 70, "Complete all-around outfield star"],
    "Rick Ankiel": [55, 50, "Pitcher-turned-outfielder cannon arm"],
    "Brett Gardner": [58, 72, "Speedy durable Yankees leadoff man"],
    "Jarrod Dyson": [45, 72, "Elite speed and outfield range"],
    "Billy Hamilton": [40, 75, "Blazing pure speed, weak bat"],
    "Terrance Gore": [40, 55, "Pure pinch-running specialist"],
    "Endy Chavez": [50, 72, "Iconic robbed-homer defensive catch"],
    "Mitch Haniger": [70, 55, "Power bat, injury-riddled Mariners career"],
    "Mike Cameron": [68, 85, "Gold Glove elite center fielder"],
    "Raul Ibanez": [70, 45, "Steady late-career power surge"],
    "Ben Gamel": [50, 55, "Solid fourth-outfielder role player"],
    "Hunter Pence": [72, 55, "Quirky swing, championship energy"],
    "Jonny Gomes": [58, 45, "Fiery clubhouse energy bat"],
    "Nick Swisher": [65, 50, "Enthusiastic switch-hitting power bat"],
    "Juan Pierre": [58, 68, "Speedy slap-hitting stolen base threat"],
    "Coco Crisp": [62, 72, "Speedy center field table-setter"],
    "So Taguchi": [45, 60, "Japanese role player, championship pinch hitter"],
    "Kosuke Fukudome": [55, 50, "Import outfielder, modest MLB run"],
    "Tsuyoshi Shinjo": [50, 60, "Flashy import, electric fan favorite"],
    "Victor Robles": [45, 68, "Athletic glove, underwhelming bat"],
    "Mike Lum": [45, 50, "Long-career role-playing outfielder"],

    "Shohei Ohtani": [99, 85, "Two-way unicorn, unprecedented seasons"],
    "Edgar Martinez": [92, 55, "Greatest DH ever, pure hitter"],
    "David Ortiz": [92, 50, "Big Papi, clutch postseason legend"],
    "Frank Thomas": [93, 45, "Big Hurt, dominant middle-of-order bat"],
    "Nelson Cruz": [85, 45, "Boomstick, ageless power hitter"],
    "Yordan Alvarez": [92, 40, "Elite middle-of-order power bat"],
    "Kyle Schwarber": [85, 40, "Prolific slugger, all-or-nothing power"],
    "Giancarlo Stanton": [90, 42, "Massive raw power, injury history"],
    "Jim Thome": [88, 50, "Beloved slugger, 600 home runs"],
    "Paul Molitor": [82, 65, "Hit machine, versatile durable career"],
    "Travis Hafner": [78, 40, "Pronk, feared middle-of-order bat"],
    "Harold Baines": [72, 50, "Quiet consistent Hall of Fame bat"],
    "Marcell Ozuna": [78, 40, "Streaky power-hitting corner bat"],
    "Brent Rooker": [75, 45, "Late-blooming power breakout hitter"],
    "J.D. Martinez": [85, 42, "Swing-changed late-career power surge"],
    "Pete Alonso": [85, 48, "Polar Bear, prolific home run hitter"],
    "Eugenio Suarez": [75, 50, "Streaky power-hitting corner infielder"],
    "Mitch Garver": [65, 45, "Power-hitting converted catcher DH"],
    "Edwin Encarnacion": [82, 42, "Parrot celebration, steady power bat"],
    "Josh Naylor": [72, 48, "Emerging power and personality bat"],
    "Matt Stairs": [60, 40, "Journeyman pinch-hit home run legend"],
    "Lenny Harris": [45, 50, "All-time pinch-hit leader"],
    "Mark Sweeney": [50, 45, "Reliable veteran pinch-hit specialist"],
    "Adam Dunn": [78, 40, "Three true outcomes, massive power"],
    "Jack Cust": [65, 40, "High-strikeout, high-walk power bat"],
    "Russell Branyan": [58, 40, "Journeyman all-or-nothing power bat"],
    "Mike Morse": [65, 40, "Powerful late-blooming corner bat"],
    "Kendrys Morales": [72, 45, "Steady switch-hitting power bat"],
    "Billy Butler": [70, 50, "Country Breakfast, contact power bat"],
    "Dan Vogelbach": [58, 40, "Beloved fan-favorite power bat"],
    "Luke Voit": [65, 40, "Grandyman power surge, injury-prone"],
    "Kevin Millar": [58, 55, "Idiots era, clubhouse energy bat"],
    "Steve Balboni": [55, 40, "Bye Bye Balboni, power-only bat"],
    "Cecil Fielder": [78, 40, "Big Daddy, 50 home run season"],
    "Mark Trumbo": [70, 40, "Home Run Derby power slugger"],
    "Josh Willingham": [65, 42, "Steady journeyman power bat"],
    "Rowdy Tellez": [58, 40, "Left-handed platoon power bat"],
    "Pedro Alvarez": [65, 40, "Boom-or-bust power third baseman"],
    "Steve Pearce": [55, 50, "World Series MVP journeyman bat"],
    "Wily Mo Pena": [58, 40, "Raw power, contact struggles"],
    "Edwin Diaz": [88, 62, "Elite strikeout closer"]
  }
};
