import http from 'node:http';
import {setupPhysical,physicalAction,physicalElapsed,physicalStop,categories} from './physical.mjs';
import {GAMES,compatible} from './public/catalog.js';
import {decks,deckNames} from './mixer.mjs';
import {randomBytes,randomInt} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import os from 'node:os';
const networkAddresses=()=>Object.values(os.networkInterfaces()).flat().filter(n=>n&&n.family==='IPv4'&&!n.internal).map(n=>n.address);
const root=fileURLToPath(new URL('./public/',import.meta.url));
const gameFormats=id=>GAMES.find(g=>g.id===id)?.formats||[];
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=randomInt(i+1);[b[i],b[j]]=[b[j],b[i]];}return b;};
const id=()=>randomBytes(18).toString('hex');
const meals=['Build your dream fast-food meal.','Build the best meal after a concert.','Build a drive-through date-night dinner.','Build the ultimate road-trip meal.'];
const foods=[['Big Mac','Crunchwrap','Chicken sandwich','Veggie burger','Pizza slice','Bean burrito','Nuggets','Hot dog'],['Curly fries','Onion rings','Waffle fries','Hash browns','Mac & cheese','Mozzarella sticks','Apple slices','Chips & guac'],['Milkshake','Lemonade','Iced coffee','Root beer','Sweet tea','Orange soda','Water','Hot chocolate'],['Extra pickles','Soft serve','Hot sauce','Cookie','Bacon','Breakfast egg','Donut','Mystery sauce']];
const brain=['Worst animal to share an elevator with?','Best midnight snack?','Most suspicious thing to carry in a briefcase?','Worst place to fall asleep?','An animal that would be a terrible roommate?','What would a pigeon buy with $100?'];
const nums=[['How many minutes are in one week?',10080],['How many squares are on a standard chessboard (individual cells)?',64],['How many legs do seven spiders have?',56],['How many seconds are in two hours?',7200],['How many sides do nine triangles have altogether?',27],['How many months are in 15 years?',180],['How many cards are in a standard deck without jokers?',52],['How many days are in three non-leap years?',1095],['How many inches are in five feet?',60]];
const drawings=['A pigeon applying for a mortgage','A potato on its first date','A haunted vending machine','A raccoon running a luxury hotel','A dinosaur stuck on a video call'];
const secrets=[['Airport','Places'],['Popcorn','Food'],['Dentist','Jobs'],['Camping','Activities'],['Karaoke','Activities'],['Aquarium','Places'],['Library','Places'],['Roller coaster','Things you ride'],['Pizza','Food'],['Firefighter','Jobs'],['Bicycle','Things you ride'],['Bowling','Activities']];
const norm=s=>s.toLowerCase().replace(/[^a-z0-9 ]/g,'').replace(/^(a|an|the) /,'').trim().replace(/\s+/g,' ');
export class Game {
 constructor(){this.rooms=new Map();this.clients=new Map();}
 player(r,t){const p=r.players.find(p=>p.token===t&&!p.left);if(!p)throw Error('Your seat is unavailable. Rejoin the room.');return p;}
 create(name,mode='tournament'){if(!['tournament','minigames'].includes(mode))throw Error('Choose Party mode or Minigames.');if(!String(name||'').trim())throw Error('Enter a nickname.');let code;do{code=Array.from({length:4},()=> 'ABCDEFGHJKLMNPQRSTUVWXYZ'[randomInt(24)]).join('');}while(this.rooms.has(code));const r={code,phase:'lobby',round:0,players:[],host:null,mode,selectedGame:'brain',enabledGames:GAMES.map(g=>g.id),banEnabled:true,deck:'ice',history:[],last:Date.now(),seen:{}};this.rooms.set(code,r);return this.join(code,name);}
 join(code,name){const r=this.rooms.get(String(code).toUpperCase());if(!r)throw Error('Room not found. Check the four-letter code.');if(r.phase!=='lobby')throw Error('This game has started. Reconnect with your original tab, or join after the rematch.');if(r.players.filter(p=>!p.left).length>=8)throw Error('This room already has eight players.');name=String(name||'').trim().slice(0,18);if(!name)throw Error('Enter a nickname.');if(r.players.some(p=>!p.left&&p.name.toLowerCase()===name.toLowerCase()))throw Error('That nickname is taken. Try another.');r.players=r.players.filter(p=>!p.left);const p={id:id(),token:id(),name,chips:100,spots:0,left:false,lastSeen:Date.now()};r.players.push(p);r.host ||=p.id;this.emit(r);return {code:r.code,token:p.token};}
 live(r){return r.players.filter(p=>!p.left);}
 phase(r,phase,seconds){r.phase=phase;r.deadline=seconds?Date.now()+seconds*1000:null;}
 mixerNext(r){r.round++;if(r.round>12){this.phase(r,'finished');return;}const card=r.mixerDeck[r.round-1];r.game='mixer';r.prompt=card[1];r.mixerKind=card[0];r.options=card[2]||[];r.submissions={};r.passes=[];r.ready=[];r.active=this.live(r).map(p=>p.id);r.spot=false;r.stakes={};r.bets={};r.teams=[];r.picks={};r.votes={};r.result=null;this.phase(r,'mixer');}
 mixerReveal(r){r.history.push({round:r.round,game:'mixer',prompt:r.prompt,detail:r.mixerKind});this.phase(r,'mixerReveal');}
 pool(r,spot=r.spot){if(r.mode==='minigames')return compatible([r.selectedGame],this.live(r).length,spot);return compatible(r.enabledGames||GAMES.map(g=>g.id),this.live(r).length,spot);}
 selectionError(r){if(r.mode==='minigames')return GAMES.some(g=>g.id===r.selectedGame&&g.min<=this.live(r).length)?null:'Choose a game that supports this group.';if(!this.pool(r,false).length)return 'Choose an everyone-plays game that supports this group.';if(!this.pool(r,true).length)return 'Choose a spotlight game that supports this group. With two players, include Ballpark.';return null;}
 betting(r){this.phase(r,r.spot?'entry':'stake',15);}
 closeBan(r){const totals=Object.fromEntries(r.candidates.map(g=>[g,0]));Object.values(r.banVotes).forEach(g=>{if(g)totals[g]++;});const most=Math.max(0,...Object.values(totals));const tied=r.candidates.filter(g=>totals[g]===most);r.banned=most>0?shuffle(tied)[0]:null;r.banTie=most>0&&tied.length>1;r.banTotals=totals;r.candidates=r.candidates.filter(g=>g!==r.banned);this.phase(r,'banResult',4);}
 fresh(r){r.round++;r.spot=r.round%3===0;r.active=[];r.teams=[];r.stakes={};r.submissions={};r.votes={};r.bets={};r.decisions={};r.eliminated=[];r.ladder=5;r.game=null;r.result=null;r.cards=[];r.draftStep=0;r.draftTurn=0;r.picks={};r.clues={};r.clueOrder=[];r.clueIndex=0;r.category=null;r.physical=null;r.free=r.mode==='minigames';this.live(r).forEach(p=>{if(r.mode!=='minigames'&&p.chips<5)p.chips=5;r.stakes[p.id]=5;});r.banVotes={};r.banTotals={};r.banned=null;r.banTie=false;r.candidates=this.pool(r);r.spinOptions=[];r.spinStarted=null;r.spinAngle=0;this.phase(r,r.banEnabled&&r.candidates.length>=3?'ban':r.spot?'entry':'stake',r.banEnabled&&r.candidates.length>=3?18:15);}
 choose(r){if(r.mode==='minigames'){r.spot=!gameFormats(r.selectedGame).includes('all');r.candidates=[r.selectedGame];r.free=true;}let eligible=r.spot?this.live(r).filter(p=>!r.eliminated.includes(p.id)):this.live(r);if(eligible.length<2){eligible=this.live(r);r.free=true;r.spot=false;r.candidates=this.pool(r,false).filter(g=>g!==r.banned);}
 const compatiblePool=this.pool(r);let pool=(r.candidates||compatiblePool).filter(g=>compatiblePool.includes(g)&&g!==r.banned);
 if(!pool.length){r.game=null;r.active=[];r.result={winners:[],tie:true,detail:'No compatible game remains. This round is skipped; no chips were taken.',changes:{},totals:{},answers:{},picks:{}};this.phase(r,'result');return;}
 r.spinOptions=pool;r.game=pool[randomInt(pool.length)];r.previous=r.game;
 if(r.spot){let size=r.game==='number'?shuffle([2,...(eligible.length>=4?[4]:[]),...(eligible.length>=6?[6]:[]),...(eligible.length>=8?[8]:[])])[0]:2;eligible=shuffle(eligible).sort((a,b)=>a.spots-b.spots).slice(0,size);eligible.forEach(p=>p.spots++);r.teams=[[],[]];shuffle(eligible).forEach((p,i)=>r.teams[i%2].push(p.id));}
 r.active=eligible.map(p=>p.id);r.active.forEach(pid=>{const p=r.players.find(p=>p.id===pid);r.stakes[pid]=r.free?0:Math.min(p.chips,r.spot?r.ladder:r.stakes[pid]);p.chips-=r.stakes[pid];});
 const pick=(key,items)=>{const seen=r.seen[key]||[];let available=items.map((_,i)=>i).filter(i=>!seen.includes(i));if(!available.length){available=items.map((_,i)=>i);r.seen[key]=[];}const i=shuffle(available)[0];(r.seen[key]||=[]).push(i);return items[i];};
 if(r.game==='brain')r.prompt=pick('brain',brain);
 if(r.game==='number'){[r.prompt,r.answer]=pick('number',nums);}
 if(r.game==='draft'){r.prompt=pick('meal',meals);r.active.forEach(pid=>r.picks[pid]=[]);r.cards=foods[0];}
 if(r.game==='draw')r.prompt=pick('draw',drawings);
 if(r.game==='imposter'){r.prompt='Give one clue without saying the word';[r.secret,r.category]=pick('secret',secrets);const candidates=shuffle(eligible).sort((a,b)=>(a.fakerCount||0)-(b.fakerCount||0));r.imposter=candidates[0].id;candidates[0].fakerCount=(candidates[0].fakerCount||0)+1;r.clueOrder=shuffle(r.active);r.clueIndex=0;}
 if(['shadow','rhythm'].includes(r.game)){setupPhysical(r);r.prompt=r.game==='shadow'?'Point and dodge in person':'Choose a category together';}
 r.spinStarted=Date.now();r.spinAngle=1440+360-((r.spinOptions.indexOf(r.game)+0.5)*360/r.spinOptions.length);this.phase(r,r.mode==='minigames'?'reveal':'spin',r.mode==='minigames'?6:4);
 }
 begin(r){if(['shadow','rhythm'].includes(r.game))this.phase(r,'physicalSetup');else if(r.game==='imposter')this.phase(r,'clue',20);else if(r.game==='draft')this.phase(r,'draft',15);else this.phase(r,'play',r.game==='draw'?45:r.game==='imposter'?35:30);}
 nextClue(r){r.clueIndex++;if(r.clueIndex>=r.clueOrder.length){if(!Object.keys(r.clues).length){r.votes={};this.settle(r);}else this.phase(r,'discuss',30);}else this.phase(r,'clue',20);}
 advance(r){if(r.phase==='clue')this.nextClue(r);else if(r.phase==='ban')this.closeBan(r);else if(r.phase==='banResult')this.betting(r);else if(r.phase==='spin')this.phase(r,'reveal',10);else if(r.phase==='stake'){this.choose(r);}else if(r.phase==='entry'){const remaining=this.live(r).filter(p=>!r.eliminated.includes(p.id));for(const p of remaining)if(r.decisions[p.id]!=='stay'||p.chips<r.ladder)r.eliminated.push(p.id);const n=this.live(r).filter(p=>!r.eliminated.includes(p.id)).length;if(n<=2||r.ladder===20)this.choose(r);else{r.ladder=r.ladder===5?10:20;r.decisions={};this.phase(r,'entry',12);}}else if(r.phase==='reveal')this.begin(r);else if(r.phase==='draft'){this.draftPick(r,r.cards[0]);}else if(r.phase==='play'){if(r.game==='imposter')this.phase(r,'discuss',30);else if(['draw'].includes(r.game))this.phase(r,'vote',20);else this.settle(r);}else if(r.phase==='discuss')this.phase(r,'vote',20);else if(r.phase==='vote')this.settle(r);this.emit(r);}
 draftPlayer(r){const pair=r.draftStep%2===0?[0,1]:[1,0];return r.active[pair[r.draftTurn]];}
 draftPick(r,item){const pid=this.draftPlayer(r);r.picks[pid].push(item);r.cards=r.cards.filter(x=>x!==item);r.draftTurn++;if(r.draftTurn===2){r.draftTurn=0;r.draftStep++;r.cards=foods[r.draftStep]||[];}if(r.draftStep===4)this.phase(r,'pitch',20);else this.phase(r,'draft',15);}
 voters(r){return this.live(r).filter(p=>r.game==='imposter'?r.active.includes(p.id):!r.active.includes(p.id));}
 settle(r){if(r.phase==='result'||r.phase==='finished')return;let winners=[],tie=false,detail='';const totals={};
 if(['shadow','rhythm'].includes(r.game)){const scores=r.physical.scores;const best=r.game==='shadow'?Math.max(...Object.values(scores)):Math.min(...Object.values(scores));winners=r.active.filter(id=>scores[id]===best);tie=winners.length===r.active.length;if(tie)winners=[];detail=r.game==='shadow'?'Final score confirmed by both players.':'Two trips around the group. Fewest mistakes wins.';}
 if(r.game==='brain'){const groups=Object.create(null);for(const pid of r.active){const a=norm(r.submissions[pid]||'');if(a)(groups[a]||=[]).push(pid);}winners=Object.values(groups).filter(a=>a.length>1).flat();detail='Match another answer to win. Articles, capitals, punctuation and extra spaces are ignored.';}
 if(r.game==='number'){const value=pid=>r.submissions[pid]===undefined?Infinity:Math.abs(Number(r.submissions[pid])-r.answer);if(r.spot){const distances=r.teams.map(t=>t.reduce((s,p)=>s+value(p),0)/t.length);tie=distances[0]===distances[1];if(!tie)winners=r.teams[distances[0]<distances[1]?0:1];}else{const best=Math.min(...r.active.map(value));winners=Number.isFinite(best)?r.active.filter(p=>value(p)===best):[];}detail=`The answer is ${r.answer.toLocaleString()}. ${r.spot?'Lowest team average error wins. Every teammate must submit.':'Closest guesses win, including ties.'}`;}
 if(['draft','draw','imposter'].includes(r.game)){Object.values(r.votes).forEach(pid=>totals[pid]=(totals[pid]||0)+1);const max=Math.max(0,...Object.values(totals));const leaders=r.active.filter(pid=>totals[pid]===max);if(r.game==='imposter'){const caught=max>0&&leaders.length===1&&leaders[0]===r.imposter;tie=max===0;winners=tie?[]:caught?r.active.filter(p=>p!==r.imposter):[r.imposter];detail=`${r.players.find(p=>p.id===r.imposter).name} was the faker. The word was “${r.secret}”. ${tie?'No votes were cast, so everyone gets their chips back.':caught?'You found the faker.':'The faker escaped. A tied vote lets the faker win.'}`;}else{tie=max===0||leaders.length!==1;winners=tie?[]:leaders;detail=tie?'The audience tied or did not vote. Stakes returned.':'The audience has spoken.';}}
 const changes={};for(const pid of r.active){const p=r.players.find(p=>p.id===pid),s=r.stakes[pid];const delta=tie?0:winners.includes(pid)?s:-s;p.chips+=tie?s:winners.includes(pid)?s*2:0;changes[pid]=delta;}
 for(const [pid,b] of Object.entries(r.bets)){const p=r.players.find(p=>p.id===pid);const won=r.teams[b.team].some(x=>winners.includes(x));p.chips+=tie?b.amount:won?b.amount*2:0;changes[pid]=(changes[pid]||0)+(tie?0:won?b.amount:-b.amount);}
 r.result={winners,tie,detail,changes,totals,answers:r.game==='imposter'?r.clues:r.submissions,picks:r.picks};r.history.push({round:r.round,game:r.game,prompt:r.prompt,detail,changes});if(r.history.length>50)r.history.splice(0,r.history.length-50);this.phase(r,'result');}
 action(r,p,a){if(a.round!==undefined&&a.round!==r.round)throw Error('The round changed. Try again.');if(a.type.startsWith('mixer')&&a.round!==undefined&&a.round!==r.round)throw Error('This card has changed. Try the current card.');if(r.deadline&&Date.now()>=r.deadline){this.tick();throw Error('Time is up. Use the current round screen.');}r.last=Date.now();const host=()=>{if(r.host!==p.id)throw Error('Only the host can do that.');};const phase=(...s)=>{if(!s.includes(r.phase))throw Error('That part of the round has ended.');};
 if(a.type.startsWith('physical')){physicalAction(this,r,p,a);this.emit(r);return;}
 switch(a.type){case 'takeover':{const current=r.players.find(q=>q.id===r.host);if(current&&!current.left&&(!(current.lastSeen||current.disconnectedAt)||Date.now()-(current.lastSeen||current.disconnectedAt)<30000))throw Error('The host is still connected, or is reconnecting. Try again in 30 seconds.');r.host=p.id;break;}
 case 'beginGame':host();phase('reveal');if(r.mode!=='minigames')throw Error('Wait for the reveal timer.');this.begin(r);break;
 case 'selectGame':host();phase('lobby');if(r.mode!=='minigames'||!GAMES.some(g=>g.id===a.game&&g.min<=this.live(r).length))throw Error('Choose a compatible game.');r.selectedGame=a.game;break;
 case 'mode':host();phase('lobby');if(!['tournament','minigames'].includes(a.mode))throw Error('Invalid mode.');if(r.mode!==a.mode){r.round=0;r.history=[];r.players.forEach(q=>{q.chips=100;q.spots=0;});}r.mode=a.mode;break;
 case 'replay':host();phase('result');if(r.mode!=='minigames'||this.live(r).length<2)throw Error('Choose a game in the lobby.');r.selectedGame=r.game;this.fresh(r);this.choose(r);break;
 case 'lobby':host();phase('result','finished');r.physical=null;r.result=null;this.phase(r,'lobby');break;
 case 'removeDisconnected':{host();const q=r.players.find(q=>q.id===a.player&&!q.left);if(!q||q.id===p.id||!q.lastSeen||Date.now()-q.lastSeen<30000)throw Error('Only disconnected players can be removed after 30 seconds.');this.action(r,q,{type:'leave',round:r.round});break;}
 case 'toggleGame':host();phase('lobby');if(!GAMES.some(g=>g.id===a.game))throw Error('Unknown game.');r.enabledGames=r.enabledGames.includes(a.game)?r.enabledGames.filter(g=>g!==a.game):[...r.enabledGames,a.game];break;
 case 'banSetting':host();phase('lobby');r.banEnabled=!!a.enabled;break;
 case 'banVote':phase('ban');if(a.round!==undefined&&a.round!==r.round)throw Error('That vote belongs to an earlier round.');if(Object.hasOwn(r.banVotes,p.id))throw Error('Your vote is already locked.');if(a.game!==null&&!r.candidates.includes(a.game))throw Error('Choose one of the candidate games.');r.banVotes[p.id]=a.game;if(this.live(r).every(q=>Object.hasOwn(r.banVotes,q.id)))this.closeBan(r);break;
 case 'configure':host();phase('lobby');if(!['tournament','mixer'].includes(a.mode)||!Object.hasOwn(decks,a.deck))throw Error('Choose a valid mode and deck.');r.mode=a.mode;r.deck=a.deck;break;
 case 'start':host();phase('lobby');if(this.live(r).length<2)throw Error('Invite at least one more player.');if(r.mode==='mixer'){r.round=0;r.mixerDeck=shuffle(decks[r.deck]);this.mixerNext(r);}else {const error=this.selectionError(r);if(error)throw Error(error);this.fresh(r);if(r.mode==='minigames')this.choose(r);}break;
 case 'mixerAnswer':phase('mixer');if(r.submissions[p.id]!==undefined||r.passes.includes(p.id))throw Error('You already responded.');if(a.pass)r.passes.push(p.id);else {const value=String(a.value||'').trim().slice(0,240);if(!value)throw Error('Share an answer or choose Pass.');if(r.options.length&&!r.options.includes(value))throw Error('Choose one of the options.');r.submissions[p.id]=value;}if(this.live(r).every(q=>r.submissions[q.id]!==undefined||r.passes.includes(q.id)))this.mixerReveal(r);break;
 case 'mixerReveal':host();phase('mixer');this.mixerReveal(r);break;
 case 'mixerNext':host();phase('mixerReveal');this.mixerNext(r);break;
 case 'mixerSkip':phase('mixer','mixerReveal');this.mixerNext(r);break;
 case 'mixerEnd':host();phase('mixer','mixerReveal');this.phase(r,'finished');break;
 case 'stake':phase('stake');if(![5,10,20].includes(a.amount)||a.amount>p.chips)throw Error('Choose an affordable stake.');r.stakes[p.id]=a.amount;break;
 case 'entry':phase('entry');if(r.eliminated.includes(p.id))throw Error('You are in the audience for this round.');r.decisions[p.id]=a.stay?'stay':'fold';if(!a.stay)r.eliminated.push(p.id);break;
 case 'bet':phase('reveal');if(r.mode==='minigames'||r.game!=='number'||!r.spot||r.active.includes(p.id))throw Error('Side bets are only available to the audience in objective rounds.');if(r.bets[p.id])throw Error('Your prediction is already locked.');if(![0,1].includes(a.team)||p.chips<5)throw Error('You need 5 chips to predict.');r.bets[p.id]={team:a.team,amount:5};p.chips-=5;break;
 case 'clue':phase('clue');if(p.id!==r.clueOrder[r.clueIndex])throw Error('Wait for your turn.');if(a.clueIndex!==r.clueIndex)throw Error('That turn has ended.');{const clue=String(a.value||'').trim().slice(0,30);if(!clue)throw Error('Enter a clue.');if(p.id!==r.imposter&&norm(clue).includes(norm(r.secret)))throw Error('Give a clue without using the secret word.');r.clues[p.id]=clue;r.submissions[p.id]=clue;this.nextClue(r);}break;
 case 'submit':phase('play');if(!r.active.includes(p.id))throw Error('You are in the audience.');if(r.submissions[p.id]!==undefined)throw Error('Already submitted.');if(r.game==='number'){if(a.value===''||!Number.isFinite(Number(a.value))||Math.abs(Number(a.value))>1e9)throw Error('Enter a number between -1 billion and 1 billion.');r.submissions[p.id]=Number(a.value);}else if(r.game==='draw'){if(typeof a.value!=='string'||a.value.length>100000||!a.value.startsWith('data:image/png;base64,'))throw Error('Submit a drawing.');r.submissions[p.id]=a.value;}else{const s=String(a.value||'').trim().slice(0,r.game==='imposter'?30:80);if(!s)throw Error('Write an answer first.');r.submissions[p.id]=s;if(r.game==='imposter')r.clues[p.id]=s;}if(r.active.every(pid=>r.submissions[pid]!==undefined))this.advance(r);break;
 case 'pick':phase('draft');if(p.id!==this.draftPlayer(r))throw Error('Wait for your turn.');if(!r.cards.includes(a.item))throw Error('That item was already picked.');this.draftPick(r,a.item);break;
 case 'pitch':phase('pitch');if(!r.active.includes(p.id))throw Error('Only contestants can pitch.');r.submissions[p.id]=String(a.value||'').trim().slice(0,100);break;
 case 'vote':phase('vote');if(!this.voters(r).some(v=>v.id===p.id)||r.bets[p.id])throw Error('You cannot judge this round.');if(!r.active.includes(a.player)||a.player===p.id)throw Error('Choose another contestant.');if(r.votes[p.id])throw Error('Your vote is locked.');r.votes[p.id]=a.player;if(this.voters(r).every(v=>r.votes[v.id]))this.settle(r);break;
 case 'next':host();phase('result');if(r.round>=9||this.live(r).length<2)this.phase(r,'finished');else this.fresh(r);break;
 case 'rematch':host();phase('finished');r.players=r.players.filter(p=>!p.left);r.players.forEach(p=>{p.chips=100;p.spots=0;p.fakerCount=0;});r.round=0;r.history=[];r.result=null;this.phase(r,'lobby');break;
 case 'leave':if(r.mode==='mixer'){p.left=true;if(p.id===r.host)r.host=this.live(r)[0]?.id;if(this.live(r).length<2)this.phase(r,'finished');else if(r.phase==='mixer'&&this.live(r).every(q=>r.submissions[q.id]!==undefined||r.passes.includes(q.id)))this.mixerReveal(r);break;}p.left=true;if(p.id===r.host)r.host=this.live(r)[0]?.id;if(r.phase!=='lobby'&&r.phase!=='finished'&&r.phase!=='result'){// Cancel rather than award a disconnected opponent an unfair loss.
 for(const pid of r.active||[]){const q=r.players.find(x=>x.id===pid);q.chips+=r.stakes[pid]||0;}for(const [pid,b]of Object.entries(r.bets||{}))r.players.find(x=>x.id===pid).chips+=b.amount;r.result={winners:[],tie:true,detail:'A player left. This round was cancelled and all stakes returned.',changes:{},totals:{},answers:{},picks:{}};this.phase(r,'result');}break;
 default:throw Error('Unknown action.');}this.emit(r);}
 view(r,p){return {version:r.version||0,selectedGame:r.selectedGame,categories:r.game==='rhythm'?categories:[],physical:r.physical?{...r.physical,undo:undefined,canUndo:!!r.physical.undo.length,keeper:this.live(r).some(p=>p.id===r.physical.keeper)?r.physical.keeper:r.host}:null,canTakeover:(()=>{const h=r.players.find(q=>q.id===r.host);const seen=h?.lastSeen||h?.disconnectedAt;return r.host!==p.id&&!!seen&&Date.now()-seen>=30000;})(),clueOrder:r.game==='imposter'&&!['spin','stake','entry','ban','banResult'].includes(r.phase)?r.clueOrder||[]:[],clueIndex:r.clueIndex,cluePlayer:r.phase==='clue'?r.clueOrder[r.clueIndex]:null,category:r.game==='imposter'&&!['spin','stake','entry','ban','banResult'].includes(r.phase)?r.category:null,enabledGames:r.enabledGames||GAMES.map(g=>g.id),banEnabled:!!r.banEnabled,selectionError:r.phase==='lobby'?this.selectionError(r):null,candidates:r.candidates||[],banVoted:Object.hasOwn(r.banVotes||{},p.id),banChoice:r.banVotes?.[p.id],banCount:Object.keys(r.banVotes||{}).length,banned:r.banned||null,banTotals:r.phase==='ban'?{}:r.banTotals||{},banTie:r.banTie||false,spinOptions:r.spinOptions||[],spinAngle:r.spinAngle||0,spinStarted:r.spinStarted,mode:r.mode||'tournament',deck:r.deck,deckName:deckNames[r.deck],mixerKind:r.mixerKind,options:r.options||[],passed:r.passes?.includes(p.id)||false,responseCount:r.mode==='mixer'?Object.keys(r.submissions||{}).length+(r.passes||[]).length:0,code:r.code,phase:r.phase,round:r.round,host:r.host,you:p.id,deadline:r.deadline,spot:r.spot,game:r.game,prompt:r.prompt,players:r.players.map(({id,name,chips,left,spots,lastSeen})=>({id,name,chips,left,spots,disconnected:!!lastSeen&&Date.now()-lastSeen>=30000})),active:r.active||[],teams:r.teams||[],ladder:r.ladder,eliminated:r.eliminated||[],decision:r.decisions?.[p.id],stake:r.stakes?.[p.id]||5,stakes:['entry','stake'].includes(r.phase)?{}:r.stakes,bet:r.bets?.[p.id],submitted:r.submissions?.[p.id]!==undefined,voted:!!r.votes?.[p.id],cards:r.phase==='draft'?r.cards:[],draftPlayer:r.phase==='draft'?this.draftPlayer(r):null,draftStep:r.draftStep,picks:r.game==='draft'?r.picks:{},secret:r.game==='imposter'&&r.active.includes(p.id)&&!['spin','stake','entry','ban','banResult'].includes(r.phase)?(p.id===r.imposter?'You’re the faker':r.secret):null,answers:['clue','vote','discuss','result','finished','mixerReveal'].includes(r.phase)?r.submissions:{},result:['result','finished'].includes(r.phase)?r.result:null,history:r.phase==='finished'?r.history:[],free:r.free,voters:r.phase==='vote'?this.voters(r).map(x=>x.id):[]};}
 emit(r){r.version=(r.version||0)+1;for(const p of r.players){const streams=this.clients.get(p.token);if(streams)for(const res of streams)res.write(`data: ${JSON.stringify(this.view(r,p))}\n\n`);}}
 tick(){const now=Date.now();for(const r of this.rooms.values()){if(r.phase==='physical'&&r.physical&&!r.physical.paused){const h=r.players.find(p=>p.id===r.host);if(h?.lastSeen&&now-h.lastSeen>5000){physicalStop(r);this.emit(r);continue;}const elapsed=physicalElapsed(r,now);if(r.physical.practice&&elapsed>=7500){physicalStop(r);this.emit(r);}else if(!r.physical.practice&&r.game==='rhythm'&&elapsed>=3000+r.active.length*2*4500){physicalStop(r);this.phase(r,'physicalConfirm');this.emit(r);}}if(r.deadline&&now>=r.deadline){if(r.phase==='pitch'){this.phase(r,'vote',20);this.emit(r);}else this.advance(r);}if(now-r.last>12*3600000){for(const p of r.players)for(const res of this.clients.get(p.token)||[])res.end();this.rooms.delete(r.code);}}}
}
export function createServer(game=new Game()){
 const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');res.setHeader('Cache-Control','no-store');if(u.pathname==='/state'){const r=game.rooms.get(u.searchParams.get('code'));if(!r)throw Error('This room has expired. Start fresh or join a new room.');const p=game.player(r,u.searchParams.get('token'));p.lastSeen=Date.now();r.last=Date.now();res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify(game.view(r,p)));return;}if(u.pathname==='/info'){res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({addresses:networkAddresses()}));return;}if(u.pathname==='/events'){const r=game.rooms.get(u.searchParams.get('code')),p=r&&game.player(r,u.searchParams.get('token'));if(!p)throw Error('Room expired. Create a new room.');res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});let streams=game.clients.get(p.token);if(!streams)game.clients.set(p.token,streams=new Set());streams.add(res);p.disconnectedAt=null;res.write(`data: ${JSON.stringify(game.view(r,p))}\n\n`);req.on('close',()=>{streams.delete(res);if(!streams.size){game.clients.delete(p.token);p.disconnectedAt=Date.now();}});return;}
 if(u.pathname==='/api'&&req.method==='POST'){if(req.headers.origin&&new URL(req.headers.origin).host!==req.headers.host)throw Error('Invalid origin.');let body='';for await(const chunk of req){body+=chunk;if(body.length>120000)throw Error('Submission too large.');}const a=JSON.parse(body);let result={ok:true};if(a.type==='create')result=game.create(a.name,a.mode);else if(a.type==='join')result=game.join(a.code,a.name);else{const r=game.rooms.get(a.code);if(!r)throw Error('Room expired. Create a new room.');const player=game.player(r,a.token);player.lastSeen=Date.now();r.last=Date.now();game.action(r,player,a);result={ok:true,state:game.view(r,player)};}res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify(result));return;}
 const file={'/feedback.html':'feedback.html','/feedback.js':'feedback.js','/':'index.html','/app.js':'app.js','/state-flow.js':'state-flow.js','/catalog.js':'catalog.js','/ui.js':'ui.js','/physical-ui.js':'physical-ui.js','/game-themes.css':'game-themes.css','/style.css':'style.css','/cleanup.css':'cleanup.css','/tutorial/how-to-play.mp4':'tutorial/how-to-play.mp4','/tutorial/how-to-play.vtt':'tutorial/how-to-play.vtt','/tutorial/poster.jpg':'tutorial/poster.jpg'}[u.pathname];if(!file){res.writeHead(404);res.end('Not found');return;}const types={'html':'text/html','js':'text/javascript','css':'text/css','mp4':'video/mp4','vtt':'text/vtt; charset=utf-8','jpg':'image/jpeg'};const data=await readFile(root+file);const headers={'Content-Type':types[file.split('.').pop()],'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Length':data.length};if(file.endsWith('.mp4')){headers['Accept-Ranges']='bytes';if(req.headers.range){const match=/^bytes=(\d*)-(\d*)$/.exec(req.headers.range);let start=match?.[1]?Number(match[1]):0,end=match?.[2]?Number(match[2]):data.length-1;if(match&&!match[1]&&match[2]){start=Math.max(0,data.length-Number(match[2]));end=data.length-1;}end=Math.min(end,data.length-1);if(!match||(!match[1]&&!match[2])||!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start>end||start>=data.length){res.writeHead(416,{'Content-Range':`bytes */${data.length}`});res.end();return;}res.writeHead(206,{...headers,'Content-Range':`bytes ${start}-${end}/${data.length}`,'Content-Length':end-start+1});res.end(req.method==='HEAD'?undefined:data.subarray(start,end+1));return;}}res.writeHead(200,headers);res.end(req.method==='HEAD'?undefined:data);}catch(e){if(!res.headersSent)res.writeHead(400,{'Content-Type':'application/json'});res.end(JSON.stringify({error:e.message}));}});const timer=setInterval(()=>game.tick(),500);const heartbeat=setInterval(()=>{for(const streams of game.clients.values())for(const res of streams)res.write(': heartbeat\n\n');},15000);server.on('close',()=>{clearInterval(timer);clearInterval(heartbeat);});return server;
}
if(process.argv[1]===fileURLToPath(import.meta.url)){const port=Number(process.env.PORT||3210);createServer().listen(port,'::',()=>{console.log(`Bad Bets: http://localhost:${port}`);for(const entries of Object.values(os.networkInterfaces()))for(const n of entries||[])if(n.family==='IPv4'&&!n.internal)console.log(`Phone on same Wi-Fi: http://${n.address}:${port}`);});}
