import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Game} from './server.mjs';
function setup(n=4){const g=new Game(),a=g.create('P0'),r=g.rooms.get(a.code);r.potVersion=1; // Legacy-room migration coverage. New economy is covered in pot-test.mjs.
r.banEnabled=false;r.enabledGames=['brain','number','draft','draw','imposter'];for(let i=1;i<n;i++)g.join(a.code,`P${i}`);return {g,r,p:r.players};}
function mode(g,r,kind,spot=false){g.fresh(r);r.spot=spot;r.candidates=g.pool(r);g.choose(r);r.game=kind;r.active=r.players.map(p=>p.id);r.teams=[r.active.slice(0,2),r.active.slice(2)];g.phase(r,'play',30);}
test('rooms enforce nickname uniqueness, capacity, host control and auth',()=>{const {g,r,p}=setup(12);assert.throws(()=>g.join(r.code,'extra'));assert.throws(()=>g.player(r,'bad'));assert.throws(()=>g.action(r,p[1],{type:'start'}));g.action(r,p[0],{type:'start'});assert.throws(()=>g.join(r.code,'new'));});
test('all-in personal stakes and matching payouts settle only once',()=>{const {g,r,p}=setup();g.fresh(r);g.action(r,p[0],{type:'stake',amount:20});g.choose(r);r.game='brain';g.phase(r,'play',30);const answers=['A Hippo!','hippo','pizza','bird'];p.forEach((q,i)=>g.action(r,q,{type:'submit',value:answers[i]}));assert.equal(r.phase,'result');assert.equal(p[0].chips,120);assert.equal(p[1].chips,105);assert.equal(p[2].chips,95);g.settle(r);assert.equal(p[0].chips,120);});
test('private answers, secret role and tokens never leak',()=>{const {g,r,p}=setup();mode(g,r,'imposter');r.imposter=p[0].id;r.secret='Airport';r.submissions[p[1].id]='plane';const v=g.view(r,p[2]);assert.deepEqual(v.answers,{});assert.equal(v.secret,'Airport');assert.equal(JSON.stringify(v).includes(p[0].token),false);assert.equal(g.view(r,p[0]).secret,'You’re the imposter');assert.equal('imposter' in v,false);});
test('entry ladder folds into audience without charges and fallback is free',()=>{const {g,r,p}=setup(8);g.fresh(r);r.spot=true;r.candidates=g.pool(r);g.phase(r,'entry',15);p.forEach(q=>g.action(r,q,{type:'entry',stay:true}));g.advance(r);assert.equal(r.ladder,10);g.action(r,p[0],{type:'entry',stay:false});assert.equal(p[0].chips,100);g.advance(r);assert.equal(r.phase,'spin');assert.equal(r.free,true);assert.ok(p.every(q=>q.chips===100));});
test('capped ladder selects compatible teams and deducts only participants',()=>{const {g,r,p}=setup(8);g.fresh(r);r.spot=true;r.candidates=g.pool(r);g.phase(r,'entry',15);for(let i=0;i<3;i++){p.forEach(q=>g.action(r,q,{type:'entry',stay:true}));g.advance(r);}assert.equal(r.phase,'spin');assert.equal(r.ladder,20);assert.ok([2,4,6,8].includes(r.active.length));for(const q of p)assert.equal(q.chips,r.active.includes(q.id)?80:100);});
test('judges cannot wager; contestants cannot vote; votes lock',()=>{const {g,r,p}=setup();g.fresh(r);r.spot=true;r.candidates=g.pool(r);g.choose(r);r.game='draw';r.active=[p[0].id,p[1].id];g.phase(r,'reveal',8);assert.throws(()=>g.action(r,p[2],{type:'bet',team:0}));g.phase(r,'vote',20);assert.throws(()=>g.action(r,p[0],{type:'vote',player:p[1].id}));g.action(r,p[2],{type:'vote',player:p[0].id});assert.throws(()=>g.action(r,p[2],{type:'vote',player:p[1].id}));g.action(r,p[3],{type:'vote',player:p[1].id});assert.equal(r.result.tie,true);});
test('objective audience side bets lock before play and settle correctly',()=>{const {g,r,p}=setup(3);g.fresh(r);r.spot=true;r.candidates=g.pool(r);g.choose(r);r.game='number';// Normalize fixture balances after random mode selection.
 p.forEach(q=>q.chips=100);r.active=[p[0].id,p[1].id];r.teams=[[p[0].id],[p[1].id]];r.answer=50;r.stakes={[p[0].id]:5,[p[1].id]:5};p[0].chips=p[1].chips=95;g.phase(r,'reveal',8);g.action(r,p[2],{type:'bet',team:0});assert.equal(p[2].chips,95);assert.throws(()=>g.action(r,p[2],{type:'bet',team:1}));g.begin(r);assert.throws(()=>g.action(r,p[2],{type:'bet',team:1}));g.action(r,p[0],{type:'submit',value:49});g.action(r,p[1],{type:'submit',value:70});assert.equal(p[0].chips,105);assert.equal(p[1].chips,95);assert.equal(p[2].chips,105);});
test('invalid numbers, duplicate answers and spectators are rejected',()=>{const {g,r,p}=setup();mode(g,r,'number');r.active=p.slice(0,2).map(x=>x.id);assert.throws(()=>g.action(r,p[2],{type:'submit',value:10}));assert.throws(()=>g.action(r,p[0],{type:'submit',value:'no'}));g.action(r,p[0],{type:'submit',value:10});assert.throws(()=>g.action(r,p[0],{type:'submit',value:20}));});
test('leaving refunds stakes and hands host to next player',()=>{const {g,r,p}=setup();g.fresh(r);g.choose(r);g.action(r,p[0],{type:'leave'});assert.equal(p[0].chips,95);assert.ok(p.slice(1).every(q=>q.chips===100));assert.equal(r.phase,'result');assert.equal(r.host,p[1].id);});
test('draft makes four exclusive picks per player and times out to voting',()=>{const {g,r,p}=setup();mode(g,r,'draft',true);r.active=p.slice(0,2).map(x=>x.id);r.picks=Object.fromEntries(r.active.map(pid=>[pid,[]]));r.cards=['A','B'];r.draftStep=0;r.draftTurn=0;g.phase(r,'draft',15);for(let i=0;i<8;i++)g.advance(r);assert.equal(r.phase,'pitch');assert.equal(r.picks[p[0].id].length,4);assert.equal(r.picks[p[1].id].length,4);r.deadline=1;g.tick();assert.equal(r.phase,'vote');});
test('full nine-round sessions progress for 2 through 8 players',()=>{for(let n=2;n<=8;n++){const {g,r,p}=setup(n);g.action(r,p[0],{type:'start'});for(let round=1;round<=9;round++){assert.equal(r.round,round);let guard=0;while(r.phase!=='result'){assert.ok(guard++<30);if(r.phase==='entry'){for(const q of p)if(!r.eliminated.includes(q.id))g.action(r,q,{type:'entry',stay:true});}if(r.phase==='play'){for(const q of p.filter(q=>r.active.includes(q.id))){const value=r.game==='number'?10:r.game==='draw'?'data:image/png;base64,abc':'pizza';if(r.phase==='play')g.action(r,q,{type:'submit',value});}continue;}r.deadline=1;g.tick();}assert.ok(p.every(q=>q.chips>=0));g.action(r,p[0],{type:'next'});}assert.equal(r.phase,'finished');g.action(r,p[0],{type:'rematch'});assert.equal(r.phase,'lobby');assert.ok(p.every(q=>q.chips===100));}});
test('host takeover respects reconnect grace period',()=>{const {g,r,p}=setup();assert.throws(()=>g.action(r,p[1],{type:'takeover'}));p[0].disconnectedAt=Date.now();assert.throws(()=>g.action(r,p[1],{type:'takeover'}));p[0].disconnectedAt=Date.now()-31000;p[0].lastSeen=p[0].disconnectedAt;g.action(r,p[1],{type:'takeover'});assert.equal(r.host,p[1].id);});
test('late actions are rejected at the server deadline',()=>{const {g,r,p}=setup();g.fresh(r);r.deadline=Date.now()-1;assert.throws(()=>g.action(r,p[0],{type:'stake',amount:20}),/Time is up/);assert.equal(r.phase,'spin');});
test('mixer preserves chips, hides responses until reveal, allows free passes and completes',()=>{const {g,r,p}=setup();g.action(r,p[0],{type:'configure',mode:'mixer',deck:'ice'});g.action(r,p[0],{type:'start'});for(let i=1;i<=12;i++){assert.equal(r.phase,'mixer');assert.equal(r.round,i);g.action(r,p[0],{type:'mixerAnswer',value:r.options[0]||'My answer'});assert.deepEqual(g.view(r,p[1]).answers,{});for(const q of p.slice(1))g.action(r,q,{type:'mixerAnswer',pass:true});assert.equal(r.phase,'mixerReveal');assert.equal(Object.keys(g.view(r,p[1]).answers).length,1);g.action(r,p[0],{type:'mixerNext'});}assert.equal(r.phase,'finished');assert.ok(p.every(q=>q.chips===100));assert.ok(r.history.every(h=>!('answers' in h)));});
test('mixer deck controls require host; any player may swap; stale swap rejected',()=>{const {g,r,p}=setup(2);assert.throws(()=>g.action(r,p[1],{type:'configure',mode:'mixer',deck:'date'}));g.action(r,p[0],{type:'configure',mode:'mixer',deck:'date'});g.action(r,p[0],{type:'start'});g.action(r,p[1],{type:'mixerSkip',round:1});assert.equal(r.round,2);assert.throws(()=>g.action(r,p[0],{type:'mixerSkip',round:1}));g.action(r,p[0],{type:'leave'});assert.equal(r.phase,'finished');assert.equal(r.host,p[1].id);});
test('matching reserved object keys does not crash scoring',()=>{const {g,r,p}=setup(2);g.fresh(r);g.choose(r);r.game='brain';g.phase(r,'play',30);for(const q of p)g.action(r,q,{type:'submit',value:'constructor'});assert.equal(r.phase,'result');assert.ok(p.every(q=>q.chips===105));});
test('host game pool filters both formats and blocks an impossible start',()=>{const {g,r,p}=setup(2);assert.throws(()=>g.action(r,p[1],{type:'toggleGame',game:'number'}));g.action(r,p[0],{type:'toggleGame',game:'number'});assert.match(g.selectionError(r),/spotlight/);assert.throws(()=>g.action(r,p[0],{type:'start'}),/spotlight/);g.action(r,p[0],{type:'toggleGame',game:'number'});g.action(r,p[0],{type:'toggleGame',game:'brain'});g.action(r,p[0],{type:'start'});assert.deepEqual(r.candidates,['number']);g.advance(r);assert.equal(r.game,'number');assert.deepEqual(r.spinOptions,['number']);});
test('ban votes stay private, lock, and remove a game before wagers',()=>{const {g,r,p}=setup();r.banEnabled=true;g.action(r,p[0],{type:'start'});assert.equal(r.phase,'ban');assert.equal(r.game,null);assert.ok(p.every(q=>q.chips===100));g.action(r,p[0],{type:'banVote',game:'number',round:1});assert.deepEqual(g.view(r,p[1]).banTotals,{});assert.equal(g.view(r,p[1]).banChoice,undefined);assert.throws(()=>g.action(r,p[0],{type:'banVote',game:'brain'}));assert.throws(()=>g.action(r,p[1],{type:'banVote',game:'draw'}));for(const q of p.slice(1))g.action(r,q,{type:'banVote',game:'number'});assert.equal(r.phase,'banResult');assert.equal(r.banned,'number');assert.deepEqual(r.candidates,['brain','imposter']);g.advance(r);assert.equal(r.phase,'stake');g.advance(r);assert.equal(r.phase,'spin');assert.ok(!r.spinOptions.includes('number'));assert.notEqual(r.game,'number');g.advance(r);assert.equal(r.phase,'reveal');assert.throws(()=>g.action(r,p[1],{type:'banVote',game:'brain'}));});
test('ban abstention preserves the pool; a tied vote removes exactly one tied game',()=>{const {g,r,p}=setup();r.banEnabled=true;g.fresh(r);for(const q of p)g.action(r,q,{type:'banVote',game:null});assert.equal(r.banned,null);assert.equal(r.candidates.length,3);g.fresh(r);g.action(r,p[0],{type:'banVote',game:'brain'});g.action(r,p[1],{type:'banVote',game:'number'});g.action(r,p[2],{type:'banVote',game:null});g.action(r,p[3],{type:'banVote',game:null});assert.ok(['brain','number'].includes(r.banned));assert.equal(r.banTie,true);assert.equal(r.candidates.length,2);});
test('small pools skip bans, disabled games never return, bans reset next round',()=>{const {g,r,p}=setup();r.banEnabled=true;r.enabledGames=['brain','number','draw'];g.fresh(r);assert.equal(r.phase,'stake');assert.deepEqual(r.candidates,['brain','number']);r.banned='number';r.candidates=['brain'];g.choose(r);assert.equal(r.game,'brain');g.fresh(r);assert.equal(r.banned,null);assert.deepEqual(r.candidates,['brain','number']);r.round=2;g.fresh(r);assert.equal(r.spot,true);assert.deepEqual(r.candidates,['number','draw']);});
test('wheel landing angle points to server winner and secret roles stay hidden while spinning',()=>{const {g,r,p}=setup(8);for(let i=0;i<12;i++){g.fresh(r);g.choose(r);assert.equal(r.phase,'spin');const winner=r.spinOptions.indexOf(r.game),segment=360/r.spinOptions.length;const midpoint=(winner+.5)*segment;assert.ok(Math.abs((midpoint+r.spinAngle)%360)<.00001);assert.ok(g.view(r,p[0]).secret===null);assert.ok(r.enabledGames.includes(r.game));}});
test('full tournament supports enabled ban voting without stalling',()=>{const {g,r,p}=setup(8);r.banEnabled=true;g.action(r,p[0],{type:'start'});for(let round=1;round<=9;round++){let guard=0;while(r.phase!=='result'){assert.ok(guard++<35);if(r.phase==='ban'){for(const q of p)g.action(r,q,{type:'banVote',game:r.candidates[0]});continue;}if(r.phase==='entry')p.forEach(q=>g.action(r,q,{type:'entry',stay:true}));r.deadline=1;g.tick();}g.action(r,p[0],{type:'next'});}assert.equal(r.phase,'finished');assert.ok(p.every(q=>Number.isFinite(q.chips)&&q.chips>=0));});

test('faker gets only a category, clues follow a shuffled turn order, and others cannot submit early',()=>{
 const {g,r,p}=setup(4);g.fresh(r);r.candidates=['imposter'];g.choose(r);g.advance(r);
 assert.ok(g.view(r,p[0]).category);const faker=p.find(q=>q.id===r.imposter);
 assert.equal(g.view(r,faker).secret,'You’re the imposter');assert.equal(JSON.stringify(g.view(r,faker)).includes(r.secret),false);
 g.begin(r);assert.equal(r.phase,'clue');assert.equal(new Set(r.clueOrder).size,4);
 assert.throws(()=>g.action(r,p.find(q=>q.id!==r.clueOrder[0]),{type:'clue',clueIndex:0,value:'clue'}),/turn/);
 const first=p.find(q=>q.id===r.clueOrder[0]);g.action(r,first,{type:'clue',clueIndex:0,value:'something'});
 assert.equal(g.view(r,faker).answers[first.id],'something');
 assert.throws(()=>g.action(r,p.find(q=>q.id===r.clueOrder[1]),{type:'clue',clueIndex:0,value:'late'}),/ended/);
 for(let i=1;i<4;i++){g.action(r,p.find(q=>q.id===r.clueOrder[i]),{type:'clue',clueIndex:i,value:'different'});}
 assert.equal(r.phase,'discuss');g.advance(r);assert.equal(r.phase,'vote');
 for(const q of p){if(r.phase==='vote')g.action(r,q,{type:'vote',player:q.id===r.imposter?p.find(x=>x!==q).id:r.imposter});}
 assert.equal(r.phase,'result');assert.equal(r.result.winners.includes(faker.id),false);
});
test('faker rotates through the group and silent rounds refund all stakes',()=>{
 const {g,r,p}=setup(4),roles=[];
 for(let i=0;i<4;i++){g.fresh(r);r.spot=false;r.candidates=['imposter'];g.choose(r);roles.push(r.imposter);g.begin(r);for(let n=0;n<4;n++)g.advance(r);assert.equal(r.phase,'result');assert.equal(r.result.tie,true);assert.ok(p.every(q=>q.chips===100));}
 assert.equal(new Set(roles).size,4);
});
test('clue timeouts skip one turn and never reveal the word to the imposter',()=>{
 const {g,r,p}=setup();g.fresh(r);r.candidates=['imposter'];g.choose(r);g.begin(r);
 const before=r.cluePlayer;g.advance(r);assert.equal(r.clueIndex,1);assert.equal(r.phase,'clue');
 const q=p.find(q=>q.id===r.clueOrder[1]);g.action(r,q,{type:'clue',clueIndex:1,value:'hint'});
 g.advance(r);g.advance(r);assert.equal(r.phase,'discuss');assert.equal(g.view(r,p.find(q=>q.id===r.imposter)).secret,'You’re the imposter');
 g.advance(r);g.advance(r);assert.equal(r.result.tie,true);
});
test('host takeover is shown only after a real disconnect grace period',()=>{
 const {g,r,p}=setup();p[0].lastSeen=Date.now();assert.equal(g.view(r,p[1]).canTakeover,false);
 p[0].lastSeen=Date.now()-31000;assert.equal(g.view(r,p[1]).canTakeover,true);assert.equal(g.view(r,p[0]).canTakeover,false);
});

function physicalSetup(kind,n=4,mini=true){const {g,r,p}=setup(n);r.mode=mini?'minigames':'tournament';r.selectedGame=kind;r.enabledGames=[kind];if(!mini){g.fresh(r);r.spot=kind==='shadow';r.candidates=[kind];g.choose(r);}else g.action(r,p[0],{type:'start'});g.begin(r);return {g,r,p,do:(who,type,extra={})=>g.action(r,who,{type,revision:r.physical.revision,...extra})};}
test('minigames skips wagers and allows replay and another game without changing chips',()=>{const {g,r,p}=setup();r.mode='minigames';r.selectedGame='brain';g.action(r,p[0],{type:'start'});assert.equal(r.phase,'reveal');assert.ok(p.every(x=>x.chips===100));g.begin(r);for(const q of p)g.action(r,q,{type:'submit',value:'cat'});assert.equal(r.phase,'result');assert.ok(p.every(x=>x.chips===100));g.action(r,p[0],{type:'replay'});assert.equal(r.game,'brain');g.begin(r);g.settle(r);g.action(r,p[0],{type:'lobby'});g.action(r,p[0],{type:'selectGame',game:'shadow'});g.action(r,p[0],{type:'start'});assert.equal(r.game,'shadow');assert.equal(r.active.length,2);assert.ok(p.every(x=>x.chips===100));assert.throws(()=>g.action(r,p[2],{type:'bet',team:0}));});
test('minigame host validates player counts and can select a game disabled in party mode',()=>{const {g,r,p}=setup(2);r.mode='minigames';r.enabledGames=['number'];assert.throws(()=>g.action(r,p[0],{type:'selectGame',game:'imposter'}));assert.throws(()=>g.action(r,p[1],{type:'selectGame',game:'shadow'}));g.action(r,p[0],{type:'selectGame',game:'brain'});g.action(r,p[0],{type:'start'});assert.equal(r.game,'brain');});
test('shadowbox confirms both players before payout, protects score changes and stale requests',()=>{const x=physicalSetup('shadow',4,false),{g,r,p}=x;const active=r.active.map(id=>p.find(q=>q.id===id)),keeper=p.find(q=>q.id===r.physical.keeper);x.do(p[0],'physicalStart');assert.throws(()=>x.do(active.find(q=>q.id!==r.host),'physicalScore',{player:active[0].id,delta:1}));const revision=r.physical.revision;x.do(keeper,'physicalScore',{player:active[0].id,delta:1});assert.throws(()=>g.action(r,keeper,{type:'physicalScore',revision,player:active[0].id,delta:1}));x.do(keeper,'physicalDodge');x.do(keeper,'physicalUndo');for(let i=0;i<2;i++)x.do(keeper,'physicalScore',{player:active[0].id,delta:1});assert.equal(r.phase,'physicalConfirm');const before=active[0].chips;x.do(active[0],'physicalConfirm');assert.equal(active[0].chips,before);x.do(active[1],'physicalConfirm');assert.equal(r.phase,'result');assert.equal(active[0].chips,before+10);assert.throws(()=>x.do(keeper,'physicalScore',{player:active[0].id,delta:1}));});
test('rhythm supports custom categories, practice, pause, two laps and confirmed ties',()=>{const x=physicalSetup('rhythm'),{g,r,p}=x;assert.throws(()=>x.do(p[0],'physicalStart'));x.do(p[0],'physicalCategory',{value:'US states'});assert.equal(r.prompt,'US states');x.do(p[0],'physicalStart',{practice:true});assert.throws(()=>x.do(p[0],'physicalScore',{player:p[1].id,delta:1}));r.physical.started=Date.now()-8000;g.tick();assert.equal(r.physical.paused,true);x.do(p[0],'physicalStart');assert.equal(r.physical.practice,false);x.do(p[1],'physicalPause');assert.equal(r.physical.paused,true);x.do(p[0],'physicalStart');r.physical.started=Date.now()-40000;g.tick();assert.equal(r.phase,'physicalConfirm');for(const q of p)x.do(q,'physicalConfirm');assert.equal(r.phase,'result');assert.equal(r.result.tie,true);assert.ok(p.every(q=>q.chips===100));});
test('disputes clear confirmations and leaving a physical round refunds stakes',()=>{const x=physicalSetup('shadow',2,false),{g,r,p}=x;x.do(p[0],'physicalStart');for(let i=0;i<3;i++)x.do(p[0],'physicalScore',{player:p[0].id,delta:1});x.do(p[0],'physicalConfirm');x.do(p[1],'physicalDispute');assert.deepEqual(r.physical.confirmed,[]);assert.equal(r.phase,'physicalDispute');assert.equal(r.physical.paused,true);g.action(r,p[1],{type:'leave'});assert.equal(r.phase,'result');assert.equal(p[0].chips,100);assert.equal(p[1].chips,95);});
test('all seven games can complete in standalone mode for compatible groups',()=>{for(const kind of ['brain','number','draft','draw','imposter','shadow','rhythm']){const {g,r,p}=setup(4);r.mode='minigames';r.selectedGame=kind;const balances=p.map(q=>q.chips);g.action(r,p[0],{type:'start'});let guard=0;while(r.phase!=='result'){assert.ok(guard++<40,kind+' stalled at '+r.phase);if(r.phase==='physicalSetup'){if(kind==='rhythm')g.action(r,p[0],{type:'physicalCategory',random:true,revision:r.physical.revision});g.action(r,p[0],{type:'physicalStart',revision:r.physical.revision});}else if(r.phase==='physical'){g.action(r,p[0],{type:'physicalFinish',revision:r.physical.revision});}else if(r.phase==='physicalConfirm'){for(const pid of r.active)g.action(r,p.find(q=>q.id===pid),{type:'physicalConfirm',revision:r.physical.revision});}else if(r.phase==='pitch'){g.phase(r,'vote',20);}else g.advance(r);}assert.deepEqual(p.map(q=>q.chips),balances,kind+' changed chips');g.action(r,p[0],{type:'lobby'});assert.equal(r.phase,'lobby');}});
test('switching from minigames to party mode resets the session',()=>{const {g,r,p}=setup();r.mode='minigames';r.round=5;r.history=[{}];p[0].chips=80;g.action(r,p[0],{type:'mode',mode:'tournament'});assert.equal(r.round,0);assert.deepEqual(r.history,[]);assert.equal(p[0].chips,100);g.action(r,p[0],{type:'start'});assert.equal(r.round,1);});
test('host can recover an abandoned confirmation only after disconnect grace period',()=>{const x=physicalSetup('shadow',2,false),{g,r,p}=x;x.do(p[0],'physicalStart');assert.throws(()=>g.action(r,p[0],{type:'removeDisconnected',player:p[1].id}));p[1].lastSeen=Date.now()-31000;g.action(r,p[0],{type:'removeDisconnected',player:p[1].id});assert.equal(r.phase,'result');assert.equal(p[1].left,true);assert.ok(p.every(q=>q.chips===100));});
test('nine-round party sessions with only physical games finish for two through eight players',()=>{for(let n=2;n<=8;n++){const {g,r,p}=setup(n);r.enabledGames=['rhythm','shadow'];g.action(r,p[0],{type:'start'});for(let round=1;round<=9;round++){if(r.phase==='entry')for(const q of p)g.action(r,q,{type:'entry',stay:true});let guard=0;while(r.phase!=='result'){assert.ok(guard++<30);if(r.phase==='entry')for(const q of p.filter(q=>!r.eliminated.includes(q.id)))g.action(r,q,{type:'entry',stay:true});if(r.phase==='physicalSetup'){if(r.game==='rhythm')g.action(r,p[0],{type:'physicalCategory',value:'States',revision:r.physical.revision});g.action(r,p[0],{type:'physicalStart',revision:r.physical.revision});}else if(r.phase==='physical')g.action(r,p[0],{type:'physicalFinish',revision:r.physical.revision});else if(r.phase==='physicalConfirm'){const revision=r.physical.revision;for(const pid of r.active)g.action(r,p.find(q=>q.id===pid),{type:'physicalConfirm',revision});}else g.advance(r);}g.action(r,p[0],{type:'next'});}assert.equal(r.phase,'finished');assert.ok(p.every(q=>Number.isFinite(q.chips)));}});

test('host round count is validated, shared and ends at the selected round',()=>{for(const rounds of [3,6,9,12,15]){const {g,r,p}=setup();assert.throws(()=>g.action(r,p[1],{type:'roundCount',rounds}));for(const invalid of [0,4,99,'6',null])assert.throws(()=>g.action(r,p[0],{type:'roundCount',rounds:invalid}));g.action(r,p[0],{type:'roundCount',rounds});assert.equal(g.view(r,p[1]).totalRounds,rounds);r.round=rounds-1;g.phase(r,'result');g.action(r,p[0],{type:'next'});assert.equal(r.round,rounds);assert.notEqual(r.phase,'finished');assert.throws(()=>g.action(r,p[0],{type:'roundCount',rounds:3}));g.phase(r,'result');g.action(r,p[0],{type:'next'});assert.equal(r.phase,'finished');g.action(r,p[0],{type:'rematch'});assert.equal(r.totalRounds,rounds);}});

test('Date Night progresses by depth with mutual consent and no stored answers',()=>{
 const {g,r,p}=setup(2);g.action(r,p[0],{type:'configure',mode:'mixer',deck:'date'});g.action(r,p[0],{type:'start'});
 assert.equal(r.mixerDeck.length,36);assert.equal(g.view(r,p[0]).dateFirst,p[0].id);
 assert.throws(()=>g.action(r,p[0],{type:'mixerAnswer',value:'private personal story'}),/out loud/);
 assert.throws(()=>g.action(r,p[0],{type:'mixerReveal'}),/Both/);
 for(let n=1;n<=12;n++){assert.equal(r.round,n);g.action(r,p[0],{type:'mixerSkip',round:n});}
 assert.equal(r.phase,'dateCheck');g.action(r,p[0],{type:'dateReady'});g.action(r,p[0],{type:'dateReady'});assert.equal(r.phase,'dateCheck');
 g.action(r,p[1],{type:'dateReady'});assert.equal(r.round,13);assert.equal(r.phase,'mixer');
 for(let n=13;n<=24;n++)g.action(r,p[1],{type:'mixerSkip',round:n});
 assert.equal(r.phase,'dateCheck');p.forEach(q=>g.action(r,q,{type:'dateReady'}));
 for(let n=25;n<=36;n++)g.action(r,p[1],{type:'mixerSkip',round:n});
 assert.equal(r.phase,'finished');assert.ok(p.every(q=>q.chips===100));
});
test('Date Night can be created directly, requires two, and either partner can end',()=>{
 const g=new Game(),a=g.create('A','mixer'),r=g.rooms.get(a.code);assert.equal(r.deck,'date');g.join(r.code,'B');g.join(r.code,'C');assert.throws(()=>g.action(r,r.players[0],{type:'start'}),/two/);
 g.action(r,r.players[2],{type:'leave'});g.phase(r,'lobby');g.action(r,r.players[0],{type:'start'});g.action(r,r.players[1],{type:'mixerEnd'});assert.equal(r.phase,'finished');
});
test('Date Night keep it light: either partner can stay light, no more depth checks',()=>{
 const {g,r,p}=setup(2);g.action(r,p[0],{type:'configure',mode:'mixer',deck:'date'});g.action(r,p[0],{type:'start'});
 const firstTwelve=r.mixerDeck.slice(0,12).map(c=>c[1]);
 for(let n=1;n<=12;n++)g.action(r,p[0],{type:'mixerSkip',round:n});
 assert.equal(r.phase,'dateCheck');g.action(r,p[0],{type:'dateReady'});
 g.action(r,p[1],{type:'dateLight'});
 assert.equal(r.round,13);assert.equal(r.phase,'mixer');assert.equal(r.mixerDeck.length,24);
 assert.deepEqual(r.mixerDeck.slice(0,12).map(c=>c[1]),firstTwelve);
 const v=g.view(r,p[0]);assert.equal(v.dateLevel,'Keep it light');assert.equal(v.mixerTotal,24);
 assert.ok(r.mixerDeck.slice(12).every(c=>typeof c[1]==='string'&&!c[2]));
 assert.ok(r.mixerDeck.slice(12).some(c=>/ or .+\?$/.test(c[1])),'either/or options are spoken in the prompt');
 for(let n=13;n<=24;n++){assert.notEqual(r.phase,'dateCheck');g.action(r,p[1],{type:'mixerSkip',round:n});}
 assert.equal(r.phase,'finished');assert.ok(p.every(q=>q.chips===100));
});
test('12-player cap and per-game everyone-plays limits',async()=>{const {fitsAll,gameById,MAX_PLAYERS}=await import('./public/catalog.js');assert.equal(MAX_PLAYERS,12);assert.ok(fitsAll(gameById('brain'),12));assert.ok(!fitsAll(gameById('draft'),9));assert.ok(fitsAll(gameById('draft'),8));assert.ok(fitsAll(gameById('draw'),10));assert.ok(!fitsAll(gameById('draw'),11));assert.ok(!fitsAll(gameById('imposter'),3));const {g,r}=setup(12);assert.throws(()=>g.join(r.code,'thirteen'),/12 players/);});
test('new rooms start with the skip vote off',()=>{const g=new Game(),a=g.create('Host');assert.equal(g.rooms.get(a.code).banEnabled,false);});
