// Theme content for Fantasy Draft and Bidding War. Content only, no game logic.
// The engine reads this through the theme layer. "food" is built into the engine
// from the existing food cards and restaurants, so it is not listed here.
//
// DRAFT_THEMES[id] = {
//   name, blurb,                         // shown in the theme picker
//   icon: 'theme-<id>',                  // /art/theme-<id>.svg
//   slots: [{ id, label }],              // 4 or 5 slots, label like "a getaway driver"
//   cards: { <slotId>: [16 short items] },
//   prompts: [8 build prompts]           // e.g. "Build the heist crew that actually gets away"
// }
// AUCTION_THEMES[id] = {
//   name, blurb, icon: 'theme-<id>',
//   slots: [{ id, label }],              // what each winning bid fills
//   lots: [20 short names],              // what players bid on
//   nameItem: false,                     // true = winner types what they take from the lot (like food)
//   itemPrompt: '',                      // shown when nameItem is true, may use {lot}
//   prompts: [6 pitch prompts]
// }
export const DRAFT_THEMES = {
 "vacation": {
  "name": "Dream Vacation",
  "blurb": "Draft the trip of a lifetime, or a total disaster.",
  "icon": "theme-vacation",
  "slots": [
   {
    "id": "destination",
    "label": "a destination"
   },
   {
    "id": "stay",
    "label": "a place to stay"
   },
   {
    "id": "activity",
    "label": "an activity"
   },
   {
    "id": "buddy",
    "label": "a travel buddy"
   }
  ],
  "cards": {
   "destination": [
    "Tokyo",
    "Paris",
    "Hawaii",
    "The Moon",
    "Grandma's House",
    "Iceland",
    "A Water Park",
    "Antarctica",
    "Las Vegas",
    "The Grand Canyon",
    "A Cruise Ship",
    "A Tiny Island",
    "Your Own Backyard",
    "Rome",
    "A Gas Station",
    "Mount Everest"
   ],
   "stay": [
    "Five-Star Hotel",
    "Treehouse",
    "Igloo",
    "Tent in the Rain",
    "Castle",
    "Houseboat",
    "Your Car",
    "Bunk Bed Hostel",
    "Beach Hut",
    "Haunted Inn",
    "Cousin's Couch",
    "Airport Bench",
    "Luxury Yacht",
    "Cabin in the Woods",
    "Underwater Hotel",
    "Space Station"
   ],
   "activity": [
    "Surfing Lessons",
    "Skydiving",
    "Museum Tour",
    "Napping All Day",
    "Swimming with Sharks",
    "Hot Air Balloon Ride",
    "Karaoke Night",
    "Zip Lining",
    "Sandcastle Contest",
    "Counting Pigeons",
    "Volcano Hike",
    "Theme Park Rides",
    "Waiting in Line",
    "Cooking Class",
    "Whale Watching",
    "Buying Fridge Magnets"
   ],
   "buddy": [
    "Your Best Friend",
    "Your Grandpa",
    "A Golden Retriever",
    "A Tour Guide",
    "Your Little Cousin",
    "A Pirate",
    "A Talking Parrot",
    "A Famous Chef",
    "Your Gym Teacher",
    "A Mime",
    "A Lifeguard",
    "A Robot Butler",
    "A Sleepy Koala",
    "A Movie Star",
    "Someone Who Snores",
    "Your Mom"
   ]
  },
  "prompts": [
   "Build the vacation everyone will want to hear about.",
   "Build the trip that makes the best photos.",
   "Build the most relaxing week ever.",
   "Build the vacation with the best story afterward.",
   "Build the trip you could survive with zero money.",
   "Build the perfect family vacation.",
   "Build the trip that would make your boss jealous.",
   "Build the vacation you would actually go on tomorrow."
  ]
 },
 "heist": {
  "name": "Heist Crew",
  "blurb": "Pick a crew and plan the getaway.",
  "icon": "theme-heist",
  "slots": [
   {
    "id": "driver",
    "label": "a getaway driver"
   },
   {
    "id": "hacker",
    "label": "a hacker"
   },
   {
    "id": "disguise",
    "label": "a disguise"
   },
   {
    "id": "ride",
    "label": "a getaway ride"
   }
  ],
  "cards": {
   "driver": [
    "Stunt Driver",
    "Your Grandma",
    "Race Car Pro",
    "Taxi Driver",
    "Lost Tourist",
    "Bus Driver",
    "Ice Cream Truck Guy",
    "A Cat",
    "Getaway Expert",
    "Student Driver",
    "Pizza Delivery Guy",
    "Retired Racer",
    "A Toddler",
    "Rally Champion",
    "Bumper Car Kid",
    "Someone Who Brakes Early"
   ],
   "hacker": [
    "Teen Genius",
    "Grandpa with Email",
    "Laptop Wizard",
    "Hoodie Kid",
    "Tech Support Guy",
    "A Smart Fridge",
    "Pro Gamer",
    "Chess Champion",
    "Password Guesser",
    "A Very Smart Dog",
    "Math Teacher",
    "Satellite Expert",
    "Keyboard Smasher",
    "Coding Camp Grad",
    "Movie Hacker",
    "Someone Who Types Fast"
   ],
   "disguise": [
    "Fake Mustache",
    "Tuxedo",
    "Guard Uniform",
    "Chicken Costume",
    "Big Sunglasses",
    "Delivery Uniform",
    "Trench Coat",
    "Clown Suit",
    "Potted Plant",
    "Fancy Ball Gown",
    "Kids Stacked in Coat",
    "Paper Bag Mask",
    "Janitor Outfit",
    "Wedding Dress",
    "Astronaut Suit",
    "Just a Name Tag"
   ],
   "ride": [
    "Sports Car",
    "Motorcycle",
    "Tandem Bike",
    "Helicopter",
    "Hot Air Balloon",
    "Speedboat",
    "Garbage Truck",
    "Horse",
    "Skateboard",
    "Minivan",
    "Shopping Cart",
    "Monster Truck",
    "City Bus",
    "Jet Ski",
    "Golf Cart",
    "Rowboat"
   ]
  },
  "prompts": [
   "Build the heist crew that actually gets away.",
   "Build the crew that could rob a museum at noon.",
   "Build the sneakiest crew in town.",
   "Build the crew most likely to get caught in five minutes.",
   "Build the crew that steals the last slice of pizza.",
   "Build the crew that would make the best movie.",
   "Build the crew you trust with your secret.",
   "Build the crew that pulls it off with style."
  ]
 },
 "zombie": {
  "name": "Zombie Survival",
  "blurb": "Gear up and see who lasts the night.",
  "icon": "theme-zombie",
  "slots": [
   {
    "id": "weapon",
    "label": "a weapon"
   },
   {
    "id": "hideout",
    "label": "a hideout"
   },
   {
    "id": "snack",
    "label": "a snack"
   },
   {
    "id": "sidekick",
    "label": "a sidekick"
   }
  ],
  "cards": {
   "weapon": [
    "Baseball Bat",
    "Frying Pan",
    "Garden Rake",
    "Leaf Blower",
    "Pool Noodle",
    "Crossbow",
    "Katana",
    "Rubber Chicken",
    "Fire Extinguisher",
    "Hockey Stick",
    "Squirt Gun",
    "Golf Club",
    "Umbrella",
    "Shovel",
    "Tennis Racket",
    "Rolled-Up Magazine"
   ],
   "hideout": [
    "Shopping Mall",
    "Lighthouse",
    "School Gym",
    "Treehouse",
    "Houseboat",
    "Old Prison",
    "Bowling Alley",
    "Army Base",
    "Movie Theater",
    "Grandma's Attic",
    "Porta Potty",
    "Castle",
    "Farmhouse",
    "Bank Vault",
    "Ferris Wheel",
    "Library"
   ],
   "snack": [
    "Canned Beans",
    "Beef Jerky",
    "Twinkies",
    "Granola Bar",
    "Peanut Butter Jar",
    "Spam",
    "Instant Noodles",
    "Hot Sauce Packets",
    "Dry Cereal",
    "Birthday Cake",
    "Pickles",
    "Trail Mix",
    "Ice Pop",
    "Crackers",
    "Gummy Bears",
    "One Sad Carrot"
   ],
   "sidekick": [
    "Loyal Dog",
    "Army Medic",
    "Your Grandma",
    "Farmer with a Truck",
    "Scared Mall Cop",
    "Park Ranger",
    "A Toddler",
    "Martial Arts Master",
    "Know-It-All Nerd",
    "Cat Who Ignores You",
    "Nurse",
    "Scout Troop",
    "Friendly Zombie",
    "Pizza Chef",
    "Chatty Parrot",
    "Retired Wrestler"
   ]
  },
  "prompts": [
   "Build the team that survives the first night.",
   "Build the loadout that lasts a whole year.",
   "Build the setup that makes zombies turn around.",
   "Build the survival plan with the most style.",
   "Build the team that throws the best end-of-world party.",
   "Build the plan most likely to fail in one hour.",
   "Build the setup you would bet your life on.",
   "Build the team that saves the whole town."
  ]
 },
 "hoops": {
  "name": "Starting Five",
  "blurb": "Stars, legends and cult heroes from any era.",
  "icon": "theme-hoops",
  "players": true,
  "slots": [
   {
    "id": "pg",
    "label": "a point guard"
   },
   {
    "id": "sg",
    "label": "a shooting guard"
   },
   {
    "id": "sf",
    "label": "a small forward"
   },
   {
    "id": "pf",
    "label": "a power forward"
   },
   {
    "id": "c",
    "label": "a center"
   }
  ],
  "cards": {
   "pg": [
    "Stephen Curry",
    "Magic Johnson",
    "Gary Payton",
    "Sue Bird",
    "Chris Paul",
    "Steve Nash",
    "Isiah Thomas",
    "John Stockton",
    "Allen Iverson",
    "Russell Westbrook",
    "Luka Doncic",
    "Jason Kidd",
    "Caitlin Clark",
    "Damian Lillard",
    "Shai Gilgeous-Alexander",
    "Courtney Vandersloot",
    "Jalen Brunson",
    "Tyrese Haliburton",
    "Paige Bueckers",
    "Yuki Kawamura",
    "Jeremy Lin",
    "Nate Robinson",
    "Matthew Dellavedova",
    "Muggsy Bogues",
    "Spud Webb",
    "Yuta Tabuse",
    "Anthony Carter",
    "T.J. McConnell",
    "Patrick Beverley",
    "Mario Chalmers",
    "Derek Fisher",
    "Scoot Henderson",
    "Bronny James",
    "Natasha Cloud",
    "Reed Sheppard"
   ],
   "sg": [
    "Michael Jordan",
    "Kobe Bryant",
    "Dwyane Wade",
    "Ray Allen",
    "Diana Taurasi",
    "Klay Thompson",
    "James Harden",
    "Reggie Miller",
    "Jewell Loyd",
    "Anthony Edwards",
    "Devin Booker",
    "Arike Ogunbowale",
    "Kelsey Plum",
    "Jerry West",
    "Manu Ginobili",
    "Vince Carter",
    "Donovan Mitchell",
    "Jaylen Brown",
    "Sabrina Ionescu",
    "Jalen Williams",
    "J.R. Smith",
    "Alex Caruso",
    "Jordan Clarkson",
    "Nick Young",
    "Lou Williams",
    "Jamal Crawford",
    "Kyle Korver",
    "Steve Kerr",
    "Jason Terry",
    "Austin Reaves",
    "Svi Mykhailiuk",
    "Dalton Knecht",
    "Brandin Podziemski",
    "Sophie Cunningham",
    "Dyson Daniels",
    "Jarrett Culver"
   ],
   "sf": [
    "LeBron James",
    "Larry Bird",
    "Kevin Durant",
    "Kawhi Leonard",
    "Scottie Pippen",
    "Maya Moore",
    "Julius Erving",
    "Jayson Tatum",
    "Paul George",
    "Carmelo Anthony",
    "Elgin Baylor",
    "Tamika Catchings",
    "Detlef Schrempf",
    "Jimmy Butler",
    "Candace Parker",
    "Rashard Lewis",
    "Cooper Flagg",
    "Rui Hachimura",
    "Franz Wagner",
    "Mikal Bridges",
    "Brian Scalabrine",
    "Yuta Watanabe",
    "Jaime Jaquez Jr.",
    "Bruce Bowen",
    "Shane Battier",
    "Metta World Peace",
    "Andrei Kirilenko",
    "Matt Barnes",
    "Stephen Jackson",
    "Hedo Turkoglu",
    "P.J. Tucker",
    "Rick Fox",
    "Tony Allen",
    "Josh Hart",
    "Kyle Anderson",
    "Joe Ingles"
   ],
   "pf": [
    "Tim Duncan",
    "Shawn Kemp",
    "Breanna Stewart",
    "Dirk Nowitzki",
    "Giannis Antetokounmpo",
    "Karl Malone",
    "Kevin Garnett",
    "Charles Barkley",
    "Dennis Rodman",
    "A'ja Wilson",
    "Blake Griffin",
    "Pau Gasol",
    "Napheesa Collier",
    "Chris Webber",
    "Anthony Davis",
    "Draymond Green",
    "Paolo Banchero",
    "Zion Williamson",
    "Angel Reese",
    "Evan Mobley",
    "Robert Horry",
    "Kelly Olynyk",
    "Yi Jianlian",
    "Udonis Haslem",
    "Brian Cardinal",
    "Luis Scola",
    "Mehmet Okur",
    "Channing Frye",
    "Charles Oakley",
    "Kurt Rambis",
    "Chuck Hayes",
    "Drew Gooden",
    "Taj Gibson",
    "Nick Collison",
    "Mark Madsen",
    "Glen Davis"
   ],
   "c": [
    "Shaquille O'Neal",
    "Kareem Abdul-Jabbar",
    "Hakeem Olajuwon",
    "Bill Russell",
    "Wilt Chamberlain",
    "Nikola Jokic",
    "Victor Wembanyama",
    "Lisa Leslie",
    "Brittney Griner",
    "Yao Ming",
    "Patrick Ewing",
    "David Robinson",
    "Joel Embiid",
    "Lauren Jackson",
    "Sylvia Fowles",
    "Jack Sikma",
    "Alperen Sengun",
    "Chet Holmgren",
    "Bam Adebayo",
    "Kamilla Cardoso",
    "Boban Marjanovic",
    "Tacko Fall",
    "Bol Bol",
    "Luka Garza",
    "Walker Kessler",
    "Zach Edey",
    "Mark Williams",
    "Manute Bol",
    "Gheorghe Muresan",
    "Shawn Bradley",
    "Steven Adams",
    "Zaza Pachulia",
    "Joakim Noah",
    "Wang Zhizhi",
    "Mark Eaton",
    "Anderson Varejao"
   ]
  },
  "prompts": [
   "Build the starting five that wins a title.",
   "Build the most fun team to watch.",
   "Build the best defensive five ever.",
   "Build the team that wins a pickup game at the park.",
   "Build the five with the best team chemistry.",
   "Build the team that could beat any era.",
   "Build the starting five that sells out every arena.",
   "Build the team you would trust in a Game 7.",
   "Build the bench that wins a pickup game at the Y.",
   "Build the five that wins a charity game by forty.",
   "Build the bench with the loudest celebrations.",
   "Build the team the crowd chants for in garbage time.",
   "Build the five you want on a long road trip.",
   "Build the bench that steals one playoff game.",
   "Build the team that wins the dunk contest and loses the game.",
   "Build the five with the best stories to tell."
  ]
 },
 "date": {
  "name": "Perfect Date",
  "blurb": "Plan a date night to remember.",
  "icon": "theme-date",
  "slots": [
   {
    "id": "place",
    "label": "a place"
   },
   {
    "id": "food",
    "label": "a food"
   },
   {
    "id": "outfit",
    "label": "an outfit"
   },
   {
    "id": "soundtrack",
    "label": "a soundtrack"
   }
  ],
  "cards": {
   "place": [
    "Rooftop Garden",
    "Bowling Alley",
    "Beach at Sunset",
    "Aquarium",
    "Laundromat",
    "Mini Golf",
    "Fancy Restaurant",
    "Arcade",
    "Planetarium",
    "Farmers Market",
    "Ice Rink",
    "The DMV",
    "Picnic in the Park",
    "Karaoke Bar",
    "Corn Maze",
    "Parking Lot"
   ],
   "food": [
    "Sushi",
    "Spaghetti",
    "Tacos",
    "Fondue",
    "Garlic Bread",
    "Cereal",
    "Lobster",
    "Hot Dogs",
    "Midnight Pancakes",
    "Spam Musubi",
    "Street Corn",
    "Chicken Wings",
    "Shave Ice",
    "Plain Rice",
    "Chocolate Fountain",
    "Onion Rings"
   ],
   "outfit": [
    "Tuxedo",
    "Sundress",
    "Hoodie and Sweats",
    "Matching Outfits",
    "Aloha Shirt",
    "Cowboy Boots",
    "Pajamas",
    "Suit and Sneakers",
    "Leather Jacket",
    "Dinosaur Costume",
    "Ball Gown",
    "Soccer Jersey",
    "Bathrobe",
    "Sequin Jacket",
    "Wet Swimsuit",
    "Your Work Uniform"
   ],
   "soundtrack": [
    "Slow Jams",
    "Jazz Piano",
    "Ukulele Music",
    "Elevator Music",
    "Bagpipes",
    "Eighties Hits",
    "Country Ballads",
    "Heavy Metal",
    "Ocean Waves",
    "Cartoon Theme Songs",
    "Violin at the Table",
    "Awkward Silence",
    "Mariachi Band",
    "Your Own Humming",
    "Disco Hits",
    "Whale Sounds"
   ]
  },
  "prompts": [
   "Build the perfect first date.",
   "Build the date that ends with a second date.",
   "Build the most romantic night ever.",
   "Build the date your friends will never stop talking about.",
   "Build the date that costs under ten dollars.",
   "Build the date most likely to go wrong.",
   "Build the date for your fiftieth anniversary.",
   "Build the date that would win a reality show."
  ]
 },
 "nfl": {
  "name": "Gridiron",
  "blurb": "Stars, legends and lovable backups.",
  "icon": "theme-nfl",
  "players": true,
  "slots": [
   {
    "id": "qb",
    "label": "a quarterback"
   },
   {
    "id": "rb",
    "label": "a running back"
   },
   {
    "id": "wr",
    "label": "a wide receiver"
   },
   {
    "id": "te",
    "label": "a tight end"
   },
   {
    "id": "def",
    "label": "a defensive star"
   }
  ],
  "cards": {
   "qb": [
    "Patrick Mahomes",
    "Josh Allen",
    "Lamar Jackson",
    "Joe Burrow",
    "Jalen Hurts",
    "Sam Darnold",
    "Jayden Daniels",
    "Drake Maye",
    "C.J. Stroud",
    "Tom Brady",
    "Peyton Manning",
    "Joe Montana",
    "Dan Marino",
    "John Elway",
    "Aaron Rodgers",
    "Russell Wilson",
    "Matt Hasselbeck",
    "Warren Moon",
    "Marcus Mariota",
    "Tua Tagovailoa",
    "Tim Tebow",
    "Ryan Fitzpatrick",
    "Brian Hoyer",
    "Chase Daniel",
    "Kyle Orton",
    "Jon Kitna",
    "Rex Grossman",
    "Jake Delhomme",
    "Mark Sanchez",
    "Case Keenum",
    "Matt Flynn",
    "Charlie Whitehurst",
    "Nick Foles",
    "Gardner Minshew",
    "Taysom Hill",
    "Doug Flutie",
    "Josh McCown",
    "Tommy DeVito",
    "Timmy Chang",
    "Colt McCoy"
   ],
   "rb": [
    "Marshawn Lynch",
    "Shaun Alexander",
    "Kenneth Walker III",
    "Christian McCaffrey",
    "Saquon Barkley",
    "Derrick Henry",
    "Bijan Robinson",
    "Jahmyr Gibbs",
    "Jonathan Taylor",
    "Ashton Jeanty",
    "De'Von Achane",
    "Josh Jacobs",
    "Barry Sanders",
    "Walter Payton",
    "Emmitt Smith",
    "Jim Brown",
    "LaDainian Tomlinson",
    "Adrian Peterson",
    "Bo Jackson",
    "Eric Dickerson",
    "Danny Woodhead",
    "Mike Alstott",
    "Peyton Hillis",
    "BenJarvus Green-Ellis",
    "Jerome Bettis",
    "Christine Michael",
    "Mack Strong",
    "Leon Washington",
    "Kyle Juszczyk",
    "Patrick Ricard",
    "Darren Sproles",
    "Dexter McCluster",
    "Lorenzo Neal",
    "Chris Carson",
    "Rashaad Penny",
    "Robert Turbin",
    "Jerick McKinnon",
    "Rex Burkhead",
    "James White",
    "Mike Tolbert"
   ],
   "wr": [
    "Jerry Rice",
    "Randy Moss",
    "Steve Largent",
    "Doug Baldwin",
    "Tyler Lockett",
    "DK Metcalf",
    "Jaxon Smith-Njigba",
    "Justin Jefferson",
    "Ja'Marr Chase",
    "CeeDee Lamb",
    "Tyreek Hill",
    "Puka Nacua",
    "Amon-Ra St. Brown",
    "Malik Nabers",
    "A.J. Brown",
    "Davante Adams",
    "Calvin Johnson",
    "Larry Fitzgerald",
    "Terrell Owens",
    "Julio Jones",
    "Julian Edelman",
    "Wes Welker",
    "Jermaine Kearse",
    "Golden Tate",
    "Chad Johnson",
    "Danny Amendola",
    "Victor Cruz",
    "Cole Beasley",
    "Adam Thielen",
    "Hunter Renfrow",
    "David Tyree",
    "Josh Cribbs",
    "Devin Hester",
    "Jake Bobo",
    "Kendrick Bourne",
    "Deion Branch",
    "Wayne Chrebet",
    "Ricky Proehl",
    "Chris Hogan",
    "Cordarrelle Patterson"
   ],
   "te": [
    "Travis Kelce",
    "George Kittle",
    "Rob Gronkowski",
    "Tony Gonzalez",
    "Shannon Sharpe",
    "Antonio Gates",
    "Jason Witten",
    "Mark Andrews",
    "Trey McBride",
    "Brock Bowers",
    "Sam LaPorta",
    "Tyler Warren",
    "Mike Ditka",
    "Kellen Winslow",
    "Jimmy Graham",
    "Zach Ertz",
    "Greg Olsen",
    "Dallas Goedert",
    "Dallas Clark",
    "AJ Barner",
    "Luke Willson",
    "Will Dissly",
    "Martellus Bennett",
    "Vernon Davis",
    "Jared Cook",
    "Kyle Rudolph",
    "Heath Miller",
    "Marcedes Lewis",
    "Delanie Walker",
    "Owen Daniels",
    "Jermichael Finley",
    "Ben Watson",
    "Dan Campbell",
    "Frank Wycheck",
    "Mark Bavaro",
    "Chris Cooley",
    "Julius Thomas",
    "Tyler Eifert",
    "Logan Thomas"
   ],
   "def": [
    "Richard Sherman",
    "Earl Thomas",
    "Kam Chancellor",
    "Bobby Wagner",
    "Cortez Kennedy",
    "Devon Witherspoon",
    "Manti Te'o",
    "DeForest Buckner",
    "Lawrence Taylor",
    "Reggie White",
    "Ray Lewis",
    "Deion Sanders",
    "Troy Polamalu",
    "J.J. Watt",
    "Aaron Donald",
    "T.J. Watt",
    "Myles Garrett",
    "Micah Parsons",
    "Sauce Gardner",
    "Aidan Hutchinson",
    "Michael Bennett",
    "Brandon Mebane",
    "Red Bryant",
    "K.J. Wright",
    "Malcolm Smith",
    "Byron Maxwell",
    "Cliff Avril",
    "James Harrison",
    "Vince Wilfork",
    "William Perry",
    "Brett Keisel",
    "Jared Allen",
    "Tyson Alualu",
    "Jevon Kearse",
    "Clay Matthews",
    "London Fletcher",
    "Tedy Bruschi",
    "Mike Vrabel",
    "Chris Long",
    "Kyle Williams"
   ]
  },
  "prompts": [
   "Build the team that wins the Super Bowl.",
   "Build the offense that scores on every drive.",
   "Build the lineup that wins a snowy playoff game.",
   "Build the team that wins the backyard game on Thanksgiving.",
   "Build the squad with the best touchdown dances.",
   "Build the team you would trust on fourth and one.",
   "Build the lineup that sells the most jerseys.",
   "Build the team that could beat any era.",
   "Build the team that wins the last preseason game.",
   "Build the backups who save the season in December.",
   "Build the squad with the best sideline celebrations.",
   "Build the team the crowd cheers for when the score is 42 to 3.",
   "Build the lineup that wins a flag football game at the park.",
   "Build the team that runs the wildest trick play.",
   "Build the squad you want on a long bus ride.",
   "Build the team with the best stories to tell."
  ]
 },
 "mlb": {
  "name": "Diamond",
  "blurb": "Stars, legends and bench-clearing cult heroes.",
  "icon": "theme-mlb",
  "players": true,
  "slots": [
   {
    "id": "p",
    "label": "a pitcher"
   },
   {
    "id": "c",
    "label": "a catcher"
   },
   {
    "id": "inf",
    "label": "an infielder"
   },
   {
    "id": "of",
    "label": "an outfielder"
   },
   {
    "id": "dh",
    "label": "a designated hitter"
   }
  ],
  "cards": {
   "p": [
    "Yoshinobu Yamamoto",
    "Roki Sasaki",
    "Yu Darvish",
    "Hideo Nomo",
    "Paul Skenes",
    "Tarik Skubal",
    "Logan Gilbert",
    "George Kirby",
    "Bryan Woo",
    "Felix Hernandez",
    "Randy Johnson",
    "Sid Fernandez",
    "Sandy Koufax",
    "Nolan Ryan",
    "Pedro Martinez",
    "Clayton Kershaw",
    "Greg Maddux",
    "Mariano Rivera",
    "Justin Verlander",
    "Jacob deGrom",
    "Bartolo Colon",
    "Rich Hill",
    "Pat Venditte",
    "Jamie Moyer",
    "Fernando Rodney",
    "Brian Wilson",
    "Kenley Jansen",
    "Tim Lincecum",
    "R.A. Dickey",
    "Hideki Okajima",
    "Koji Uehara",
    "Kazuhiro Sasaki",
    "Shintaro Fujinami",
    "Brandon League",
    "Joba Chamberlain",
    "Jonathan Papelbon",
    "Jesse Chavez",
    "Brent Suter",
    "Mark Buehrle",
    "Kent Tekulve"
   ],
   "c": [
    "Cal Raleigh",
    "Kurt Suzuki",
    "Dan Wilson",
    "Kenji Johjima",
    "Johnny Bench",
    "Yogi Berra",
    "Mike Piazza",
    "Ivan Rodriguez",
    "Buster Posey",
    "Yadier Molina",
    "Salvador Perez",
    "Will Smith",
    "Adley Rutschman",
    "William Contreras",
    "J.T. Realmuto",
    "Joe Mauer",
    "Carlton Fisk",
    "Roy Campanella",
    "Gary Carter",
    "Jorge Posada",
    "David Ross",
    "A.J. Pierzynski",
    "Jose Molina",
    "Bengie Molina",
    "Mike Zunino",
    "Jesus Sucre",
    "Jeff Mathis",
    "Drew Butera",
    "Austin Hedges",
    "Erik Kratz",
    "Stephen Vogt",
    "Tom Murphy",
    "Luis Torrens",
    "Brent Mayne",
    "Russell Martin",
    "Jason Varitek",
    "Bob Uecker",
    "Chris Gimenez",
    "Dioner Navarro",
    "Carlos Ruiz"
   ],
   "inf": [
    "Kolten Wong",
    "J.P. Crawford",
    "Kyle Seager",
    "Adrian Beltre",
    "Derek Jeter",
    "Cal Ripken Jr.",
    "Jackie Robinson",
    "Lou Gehrig",
    "Ozzie Smith",
    "Mike Schmidt",
    "Ryne Sandberg",
    "Albert Pujols",
    "Freddie Freeman",
    "Francisco Lindor",
    "Bobby Witt Jr.",
    "Mookie Betts",
    "Jose Altuve",
    "Gunnar Henderson",
    "Elly De La Cruz",
    "Vladimir Guerrero Jr.",
    "David Eckstein",
    "Pablo Sandoval",
    "Willie Bloomquist",
    "Ben Zobrist",
    "Brock Holt",
    "Enrique Hernandez",
    "Nick Punto",
    "Mario Mendoza",
    "Dylan Moore",
    "Lenn Sakata",
    "Munenori Kawasaki",
    "Kevin Youkilis",
    "Jose Iglesias",
    "Sean Casey",
    "John Kruk",
    "Luis Arraez",
    "Willians Astudillo",
    "Ty France",
    "Josh Harrison",
    "Tony Kemp"
   ],
   "of": [
    "Ichiro Suzuki",
    "Ken Griffey Jr.",
    "Julio Rodriguez",
    "Jay Buhner",
    "Randy Arozarena",
    "Shane Victorino",
    "Benny Agbayani",
    "Hideki Matsui",
    "Seiya Suzuki",
    "Babe Ruth",
    "Willie Mays",
    "Hank Aaron",
    "Mickey Mantle",
    "Rickey Henderson",
    "Tony Gwynn",
    "Aaron Judge",
    "Juan Soto",
    "Mike Trout",
    "Ronald Acuna Jr.",
    "Kyle Tucker",
    "Rick Ankiel",
    "Brett Gardner",
    "Jarrod Dyson",
    "Billy Hamilton",
    "Terrance Gore",
    "Endy Chavez",
    "Mitch Haniger",
    "Mike Cameron",
    "Raul Ibanez",
    "Ben Gamel",
    "Hunter Pence",
    "Jonny Gomes",
    "Nick Swisher",
    "Juan Pierre",
    "Coco Crisp",
    "So Taguchi",
    "Kosuke Fukudome",
    "Tsuyoshi Shinjo",
    "Victor Robles",
    "Mike Lum"
   ],
   "dh": [
    "Shohei Ohtani",
    "Edgar Martinez",
    "David Ortiz",
    "Frank Thomas",
    "Nelson Cruz",
    "Yordan Alvarez",
    "Kyle Schwarber",
    "Giancarlo Stanton",
    "Jim Thome",
    "Paul Molitor",
    "Travis Hafner",
    "Harold Baines",
    "Marcell Ozuna",
    "Brent Rooker",
    "J.D. Martinez",
    "Pete Alonso",
    "Eugenio Suarez",
    "Mitch Garver",
    "Edwin Encarnacion",
    "Josh Naylor",
    "Matt Stairs",
    "Lenny Harris",
    "Mark Sweeney",
    "Adam Dunn",
    "Jack Cust",
    "Russell Branyan",
    "Mike Morse",
    "Kendrys Morales",
    "Billy Butler",
    "Dan Vogelbach",
    "Luke Voit",
    "Kevin Millar",
    "Steve Balboni",
    "Cecil Fielder",
    "Mark Trumbo",
    "Josh Willingham",
    "Rowdy Tellez",
    "Pedro Alvarez",
    "Steve Pearce",
    "Wily Mo Pena"
   ]
  },
  "prompts": [
   "Build the team that wins the World Series.",
   "Build the lineup that hits the most home runs.",
   "Build the team with the best defense ever.",
   "Build the team that wins a sandlot game.",
   "Build the lineup that wins a 15 inning game.",
   "Build the team that sells out every ballpark.",
   "Build the team you would trust in a Game 7.",
   "Build the lineup that could beat any era.",
   "Build the team that wins the rain delay.",
   "Build the bench that wins a game in the 17th inning.",
   "Build the team with the best rally caps.",
   "Build the squad that wins the dugout dance off.",
   "Build the lineup the crowd sings for in the seventh inning.",
   "Build the team that wins the company softball game.",
   "Build the bench that steals one playoff game.",
   "Build the team with the best stories to tell."
  ]
 }
};

export const AUCTION_THEMES = {
 "heist": {
  "name": "Heist Crew",
  "blurb": "Bid on crew members and pull off the job.",
  "icon": "theme-heist",
  "slots": [
   {
    "id": "driver",
    "label": "a driver"
   },
   {
    "id": "hacker",
    "label": "a hacker"
   },
   {
    "id": "muscle",
    "label": "the muscle"
   },
   {
    "id": "mastermind",
    "label": "a mastermind"
   }
  ],
  "lots": [
   "The Nervous Intern",
   "The Retired Magician",
   "The Smooth Talker",
   "The Guy Who Knows a Guy",
   "The Quiet Genius",
   "The Ex-Stuntman",
   "The Nosy Neighbor",
   "The Master of Disguise",
   "The Gym Coach",
   "The Sleepy Security Guard",
   "The Chess Grandma",
   "The Know-It-All Teen",
   "The Lucky Rookie",
   "The Safe Cracker",
   "The Clumsy Acrobat",
   "The Pickpocket",
   "The Mall Santa",
   "The Sweaty Locksmith",
   "The Bored Billionaire",
   "The Trained Raccoon"
  ],
  "nameItem": false,
  "itemPrompt": "",
  "prompts": [
   "Pitch why your crew pulls off the job.",
   "Pitch your crew to a very nervous bank.",
   "Explain your getaway plan in one breath.",
   "Pitch the movie about your crew.",
   "Pitch why your crew never gets caught.",
   "Explain what goes wrong first and how you fix it."
  ]
 },
 "vacation": {
  "name": "Dream Vacation",
  "blurb": "Bid your way to the best trip.",
  "icon": "theme-vacation",
  "slots": [
   {
    "id": "flight",
    "label": "the flight"
   },
   {
    "id": "stay",
    "label": "a place to stay"
   },
   {
    "id": "daytrip",
    "label": "a day trip"
   },
   {
    "id": "souvenir",
    "label": "a souvenir moment"
   }
  ],
  "lots": [
   "First Class Seats",
   "Middle Seat by the Bathroom",
   "Beach Villa",
   "Tokyo Food Tour",
   "Paris Rooftop Dinner",
   "Safari Jeep Ride",
   "Northern Lights Cabin",
   "Swim with Dolphins",
   "Grand Canyon Helicopter",
   "Hawaii Snorkel Trip",
   "Castle Sleepover",
   "Theme Park Fast Pass",
   "Hot Spring Soak",
   "Ski Chalet",
   "Private Island Day",
   "Gondola Ride in Venice",
   "Camping in a Thunderstorm",
   "Airport Layover Nap",
   "Cruise Ship Buffet",
   "Space Tourist Seat"
  ],
  "nameItem": false,
  "itemPrompt": "",
  "prompts": [
   "Pitch your trip like a travel ad.",
   "Pitch the trip to your grandma.",
   "Explain the best day of your trip.",
   "Pitch why your trip is worth every dollar.",
   "Describe the postcard you send home.",
   "Pitch your trip to someone who hates travel."
  ]
 },
 "hoops": {
  "name": "Starting Five",
  "blurb": "Stars, legends and cult heroes from any era.",
  "icon": "theme-hoops",
  "players": true,
  "slots": [
   {
    "id": "guard",
    "label": "a guard"
   },
   {
    "id": "wing",
    "label": "a wing"
   },
   {
    "id": "big",
    "label": "a big"
   },
   {
    "id": "sixth",
    "label": "a sixth man"
   }
  ],
  "lots": [
   "Stephen Curry",
   "Gary Payton",
   "Sue Bird",
   "Caitlin Clark",
   "Michael Jordan",
   "Kobe Bryant",
   "Diana Taurasi",
   "LeBron James",
   "Kevin Durant",
   "Breanna Stewart",
   "Maya Moore",
   "Shawn Kemp",
   "A'ja Wilson",
   "Nikola Jokic",
   "Shaquille O'Neal",
   "Victor Wembanyama",
   "Lisa Leslie",
   "Manu Ginobili",
   "Giannis Antetokounmpo",
   "Jewell Loyd",
   "Jeremy Lin",
   "Yuki Kawamura",
   "Nate Robinson",
   "Muggsy Bogues",
   "Matthew Dellavedova",
   "J.R. Smith",
   "Alex Caruso",
   "Jordan Clarkson",
   "Lou Williams",
   "Jamal Crawford",
   "Brian Scalabrine",
   "Robert Horry",
   "Metta World Peace",
   "Yuta Watanabe",
   "Kelly Olynyk",
   "Boban Marjanovic",
   "Tacko Fall",
   "Bol Bol",
   "Manute Bol",
   "Luka Garza"
  ],
  "nameItem": false,
  "itemPrompt": "",
  "prompts": [
   "Pitch why your team wins the title.",
   "Give your team a name and a pregame speech.",
   "Explain how your team closes out a tight game.",
   "Pitch your team to a sold-out arena.",
   "Pitch why you won the auction.",
   "Explain the one play your team runs every time.",
   "Pitch why your bench outplays the starters.",
   "Give your bench mob a name and a handshake.",
   "Explain how your bench wins a game in garbage time.",
   "Pitch your bench to a sold-out crowd at the Y.",
   "Pitch why your sixth man deserves a statue.",
   "Explain the one play your bench runs every time."
  ]
 },
 "zombie": {
  "name": "Zombie Survival",
  "blurb": "Bid on places to raid before the zombies do.",
  "icon": "theme-zombie",
  "slots": [
   {
    "id": "weapon",
    "label": "a weapon"
   },
   {
    "id": "food",
    "label": "food"
   },
   {
    "id": "supply",
    "label": "a shelter supply"
   },
   {
    "id": "luxury",
    "label": "a luxury"
   }
  ],
  "lots": [
   "Costco",
   "Hardware Store",
   "Sporting Goods Store",
   "Grocery Store",
   "Pharmacy",
   "Toy Store",
   "Gas Station",
   "Pet Store",
   "Camping Store",
   "Dollar Store",
   "Bakery",
   "Music Store",
   "School Cafeteria",
   "Garden Center",
   "Bowling Alley",
   "Farm Stand",
   "Bookstore",
   "Candy Shop",
   "Fire Station",
   "Movie Theater"
  ],
  "nameItem": true,
  "itemPrompt": "What do you grab from {lot}?",
  "prompts": [
   "Pitch why your haul keeps you alive.",
   "Explain your first night with this stuff.",
   "Pitch your survival kit to a scared stranger.",
   "Explain which item saves the day and how.",
   "Pitch your haul like a late-night TV ad.",
   "Explain how you would survive a whole year."
  ]
 },
 "date": {
  "name": "Perfect Date",
  "blurb": "Bid on date spots and plan the night.",
  "icon": "theme-date",
  "slots": [
   {
    "id": "first",
    "label": "the first stop"
   },
   {
    "id": "dinner",
    "label": "dinner"
   },
   {
    "id": "dessert",
    "label": "dessert"
   },
   {
    "id": "late",
    "label": "late night"
   }
  ],
  "lots": [
   "Rooftop Bar",
   "Bowling Alley",
   "Beach Bonfire",
   "Aquarium",
   "Mini Golf",
   "Fancy Steakhouse",
   "Taco Truck",
   "Ice Cream Parlor",
   "Arcade",
   "Karaoke Room",
   "Drive-In Movie",
   "Art Museum",
   "Farmers Market",
   "Sushi Counter",
   "Night Market",
   "Stargazing Hill",
   "Ice Skating Rink",
   "Late Night Diner",
   "Pottery Class",
   "Laundromat"
  ],
  "nameItem": false,
  "itemPrompt": "",
  "prompts": [
   "Pitch your date night in one breath.",
   "Pitch the date to someone you want to impress.",
   "Explain the best moment of the night.",
   "Pitch why this date leads to a second date.",
   "Describe the text you send the next morning.",
   "Pitch your date like a movie trailer."
  ]
 },
 "nfl": {
  "name": "Gridiron",
  "blurb": "Stars, legends and lovable backups.",
  "icon": "theme-nfl",
  "players": true,
  "slots": [
   {
    "id": "qb",
    "label": "a quarterback"
   },
   {
    "id": "skill",
    "label": "a skill player"
   },
   {
    "id": "big",
    "label": "a big guy"
   },
   {
    "id": "def",
    "label": "a defender"
   }
  ],
  "lots": [
   "Patrick Mahomes",
   "Josh Allen",
   "Tom Brady",
   "Marcus Mariota",
   "Tua Tagovailoa",
   "Marshawn Lynch",
   "Christian McCaffrey",
   "Saquon Barkley",
   "Jerry Rice",
   "Steve Largent",
   "Jaxon Smith-Njigba",
   "Travis Kelce",
   "Walter Jones",
   "Jason Kelce",
   "Aaron Donald",
   "Cortez Kennedy",
   "Richard Sherman",
   "Earl Thomas",
   "Kam Chancellor",
   "Manti Te'o",
   "Tim Tebow",
   "Ryan Fitzpatrick",
   "Doug Flutie",
   "Gardner Minshew",
   "Timmy Chang",
   "Danny Woodhead",
   "Mike Alstott",
   "Kyle Juszczyk",
   "Jerome Bettis",
   "Julian Edelman",
   "Wes Welker",
   "Devin Hester",
   "Rob Gronkowski",
   "Luke Willson",
   "William Perry",
   "Vince Wilfork",
   "Brandon Mebane",
   "Michael Bennett",
   "Malcolm Smith",
   "James Harrison"
  ],
  "nameItem": false,
  "itemPrompt": "",
  "prompts": [
   "Pitch why your team wins the Super Bowl.",
   "Give your team a name and a halftime speech.",
   "Explain how your team scores on the last drive.",
   "Pitch your team to a stadium full of fans.",
   "Pitch why you won the auction.",
   "Explain the one trick play your team runs every time.",
   "Pitch why your backups outplay the starters.",
   "Give your garbage time crew a name and a handshake.",
   "Explain how your team wins after the starters sit down.",
   "Pitch your team to the fans who stayed until the end.",
   "Pitch why your backup quarterback deserves a statue."
  ]
 },
 "mlb": {
  "name": "Diamond",
  "blurb": "Stars, legends and bench-clearing cult heroes.",
  "icon": "theme-mlb",
  "players": true,
  "slots": [
   {
    "id": "ace",
    "label": "an ace"
   },
   {
    "id": "slugger",
    "label": "a slugger"
   },
   {
    "id": "glove",
    "label": "a glove"
   },
   {
    "id": "closer",
    "label": "a closer"
   }
  ],
  "lots": [
   "Shohei Ohtani",
   "Ichiro Suzuki",
   "Ken Griffey Jr.",
   "Edgar Martinez",
   "Felix Hernandez",
   "Randy Johnson",
   "Julio Rodriguez",
   "Cal Raleigh",
   "Yoshinobu Yamamoto",
   "Roki Sasaki",
   "Paul Skenes",
   "Aaron Judge",
   "Babe Ruth",
   "Hideki Matsui",
   "Shane Victorino",
   "Kurt Suzuki",
   "Kolten Wong",
   "Ozzie Smith",
   "Mariano Rivera",
   "Edwin Diaz",
   "Bartolo Colon",
   "Rich Hill",
   "Pat Venditte",
   "Jamie Moyer",
   "Fernando Rodney",
   "Brian Wilson",
   "Brandon League",
   "David Ross",
   "Bob Uecker",
   "David Eckstein",
   "Pablo Sandoval",
   "Willie Bloomquist",
   "Munenori Kawasaki",
   "Rick Ankiel",
   "Hunter Pence",
   "Billy Hamilton",
   "Tsuyoshi Shinjo",
   "Dan Vogelbach",
   "Adam Dunn",
   "Matt Stairs"
  ],
  "nameItem": false,
  "itemPrompt": "",
  "prompts": [
   "Pitch why your team wins the World Series.",
   "Give your team a name and a walk-up song.",
   "Explain how your team wins in the bottom of the ninth.",
   "Pitch your team to a sold-out ballpark.",
   "Pitch why you won the auction.",
   "Explain the one play your team runs every time.",
   "Pitch why your bench beats the starters.",
   "Give your bench crew a name and a dugout handshake.",
   "Explain how your team wins in extra innings.",
   "Pitch your team to the fans still in their seats in the 14th.",
   "Pitch why your utility player deserves a statue.",
   "Explain the one play your bench runs every time."
  ]
 }
};
